//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "EKStringFactory.h"

@class EKEventDescriptionGenerator;

@interface NCSStringFactory : EKStringFactory
{
    EKEventDescriptionGenerator *_descriptionGenerator;
}

- (id)descriptiveDateStringForEvent:(id)arg1;
- (void).cxx_destruct;
- (id)init;

@end

