//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoCalendarServices/NCSEventStoreObserver.h>

@class NSArray, NSMutableArray, NSObject<OS_dispatch_queue>, NSTimer, NSURL;

@interface NCSUpcomingEventsListener : NCSEventStoreObserver
{
    NSObject<OS_dispatch_queue> *_refreshQueue;
    NSMutableArray *_upcomingTodayEvents;
    NSMutableArray *_todayEvents;
    NSMutableArray *_tomorrowEvents;
    NSTimer *_updateTimer;
    BOOL _reporting;
    BOOL _firstInDay;
    BOOL _overbooked;
    NSArray *_upcomingEvents;
    NSURL *_launchURL;
    CDUnknownBlockType _refinementBlock;
    CDUnknownBlockType _updateBlock;
    unsigned int _searchRange;
}

+ (id)nanoCalendarLaunchURLForDate:(id)arg1;
+ (id)nanoCalendarLaunchURLForEvent:(id)arg1;
+ (id)_calendarIDsForSyncHashes:(id)arg1 inCalendars:(id)arg2;
+ (id)_dateFor5PMTomorrow;
- (void)_significantTimeChange:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType updateBlock; // @synthesize updateBlock=_updateBlock;
@property(nonatomic, getter=isOverbooked) BOOL overbooked; // @synthesize overbooked=_overbooked;
@property(readonly, nonatomic) NSMutableArray *todayEvents; // @synthesize todayEvents=_todayEvents;
@property(retain, nonatomic) NSArray *upcomingEvents; // @synthesize upcomingEvents=_upcomingEvents;
- (void)stopReportingUpcomingEvents;
- (void)startReportingUpcomingEventsWithBlock:(CDUnknownBlockType)arg1;
@property(copy, nonatomic) CDUnknownBlockType refinementBlock; // @synthesize refinementBlock=_refinementBlock;
@property(retain, nonatomic) NSURL *launchURL; // @synthesize launchURL=_launchURL;
@property(nonatomic) unsigned int searchRange; // @synthesize searchRange=_searchRange;
@property(readonly, nonatomic) NSMutableArray *tomorrowEvents; // @synthesize tomorrowEvents=_tomorrowEvents;
@property(readonly, nonatomic) NSMutableArray *upcomingTodayEvents; // @synthesize upcomingTodayEvents=_upcomingTodayEvents;
@property(nonatomic, getter=isFirstInDay) BOOL firstInDay; // @synthesize firstInDay=_firstInDay;
- (BOOL)_isListOfEvents:(id)arg1 equivalentToListOfEvents:(id)arg2;
- (BOOL)_isEvent:(id)arg1 overlappingEvent:(id)arg2;
- (BOOL)_isEvent:(id)arg1 equivalentToEvent:(id)arg2;
- (BOOL)_doesListOfEvents:(id)arg1 containEquivalentForEvent:(id)arg2;
- (void)_resetAllEvents;
- (void)_selectedCalendarsChanged:(id)arg1;
- (void)_releaseAllEvents;
- (void)_reloadAllEvents;
- (void)_updateTimerDidFire:(id)arg1;
- (BOOL)_shouldExcludeEvent:(id)arg1 allowAllDayEvents:(BOOL)arg2;
- (id)_dateForBeginningOfToday;
- (id)_dateForBeginningOfTomorrow;
- (id)_loadEventsForSelectedCalendars:(id)arg1 inDateRange:(id)arg2 allowAllDay:(BOOL)arg3;
- (id)_dateForEndOfToday;
- (id)_dateForNow;
- (BOOL)_doesEvent:(id)arg1 overlapAnyEventsIn:(id)arg2;
- (void)_scheduleUpdateTimerForDate:(id)arg1;
- (id)_internalRefineEventsAndGetUpdateTimerFireDate:(id)arg1;
- (id)loadTomorrowEventsIfNecessary;
- (id)loadTodayEventsIfNecessary;
- (id)loadUpcomingTodayEventsIfNecessary;
- (void)_trimStaleEventsFrom:(id)arg1;
- (void)_resetTimers;
- (id)_loadTomorrowEventsForSelectedCalendars:(id)arg1;
- (id)_loadUpcomingTodayEventsForSelectedCalendars:(id)arg1;
- (id)_loadTodayEventsForSelectedCalendars:(id)arg1;
- (id)_selectedCalendars;
- (void)_reportEventsIfAllowed;
- (void)_evaluateEventsAndReportIfAllowed;
- (void)eventStoreWillClose;
- (void)databaseChanged:(id)arg1;
- (void)_todayChanged:(id)arg1;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;
- (void)stopObserving;
- (void)startObserving;
- (void)_localeChanged;

@end

