//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIFont.h"

@interface UIFont (NCSAdditions)
+ (id)ncs_eventTitleFont;
+ (id)ncs_footnote1ShortTimeFeaturesFont;
+ (id)ncs_headlineShortFont;
+ (id)ncs_headlineFont;
+ (id)ncs_headlineSemiBoldFont;
+ (id)ncs_bodyMediumFont;
+ (id)ncs_footnote1Font;
+ (id)ncs_glanceBodyFont;
+ (id)ncs_bodyTimeFeaturesFont;
+ (id)ncs_bodyShortFont;
+ (id)scaled_eventTitleFontAtCurrentContentSize;
+ (id)ncs_footnote1ShortFont;
+ (id)ncs_bodyFont;
+ (void)_clearCachedFonts;
+ (void)load;
- (id)fontByApplyingFeatureSettings:(id)arg1;
@end

