//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SPCacheAsset : NSObject
{
    NSString *_key;
    unsigned int _state;
    unsigned int _size;
    double _accessDate;
}

+ (id)fromProto:(id)arg1;
+ (id)toProto:(id)arg1;
- (id)initWithName:(id)arg1 size:(unsigned int)arg2 state:(unsigned int)arg3 accessDate:(id)arg4;
@property(nonatomic) double accessDate; // @synthesize accessDate=_accessDate;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *key; // @synthesize key=_key;
@property(nonatomic) unsigned int size; // @synthesize size=_size;
@property(nonatomic) unsigned int state; // @synthesize state=_state;

@end

