//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <SockPuppetGizmo/SPInterfaceLabel.h>

@class NSDate, NSDateFormatter, NSTimer, UIFont;

@interface SPInterfaceDateLabel : SPInterfaceLabel
{
    NSDateFormatter *_formatter;
    NSTimer *_timer;
    NSDate *_forcedDate;
    UIFont *_smallCapsFont;
    double _updateInterval;
    struct _NSRange _smallCapsRange;
}

+ (id)smallCapsFontFeatureSetting;
+ (id)monospaceFontFeatureSetting;
+ (id)smallCapsFontWithFont:(id)arg1;
+ (id)monospacedFontWithFont:(id)arg1;
@property(nonatomic) struct _NSRange smallCapsRange; // @synthesize smallCapsRange=_smallCapsRange;
@property(retain, nonatomic) UIFont *smallCapsFont; // @synthesize smallCapsFont=_smallCapsFont;
@property(copy, nonatomic) NSDate *forcedDate; // @synthesize forcedDate=_forcedDate;
- (id)initWithItemDescription:(id)arg1 bundle:(id)arg2 stringsFileName:(id)arg3;
- (void)setInterfaceItemValue:(id)arg1 property:(id)arg2;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
- (void).cxx_destruct;
- (void)updateText;
- (void)updateTimer;
@property(nonatomic) double updateInterval; // @synthesize updateInterval=_updateInterval;
- (void)didMoveToWindow;
- (void)dealloc;
@property(retain, nonatomic) NSDateFormatter *formatter; // @synthesize formatter=_formatter;

@end

