//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

#import "SPInterfaceItem.h"

@class NSArray, NSBundle, NSDictionary, NSString, UIColor;

@interface SPInterfaceGroupView : UIImageView <SPInterfaceItem>
{
    BOOL _clipsContentsVertically;
    BOOL _isNotification;
    BOOL _isSection;
    BOOL _isSectionDefault;
    BOOL _isRoot;
    BOOL _isTableRowRoot;
    BOOL _marginsSet;
    BOOL _radiusSet;
    BOOL _heightSet;
    BOOL _shouldRenderBackgroundColorAsImage;
    BOOL _defaultAnimate;
    id <SPInterfaceDelegate> _delegate;
    int _groupViewLayout;
    NSDictionary *_companionProperty;
    int _interfaceAlignment;
    int _verticalInterfaceAlignment;
    float _width;
    float _widthAdjustment;
    float _height;
    float _heightAdjustment;
    float _spacing;
    NSBundle *_bundle;
    NSString *_stringsFileName;
    UIColor *_renderedBackgroundColor;
    NSArray *_allAnimationImages;
    struct CGSize _fixedSize;
    double _defaultDuration;
    struct UIEdgeInsets _margins;
}

@property(nonatomic) float spacing; // @synthesize spacing=_spacing;
@property(nonatomic) BOOL isSectionDefault; // @synthesize isSectionDefault=_isSectionDefault;
@property(nonatomic) BOOL isSection; // @synthesize isSection=_isSection;
- (void)applyTableCellDefaultAppearance;
- (void)removePropertiesForGlanceContentView;
- (void)setInterfaceItemValue:(id)arg1 forKey:(id)arg2 property:(id)arg3;
- (id)initWithItemDescription:(id)arg1 bundle:(id)arg2 stringsFileName:(id)arg3;
@property(nonatomic) struct CGSize fixedSize; // @synthesize fixedSize=_fixedSize;
- (void)setStaticNotificationAlertLabelText:(id)arg1;
@property(nonatomic) BOOL heightSet; // @synthesize heightSet=_heightSet;
@property(nonatomic) BOOL radiusSet; // @synthesize radiusSet=_radiusSet;
@property(nonatomic) BOOL marginsSet; // @synthesize marginsSet=_marginsSet;
@property(nonatomic) BOOL isTableRowRoot; // @synthesize isTableRowRoot=_isTableRowRoot;
@property(nonatomic) int verticalInterfaceAlignment; // @synthesize verticalInterfaceAlignment=_verticalInterfaceAlignment;
@property(nonatomic) int interfaceAlignment; // @synthesize interfaceAlignment=_interfaceAlignment;
@property(nonatomic) BOOL clipsContentsVertically; // @synthesize clipsContentsVertically=_clipsContentsVertically;
- (BOOL)hasIntrinsicHeight;
- (id)visibleSubviews;
- (BOOL)hasDefinedWidth;
- (BOOL)hasDefinedHeight;
@property(nonatomic) float widthAdjustment; // @synthesize widthAdjustment=_widthAdjustment;
@property(nonatomic) float heightAdjustment; // @synthesize heightAdjustment=_heightAdjustment;
@property(copy, nonatomic) NSArray *allAnimationImages; // @synthesize allAnimationImages=_allAnimationImages;
@property(retain, nonatomic) UIColor *renderedBackgroundColor; // @synthesize renderedBackgroundColor=_renderedBackgroundColor;
@property(nonatomic) BOOL shouldRenderBackgroundColorAsImage; // @synthesize shouldRenderBackgroundColorAsImage=_shouldRenderBackgroundColorAsImage;
- (id)generateBackgroundPlatterImageWithColor:(id)arg1;
@property(copy, nonatomic) NSString *stringsFileName; // @synthesize stringsFileName=_stringsFileName;
- (BOOL)_setInterfaceItemValue:(id)arg1 forKey:(id)arg2 property:(id)arg3;
@property(copy, nonatomic) NSDictionary *companionProperty; // @synthesize companionProperty=_companionProperty;
- (void)setInterfaceItemValue:(id)arg1 property:(id)arg2;
@property(nonatomic) BOOL defaultAnimate; // @synthesize defaultAnimate=_defaultAnimate;
- (void)action:(id)arg1 value:(id)arg2;
@property(nonatomic) int groupViewLayout; // @synthesize groupViewLayout=_groupViewLayout;
@property(nonatomic) BOOL isRoot; // @synthesize isRoot=_isRoot;
@property(nonatomic) double defaultDuration; // @synthesize defaultDuration=_defaultDuration;
- (id)allProperties;
@property(nonatomic) BOOL isNotification; // @synthesize isNotification=_isNotification;
@property(nonatomic) struct UIEdgeInsets margins; // @synthesize margins=_margins;
@property(nonatomic) float height; // @synthesize height=_height;
- (void).cxx_destruct;
@property(nonatomic) float width; // @synthesize width=_width;
@property(retain, nonatomic) NSBundle *bundle; // @synthesize bundle=_bundle;
- (struct UIEdgeInsets)alignmentRectInsets;
@property(nonatomic) __weak id <SPInterfaceDelegate> delegate; // @synthesize delegate=_delegate;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

