//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@class NSMutableArray;

@interface SPProtoCacheAssets : PBCodable <NSCopying>
{
    NSMutableArray *_assets;
}

- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (id)assetsAtIndex:(unsigned int)arg1;
- (void)clearAssets;
- (void)addAssets:(id)arg1;
@property(retain, nonatomic) NSMutableArray *assets; // @synthesize assets=_assets;
- (unsigned int)assetsCount;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;

@end

