//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@class NSString;

@interface SPProtoCacheAsset : PBCodable <NSCopying>
{
    double _accessDate;
    unsigned long long _size;
    NSString *_key;
    unsigned int _state;
}

- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)mergeFrom:(id)arg1;
@property(nonatomic) double accessDate; // @synthesize accessDate=_accessDate;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *key; // @synthesize key=_key;
- (id)dictionaryRepresentation;
@property(nonatomic) unsigned long long size; // @synthesize size=_size;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(nonatomic) unsigned int state; // @synthesize state=_state;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;

@end

