//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSString;

@interface SYStatisticStore : NSObject
{
    NSString *_path;
    struct sqlite3 *_db;
    struct sqlite3_stmt *_insertIncoming;
    struct sqlite3_stmt *_addErrorIncoming;
    struct sqlite3_stmt *_markCompleteIncoming;
    struct sqlite3_stmt *_insertOutgoing;
    struct sqlite3_stmt *_updateOutgoingIdentifier;
    struct sqlite3_stmt *_updateOutgoing;
    struct sqlite3_stmt *_timestampForID;
    struct sqlite3_stmt *_reserveRowID;
    struct sqlite3_stmt *_responseReceived;
    struct sqlite3_stmt *_requestAcked;
    long long _lastIncomingRowID;
    NSObject<OS_dispatch_queue> *_operations_queue;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)confirmDeliveryOfOutgoingMessage:(id)arg1;
- (void)updateOutgoingMessageWithIdentifier:(id)arg1 didReceiveResponse:(_Bool)arg2 error:(id)arg3;
- (void)updateOutgoingMessageWithIdentifier:(id)arg1 forService:(id)arg2 sentSuccessfully:(_Bool)arg3 sendError:(id)arg4;
- (void)assignIdentifier:(id)arg1 toOutgoingMessage:(id)arg2;
- (void)recordOutgoingMessage:(id)arg1 forService:(id)arg2;
- (void)markLastIncomingMessageComplete;
- (void)updateLastIncomingMessageWithError:(id)arg1;
- (void)recordIncomingMessage:(id)arg1 forService:(id)arg2;
- (id)_unpackMessageData:(id)arg1;
- (void)_unpackPBResponse:(id)arg1 forMessageID:(unsigned short)arg2 intoDictionary:(id)arg3;
- (void)_unpackPBRequest:(id)arg1 forMessageID:(unsigned short)arg2 intoDictionary:(id)arg3;
- (id)_keySetForMessageLogTable;
- (double)_getMachTimestamp;
- (void)_openDB;
- (int)_getSchemaVersion;
- (_Bool)_openDBFile:(_Bool)arg1;
- (void)_ensureCorrectFileOwnership:(id)arg1;
- (_Bool)_tableEmpty:(id)arg1;
- (void)dealloc;
- (id)initWithPath:(id)arg1;
- (id)init;
- (id)operationQ;
- (struct sqlite3 *)dbRef;

@end

