//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SYTransportLog : NSObject
{
    NSString *_rootPath;
    NSString *_facility;
}

+ (id)sharedInstance;
@property(copy, nonatomic) NSString *facility; // @synthesize facility=_facility;
- (void).cxx_destruct;
- (void)_logMessage:(id)arg1 file:(const char *)arg2 line:(int)arg3 function:(const char *)arg4;
- (void)logMessage:(id)arg1 args:(struct __va_list_tag [1])arg2;
- (void)logMessage:(id)arg1;
- (id)_setupLog;
- (_Bool)_ensureFolder;
- (id)init;

@end

