//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView;

@interface PUICStatusView : UIView
{
    unsigned long long _statusViewState;
    UIImageView *_doNotDisturb;
    UIImageView *_airplaneMode;
    UIImageView *_unreadNotifications;
}

@property(retain, nonatomic) UIImageView *unreadNotifications; // @synthesize unreadNotifications=_unreadNotifications;
@property(retain, nonatomic) UIImageView *airplaneMode; // @synthesize airplaneMode=_airplaneMode;
@property(retain, nonatomic) UIImageView *doNotDisturb; // @synthesize doNotDisturb=_doNotDisturb;
@property(nonatomic) unsigned long long statusViewState; // @synthesize statusViewState=_statusViewState;
- (void).cxx_destruct;
- (void)_transitionInToState:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_transitionOutFromState:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;
- (CDStruct_c3b9c2ee)_animationParametersForState:(unsigned long long)arg1;
- (void)_transitionFromState:(unsigned long long)arg1 toState:(unsigned long long)arg2;
- (id)_viewForStatusViewState:(unsigned long long)arg1;
- (void)setStatusViewState:(unsigned long long)arg1 animated:(_Bool)arg2;

@end

