//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface PUICButton : UIButton
{
}

+ (id)buttonWithType:(long long)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)_updateBackgroundImage;
- (void)setHighlighted:(_Bool)arg1;
- (void)tintColorDidChange;
- (id)initWithFrame:(struct CGRect)arg1;

@end

