//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class PUICTableViewCellActionBar, PUICTableViewCellBackgroundView, UIColor, UIView;

@interface PUICTableViewCell : UITableViewCell
{
    PUICTableViewCellBackgroundView *_backgroundPillView;
    _Bool _isInsetByTap;
    _Bool _isInteractive;
    _Bool _clippedBeforeSwiping;
    _Bool _hasSetBackgroundColor;
    double _swipeDistancePulled;
    _Bool _usesCustomBackground;
    _Bool _usesDynamicType;
    _Bool _radioSectionCell;
    UIView *_contentWrapperView;
    PUICTableViewCellActionBar *_actionBar;
}

+ (double)defaultContentHeight;
+ (double)defaultCellHeight;
+ (id)cellIdentifier;
+ (id)cellForTableView:(id)arg1 style:(long long)arg2 reuseIdentifier:(id)arg3;
+ (id)cellForTableView:(id)arg1;
+ (void)setUsesConstraintBasedLayout:(_Bool)arg1;
+ (_Bool)usesConstraintBasedLayout;
+ (double)gapSeparatorHeight;
+ (id)_transparentBackgroundPillColor;
+ (id)_backgroundPillColor;
@property(retain, nonatomic) PUICTableViewCellActionBar *actionBar; // @synthesize actionBar=_actionBar;
@property(readonly, nonatomic) UIView *contentWrapperView; // @synthesize contentWrapperView=_contentWrapperView;
@property(nonatomic, getter=isRadioSectionCell) _Bool radioSectionCell; // @synthesize radioSectionCell=_radioSectionCell;
- (void).cxx_destruct;
- (id)_contentBackgroundColor;
- (void)_updateSeparatorContent;
- (double)_marginWidth;
- (void)didMoveToSuperview;
@property(retain, nonatomic) UIColor *backgroundPillColor;
- (void)setBackgroundColor:(id)arg1;
- (void)_puic_setBackgroundColor:(id)arg1;
- (void)_updateCellContentColor:(id)arg1 opaque:(_Bool)arg2;
- (void)setBackgroundView:(id)arg1;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelectionStyle:(long long)arg1;
- (void)_setHiliteMode:(_Bool)arg1 animated:(_Bool)arg2;
- (struct CGSize)systemLayoutSizeFittingSize:(struct CGSize)arg1 withHorizontalFittingPriority:(float)arg2 verticalFittingPriority:(float)arg3;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setSeparatorStyle:(long long)arg1;
- (void)setSectionLocation:(int)arg1 animated:(_Bool)arg2;
- (void)prepareForReuse;
- (void)_systemTextSizeChanged;
@property(nonatomic) _Bool usesDynamicType;
- (void)_didCreateContentView;
- (void)_replaceContentView;
- (id)_puicContentView;
- (void)_adjustBackgroundPill;
@property(nonatomic) _Bool usesCustomBackground;
- (void)setUserInteractionEnabled:(_Bool)arg1;
@property(nonatomic, getter=isInteractive) _Bool interactive;
- (struct CGSize)cellSizeForContentSize:(struct CGSize)arg1;
- (void)_usesConstraintsChanged;
- (id)_puicTableView;
- (void)_setSwipeToDeleteViewObject:(id)arg1;
- (id)_swipeToDeleteViewObject;
- (void)_setSwipeCancellationRecognizerObject:(id)arg1;
- (id)_swipeCancellationRecognizerObject;
- (void)_setupContentWrapperView;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (id)initWithCellIdentifier:(id)arg1;
- (struct CGRect)actionBarFrame;

@end

