//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIDevice.h"

@interface UIDevice (PUICAdditionsSim)
@property(nonatomic) long long overrideDeviceVariant; // @dynamic overrideDeviceVariant;
@property(readonly, nonatomic) _Bool overrideDeviceVariantHasBeenSet; // @dynamic overrideDeviceVariantHasBeenSet;
@end

