//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface NPHDestinationDisplayDetails : NSObject
{
    NSString *_destinationID;
    NSString *_title;
    NSString *_subTitle;
}

@property(readonly, nonatomic) NSString *destinationID; // @synthesize destinationID=_destinationID;
- (id)initWithDestinationID:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) NSString *description;
@property(readonly, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;

@end

