//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CALayer;

@interface GraphViewSegment : NSObject
{
    float avghistory[33];
    float rssihistory[33];
    int index;
    CALayer *layer;
}

- (BOOL)addAvg:(float)arg1 liveRSSI:(float)arg2;
- (BOOL)isVisibleInRect:(struct CGRect)arg1;
- (void).cxx_destruct;
- (id)accessibilityValue;
- (void)reset;
- (id)actionForLayer:(id)arg1 forKey:(id)arg2;
- (void)drawLayer:(id)arg1 inContext:(struct CGContext *)arg2;
- (id)init;
@property(readonly, nonatomic) CALayer *layer; // @synthesize layer;
- (BOOL)isFull;

@end

