//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableDictionary;

@interface _NTKPolygonCylinderTransformView : UIView
{
    unsigned int _numberOfFaces;
    float _interiorAngle;
    float _exteriorAngle;
    NSMutableDictionary *_faceViews;
    float _faceDistanceToCenter;
}

+ (Class)layerClass;
- (struct CATransform3D)_transformForFaceIndex:(unsigned int)arg1;
@property(readonly, nonatomic) float faceDistanceToCenter; // @synthesize faceDistanceToCenter=_faceDistanceToCenter;
@property(readonly, nonatomic) float rotationAnglePerFace;
- (void)enumerateFaceViewsWithBlock:(CDUnknownBlockType)arg1;
- (id)viewForFaceAtIndex:(unsigned int)arg1;
- (void)setView:(id)arg1 forFaceAtIndex:(unsigned int)arg2;
@property(readonly, nonatomic) unsigned int numberOfFaces; // @synthesize numberOfFaces=_numberOfFaces;
- (id)initWithNumberOfFaces:(unsigned int)arg1;
- (void).cxx_destruct;
- (void)setBounds:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;

@end

