//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoTimeKit/NTKColorComplicationView.h>

#import "NTKAlarmComplicationDisplay.h"
#import "NTKTimeFormatterObserver.h"

@class NSDate, NSString, NTKColoringImageView, NTKColoringLabel, NTKDigitalTimeLabel;

@interface NTKAlarmColorComplicationView : NTKColorComplicationView <NTKAlarmComplicationDisplay, NTKTimeFormatterObserver>
{
    NTKDigitalTimeLabel *_timeLabel;
    NTKColoringLabel *_designatorLabel;
    NTKColoringLabel *_alternativeTimeLabel;
    NTKColoringImageView *_image;
    BOOL _showAlternativeTimeLabel;
    NSDate *_alarmDate;
    int _alarmState;
}

- (void)_setShowAlternativeLabel:(BOOL)arg1;
- (void)timeFormatterTextDidChange:(id)arg1;
- (void)setStateSnoozingWithDuration:(double)arg1;
- (void)setStateActiveWithDate:(id)arg1;
- (void)setStateNoAlarms;
- (void)setStateAllAlarmsOff;
- (void)_updateTime;
- (void)setAnimatesForegroundColors:(BOOL)arg1;
- (void).cxx_destruct;
- (void)setForegroundColor:(id)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(nonatomic) unsigned int complicationType;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) __weak id <NTKComplicationDisplayObserver> displayObserver;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

