//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AlarmDelegate.h"
#import "NSXPCListenerDelegate.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>, NSString, NTKAlarm;

@interface NTKAlarmServer : NSObject <NSXPCListenerDelegate, AlarmDelegate>
{
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableArray *_clientConnections;
    NSMutableArray *_ntkAlarms;
    NTKAlarm *_nextAlarm;
    BOOL _isCarouselReady;
    BOOL _isRestoreDone;
    BOOL _isServerReady;
}

+ (id)bundleIDForNotifications;
+ (BOOL)isAlarmNotification:(id)arg1;
+ (void)run;
- (void)_F5ResetAlarms;
- (void)getAllAlarmsWithHandler:(CDUnknownBlockType)arg1;
- (void)requestUpdateAlarms;
- (void)setAlarm:(id)arg1 isActive:(BOOL)arg2;
- (void)updateAlarm:(id)arg1;
- (void)_handleCarouselReady;
- (void)alarmDidUpdate:(id)arg1;
- (void)addAlarm:(id)arg1 withHandler:(CDUnknownBlockType)arg2;
- (void)deleteAlarm:(id)arg1;
- (void)_handleRestoreDone;
- (void)_updateAlarm:(id)arg1 fromNTKAlarm:(id)arg2;
- (void)_updateForSnoozedNotification:(id)arg1;
- (void)_updateForNotification:(id)arg1;
- (void)_queue_updateOneAlarm:(id)arg1 clientsExcept:(id)arg2;
- (void)_queue_updateAllAlarmsClientsExcept:(id)arg1;
- (void)_handleSignificantTimeChange:(id)arg1;
- (void)_handleSnoozedNotification:(id)arg1;
- (void)_handleLocalNotificationDidFire:(id)arg1;
- (void)_reloadNTKAlarmList;
- (void)_queue_updateNextAlarm;
- (void)_startServerIfReady;
- (void)_initServer;
- (void)_updateNextAlarm;
- (id)_createNTKAlarmFromAlarm:(id)arg1;
- (void)_observeDemoMovieNotifications:(BOOL)arg1;
- (void)_prepareAlarmServerForStoreDemo;
- (BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

