//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoTimeKit/NTKDigitalFaceView.h>

@class NTKDigitalTimeLabel, NTKEditOption, UIImageView, UIView;

@interface NTKBackgroundImageFaceView : NTKDigitalFaceView
{
    NTKEditOption *_editOptionFrom;
    UIView *_transitionViewFrom;
    NTKEditOption *_editOptionTo;
    UIView *_transitionViewTo;
    UIView *_animationView;
    UIImageView *_animationMaskImageView;
    NTKDigitalTimeLabel *_timeLabel;
    UIView *_zoomMaskView;
    UIImageView *_zoomVignette;
    UIView *_borrowedCircleView;
    UIView *_borrowedTimeView;
    struct CGPoint _timeViewZoomEndingCenter;
    struct CGRect _vignetteZoomStartingBounds;
    struct CGRect _maskZoomStartingBounds;
}

- (void)_removeAllSubviewsFrom:(id)arg1;
- (void)_didTransitionToOptionView:(id)arg1;
- (void)setTimeLabelBlinkingPaused:(BOOL)arg1;
- (void)_applyRubberBandingFraction:(float)arg1 forCustomEditMode:(int)arg2;
- (void)_applyBreathingFraction:(float)arg1 forCustomEditMode:(int)arg2;
- (void)_bringForegroundViewsToFront;
- (void)_layoutForegroundContainerView;
- (id)_viewForEditOption:(id)arg1;
- (void)_beginTransitionToOption;
- (void)_cleanupAfterOptionTransitionForCustomEditMode:(int)arg1;
- (void)setViewMode:(int)arg1;
- (float)_parallaxScaleFactor;
- (id)_animationImageView;
@property(nonatomic) struct CGPoint timeViewZoomEndingCenter; // @synthesize timeViewZoomEndingCenter=_timeViewZoomEndingCenter;
@property(retain, nonatomic) UIView *zoomMaskView; // @synthesize zoomMaskView=_zoomMaskView;
@property(nonatomic) struct CGRect maskZoomStartingBounds; // @synthesize maskZoomStartingBounds=_maskZoomStartingBounds;
@property(nonatomic) struct CGRect vignetteZoomStartingBounds; // @synthesize vignetteZoomStartingBounds=_vignetteZoomStartingBounds;
@property(retain, nonatomic) UIImageView *zoomVignette; // @synthesize zoomVignette=_zoomVignette;
- (BOOL)_needsVignette;
@property(retain, nonatomic) UIView *borrowedTimeView; // @synthesize borrowedTimeView=_borrowedTimeView;
@property(retain, nonatomic) UIView *borrowedCircleView; // @synthesize borrowedCircleView=_borrowedCircleView;
- (float)_timeLabelAlphaForEditMode:(int)arg1;
- (float)_backgroundImageAlphaForEditMode:(int)arg1;
- (float)_rightSideMarginForDigitalTimeHeroPosition;
- (id)_selectedContentView;
- (BOOL)_fadesComplicationSlot:(id)arg1 inEditMode:(int)arg2;
- (unsigned int)_keylineLabelAlignmentForCustomEditMode:(int)arg1;
- (id)_keylineViewForCustomEditMode:(int)arg1;
- (void)_applyTransitionFraction:(float)arg1 fromOption:(id)arg2 toOption:(id)arg3 forCustomEditMode:(int)arg4;
- (BOOL)_usesCustomZoom;
- (void)_performWristRaiseAnimation;
- (void)_prepareWristRaiseAnimation;
- (void)_loadSnapshotContentViews;
- (void)_configureForTransitionFraction:(float)arg1 fromEditMode:(int)arg2 toEditMode:(int)arg3;
- (void)_configureForEditMode:(int)arg1;
- (float)_keylineCornerRadiusForComplicationSlot:(id)arg1;
- (unsigned int)_keylineLabelAlignmentForComplicationSlot:(id)arg1;
- (id)_newComplicationViewOfType:(unsigned int)arg1 forSlot:(id)arg2;
- (void)_loadLayoutRules;
- (BOOL)_needsForegroundContainerView;
- (void)_cleanupAfterZoom;
- (void)_setZoomFraction:(float)arg1 iconDiameter:(float)arg2;
- (void)_prepareToZoomWithIconView:(id)arg1 minDiameter:(float)arg2 maxDiameter:(float)arg3;
@property(retain, nonatomic) NTKDigitalTimeLabel *timeLabel; // @synthesize timeLabel=_timeLabel;
- (void).cxx_destruct;

@end

