//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NTKBezierPathPointModel, UIBezierPath, UIColor;

@interface NTKBezierPathView : UIView
{
    UIBezierPath *_path;
    UIBezierPath *_animateToPath;
    NTKBezierPathPointModel *_pointModel;
    UIColor *_pathColor;
}

+ (Class)layerClass;
@property(retain, nonatomic) UIColor *pathColor; // @synthesize pathColor=_pathColor;
@property(readonly, nonatomic) NTKBezierPathPointModel *pointModel; // @synthesize pointModel=_pointModel;
- (void)animateToPath:(id)arg1 duration:(double)arg2 curve:(int)arg3;
- (struct CGPoint)pointOnPathForHorizontalPercentage:(float)arg1;
- (id)_shapeLayer;
- (void).cxx_destruct;
@property(retain, nonatomic) UIBezierPath *path; // @synthesize path=_path;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;

@end

