//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

#import "NTKColoringView.h"
#import "NTKLabel.h"

@class NSAttributedString, NSString, UIColor, UIFont, _NTKColorManager;

@interface NTKColoringLabel : UILabel <NTKColoringView, NTKLabel>
{
    unsigned int _options;
    _NTKColorManager *_colorManager;
    struct CGSize _cachedSingleLineSize;
    BOOL _cachedSizeIsValid;
}

+ (id)labelWithOptions:(unsigned int)arg1;
- (BOOL)_wantsDynamicTracking;
- (void)invalidateCachedSize;
- (void)_updateTextColor;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned int options; // @synthesize options=_options;
@property(retain, nonatomic) UIColor *color;
@property(readonly, nonatomic) float _lastLineBaseline;
- (id)forwardingTargetForSelector:(SEL)arg1;
@property(retain, nonatomic) UIColor *textColor;
@property(copy, nonatomic) NSAttributedString *attributedText;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (void)setShadowOffset:(struct CGSize)arg1;
@property(copy, nonatomic) NSString *text;
@property(retain, nonatomic) UIFont *font;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setBackgroundColor:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 options:(unsigned int)arg2;

// Remaining properties
@property(nonatomic) BOOL colorIsAnimatable; // @dynamic colorIsAnimatable;
@property(readonly, nonatomic) UIColor *contentColor; // @dynamic contentColor;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;
@property(nonatomic) int textAlignment;

@end

