//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class NSArray, SKAction;

@interface NTKCollectionNode : SKNode
{
    NSArray *_nodes;
    SKAction *_appearAction;
    SKAction *_disappearAction;
    CDUnknownBlockType _animateBlock;
    float _radius;
}

+ (id)labels3_10_90Chrono;
+ (id)labels3Chrono;
+ (id)labels6_10_40Chrono;
+ (id)labels6Chrono;
+ (id)ticks6Chrono;
+ (id)labels30Chrono;
+ (id)ticks30Chrono;
+ (id)labels60Chrono;
+ (id)hoursChrono;
+ (id)ticks60Chrono;
+ (id)ticksColorAnalog;
+ (id)minutesUtilitarian;
+ (id)hours12;
+ (id)hours4;
+ (id)ticks60Utilitarian;
+ (id)minutesPills;
+ (id)ticks240;
+ (id)ticksPills;
+ (id)ticks120;
+ (id)ticks60;
+ (float)innerRadius;
+ (float)outerRadius;
@property(retain, nonatomic) NSArray *nodes; // @synthesize nodes=_nodes;
@property(copy, nonatomic) CDUnknownBlockType animateBlock; // @synthesize animateBlock=_animateBlock;
- (void)fadeAndScale:(float)arg1;
- (void)scaleNodes:(float)arg1;
- (void)fadeNodes:(float)arg1;
- (void)updateNodesWithOffset:(unsigned int)arg1 angleMultiplier:(float)arg2 rotate:(BOOL)arg3;
- (void)colorize:(id)arg1 c1:(float)arg2 c2:(float)arg3;
- (void)disappearAnimated;
- (void)appearAnimated;
- (void)scaleNodes:(float)arg1 andResetNodesAtIndices:(id)arg2;
- (void)fadeNodes:(float)arg1 except:(id)arg2;
- (void)updateNodesWithOffset:(unsigned int)arg1 angleMultiplier:(float)arg2 scale:(float)arg3 rotate:(BOOL)arg4;
@property(retain, nonatomic) SKAction *disappearAction; // @synthesize disappearAction=_disappearAction;
@property(retain, nonatomic) SKAction *appearAction; // @synthesize appearAction=_appearAction;
- (id)initWithName:(id)arg1 nodes:(id)arg2 animateBlock:(CDUnknownBlockType)arg3;
- (void)fade:(float)arg1;
- (void)applyAppearanceFraction:(float)arg1;
- (void)createSubNodes;
- (void)scaleFromLast:(float)arg1;
- (void).cxx_destruct;
- (id)init;
@property(nonatomic) float radius; // @synthesize radius=_radius;

@end

