//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIEvent;

@protocol NTKClockHardwareInput <NSObject>
- (BOOL)_handlePhysicalButton:(unsigned int)arg1 event:(unsigned int)arg2;
- (BOOL)_wheelChangedWithEvent:(UIEvent *)arg1;
@end

