//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoTimeKit/NTKAnalogTimeView.h>

@interface NTKChronoTimeView : NTKAnalogTimeView
{
}

- (double)currentTime;
- (void)applyTransitionFraction:(float)arg1 fromPaletteColor:(unsigned int)arg2 toPaletteColor:(unsigned int)arg3;
- (void)applyPaletteColor:(unsigned int)arg1;
- (id)chronoScene;
- (void)setUpdateBlock:(CDUnknownBlockType)arg1;
- (void)showChronoModeAnimated:(BOOL)arg1;
- (void)showTimeModeAnimated:(BOOL)arg1;
- (BOOL)startStop;
- (BOOL)lapReset;
- (void)applyTransitionFraction:(float)arg1 fromTimeScale:(unsigned int)arg2 toTimeScale:(unsigned int)arg3;
- (void)applyTimeScale:(unsigned int)arg1;
- (double)currentLapTime;
- (unsigned int)laps;
- (id)palette;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;

@end

