//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "NTKTimeView.h"

@class CADisplayLink, EAGLContext, NSDate, NSString, NTKMickeyRenderer, PUICClientSideAnimation;

@interface NTKCharacterTimeView : UIView <NTKTimeView>
{
    CADisplayLink *_displayLink;
    int _animationFrameInterval;
    PUICClientSideAnimation *_dateInterpolationAnimation;
    NSDate *_overrideDate;
    CDUnknownBlockType _cleanupOnAnimationStop;
    BOOL _stopAfterNextRender;
    BOOL _animating;
    NTKMickeyRenderer *_renderer;
    EAGLContext *_context;
}

+ (Class)layerClass;
@property(readonly, nonatomic) NTKMickeyRenderer *renderer; // @synthesize renderer=_renderer;
- (void)setOverrideDate:(id)arg1 duration:(double)arg2;
- (void)setZoomFraction:(float)arg1 diameter:(float)arg2;
- (void)drawView:(id)arg1;
- (void)_startAnimation;
- (void)cleanupAfterZoom;
- (void)prepareToZoom;
- (void)renderSynchronouslyWithImageQueueDiscard:(BOOL)arg1;
- (void)_stopAnimation;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=isAnimating) BOOL animating; // @synthesize animating=_animating;
- (void)setFrozen:(BOOL)arg1;
- (void)setTimeOffset:(double)arg1;
@property(retain, nonatomic) EAGLContext *context; // @synthesize context=_context;
@property(nonatomic) int animationFrameInterval; // @dynamic animationFrameInterval;
- (void)willMoveToWindow:(id)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

