//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoTimeKit/NTKUtilityCircularComplicationView.h>

#import "NTKBatteryComplicationDisplay.h"

@class NSString, NTKColoringImageView, NTKColoringLabel;

@interface NTKCircularBatteryUtilityComplicationView : NTKUtilityCircularComplicationView <NTKBatteryComplicationDisplay>
{
    NTKColoringLabel *_levelLabel;
    NTKColoringImageView *_stateRing;
    float _level;
    int _state;
}

- (void)_updateRingColor;
- (void)_applyForegroundAlpha;
- (id)_ringForLevel:(float)arg1;
- (void).cxx_destruct;
- (void)setLevel:(float)arg1;
- (void)setState:(int)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(nonatomic) unsigned int complicationType;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) __weak id <NTKComplicationDisplayObserver> displayObserver;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

