//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoTimeKit/NTKUtilityCircularComplicationView.h>

#import "NTKWellnessComplicationDisplay.h"

@class NSMutableArray, NSString, NTKRingsAndDotsView;

@interface NTKCircularWellnessUtilityComplicationView : NTKUtilityCircularComplicationView <NTKWellnessComplicationDisplay>
{
    NTKRingsAndDotsView *_ringsView;
    NSMutableArray *_ringsFillFractions;
    BOOL _animationsAllowed;
}

- (id)_ringColor;
- (void)_layoutContentView;
- (void)_applyForegroundAlpha;
- (void)setWellnessComplicationActiveHoursCurrent:(float)arg1 goal:(float)arg2;
- (void)setWellnessComplicationBriskMinutesCurrent:(float)arg1 goal:(float)arg2;
- (void)setWellnessComplicationCaloriesBurnedCurrent:(float)arg1 goal:(float)arg2;
- (void)setWellnessComplicationPredictedCaloriesPercentage:(float)arg1;
- (void)setWellnessComplicationPromptSetup;
- (void)setWellnessComplicationLoading;
- (void)setWellnessComplicationLocked;
- (void)_setLayoutEmptyRingsNoDot;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(nonatomic) unsigned int complicationType;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) __weak id <NTKComplicationDisplayObserver> displayObserver;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

