//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NPSManager;

@interface NTKCustomWorldCityAbbreviationsStore : NSObject
{
    NPSManager *_npsManager;
}

+ (id)sharedInstance;
- (void)setCustomAbbreviation:(id)arg1 forCityIdentifier:(id)arg2;
- (id)customAbbreviations;
- (id)_getCustomAbbreviationsFromPrefs;
- (void)_handlePrefsChanged;
- (void)_notifyClientsOfChange;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end

