//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

#import "NTKColoringView.h"

@class NSString, UIColor, _NTKColorManager;

@interface NTKColoringImageView : UIImageView <NTKColoringView>
{
    _NTKColorManager *_colorManager;
}

- (void)_updateImageColor;
- (void).cxx_destruct;
- (id)initWithImage:(id)arg1 highlightedImage:(id)arg2;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (void)_commonInit;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (id)initWithImage:(id)arg1;
- (void)setImage:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(retain, nonatomic) UIColor *color; // @dynamic color;
@property(nonatomic) BOOL colorIsAnimatable; // @dynamic colorIsAnimatable;
@property(readonly, nonatomic) UIColor *contentColor; // @dynamic contentColor;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

