//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSMutableDictionary, NSMutableSet, NSString, NTKComplication, NTKPolygonCylinderView, UIControl<NTKComplicationDisplay>;

@interface NTKComplicationPickerView : UIView
{
    NSArray *_rows;
    NSMutableSet *_loadedComplications;
    NSMutableDictionary *_viewsByComplication;
    NSMutableDictionary *_controllersByComplication;
    NSMutableDictionary *_layoutRulesByComplication;
    NTKPolygonCylinderView *_cylinderView;
    unsigned int _visibleRowBufferSize;
    BOOL _needsReload;
    BOOL _active;
    int _style;
    id <NTKComplicationPickerViewDataSource> _dataSource;
    NSString *_complicationSlot;
    unsigned int _numberOfSides;
    unsigned int _numberOfRows;
    unsigned int _selectedRowIndex;
    struct UIEdgeInsets _padding;
}

@property(nonatomic) unsigned int numberOfSides; // @synthesize numberOfSides=_numberOfSides;
@property(nonatomic) unsigned int selectedRowIndex; // @synthesize selectedRowIndex=_selectedRowIndex;
- (id)_selectedFaceView;
- (void)_loadComplication:(id)arg1;
- (id)_faceViewAtFaceIndex:(unsigned int)arg1;
- (struct CGRect)_frameForCylinderView;
- (void)_enumerateFaceViewsWithBlock:(CDUnknownBlockType)arg1;
- (void)incrementSelection;
- (void)decrementSelection;
- (void)_rotateAnimatedToSelectedRowFromRow:(unsigned int)arg1;
- (void)_rotateToSelectedRow;
- (void)_tileCylinderForRotationDirection:(int)arg1;
- (void)_invalidateComplicationControllers;
- (void)_loadRowsWithTypes:(unsigned int)arg1 selectedComplication:(id)arg2;
@property(retain, nonatomic) NSString *complicationSlot; // @synthesize complicationSlot=_complicationSlot;
- (void)stealSelectedComplicationView:(id *)arg1 controller:(id *)arg2;
@property(readonly, nonatomic) NTKComplication *selectedComplication;
- (id)initWithAllowedComplicationTypes:(unsigned int)arg1 selectedComplication:(id)arg2;
- (void)setSelectedRowIndex:(unsigned int)arg1 animated:(BOOL)arg2;
- (id)complicationAtIndex:(unsigned int)arg1;
- (void)setTransitionFraction:(float)arg1 fromIndex:(unsigned int)arg2 toIndex:(unsigned int)arg3;
@property(readonly, nonatomic) UIControl<NTKComplicationDisplay> *selectedComplicationView;
- (void)applyRubberBandingFraction:(float)arg1;
- (void)applyBreathingScale:(float)arg1;
- (void)reloadIfNeeded;
- (void)setNeedsReload;
- (void).cxx_destruct;
@property(nonatomic) BOOL active; // @synthesize active=_active;
@property(nonatomic) struct UIEdgeInsets padding; // @synthesize padding=_padding;
@property(readonly, nonatomic) unsigned int numberOfRows; // @synthesize numberOfRows=_numberOfRows;
@property(nonatomic) int style; // @synthesize style=_style;
@property(nonatomic) __weak id <NTKComplicationPickerViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (id)description;
- (void)layoutSubviews;
- (void)dealloc;

@end

