//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoTimeKit/NTKEditOption.h>

@interface NTKEnumeratedEditOption : NTKEditOption
{
    unsigned int _value;
}

+ (unsigned int)_numberOfValues;
+ (BOOL)_valueIsValid:(unsigned int)arg1;
+ (id)_keylineLabelTextLocalizationKeyForValue:(unsigned int)arg1;
+ (id)_nameForValue:(unsigned int)arg1;
+ (id)_optionWithValue:(unsigned int)arg1;
+ (unsigned int)indexOfOption:(id)arg1;
+ (id)optionAtIndex:(unsigned int)arg1;
+ (unsigned int)numberOfOptions;
+ (id)_orderedValues;
+ (BOOL)supportsSecureCoding;
- (id)localizedKeylineLabelText;
- (id)dailySnapshotKey;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (unsigned int)_value;

@end

