//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIImageView, UILabel;

@interface NTKFaceLibraryOverlayView : UIView
{
    UILabel *_leftTitleLabel;
    UILabel *_rightTitleLabel;
    float _leftTitleAlpha;
    float _rightTitleAlpha;
    float _leftTitleOffset;
    float _rightTitleOffset;
    BOOL _showingVerticalTitles;
    UILabel *_topTitleLabel;
    UILabel *_bottomTitleLabel;
    UIImageView *_titleGradientView;
    float _pageVOffset;
    UIButton *_editButton;
    UIButton *_cancelButton;
}

- (void)setRightTitle:(id)arg1;
- (void)setLeftTitle:(id)arg1;
@property(readonly, nonatomic) UIButton *editButton; // @synthesize editButton=_editButton;
@property(nonatomic) float pageVOffset; // @synthesize pageVOffset=_pageVOffset;
- (void)setRightTitleOffset:(float)arg1 alpha:(float)arg2;
- (void)setLeftTitleOffset:(float)arg1 alpha:(float)arg2;
- (void)setScrollFraction:(float)arg1 fromTopTitle:(id)arg2 toBottomTitle:(id)arg3;
- (void)showHorizontalTitlesWithDuration:(double)arg1;
- (void)showVerticalTitlesWithDuration:(double)arg1 startTitle:(id)arg2;
- (void)_adjustAnchorPoint;
- (id)_newTitleLabel;
- (void).cxx_destruct;
- (id)_newButton;
@property(readonly, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
- (void)layoutSubviews;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

