//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoTimeKit/NTKUtilityComplicationView.h>

#import "NTKWorldClockComplicationDisplay.h"

@class NSString, NTKColoringLabel, NTKDigitalTimeLabel;

@interface NTKLongWorldClockUtilityComplicationView : NTKUtilityComplicationView <NTKWorldClockComplicationDisplay>
{
    NTKDigitalTimeLabel *_timeLabel;
    NTKColoringLabel *_cityLabel;
}

- (void)_updateContentForMaxSizeChange;
- (float)_widthThatFits;
- (void)_applyForegroundAlpha;
- (void)setLongCity:(id)arg1;
- (void)setOverrideDate:(id)arg1;
- (void)_updateTime;
- (void).cxx_destruct;
- (void)setTimeZone:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(nonatomic) unsigned int complicationType;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) __weak id <NTKComplicationDisplayObserver> displayObserver;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

