//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoTimeKit/NTKUtilityLabelImageComplicationView.h>

#import "NTKStockComplicationDisplay.h"

@class NSString, UIView<NTKColoringView><NTKLabel>;

@interface NTKLongStockUtilityComplicationView : NTKUtilityLabelImageComplicationView <NTKStockComplicationDisplay>
{
    UIView<NTKColoringView><NTKLabel> *_priceLabel;
    UIView<NTKColoringView><NTKLabel> *_companionMetricLabel;
    UIView<NTKColoringView><NTKLabel> *_changeInPointsLabel;
    int _stockState;
    int _firstMetric;
    int _secondMetric;
    int _dropMetric;
}

- (id)_labelForMetricTag:(int)arg1;
- (void)_updateVisibleLabelsForState;
- (void)_updateStockDetailsLabel:(id)arg1 text:(id)arg2;
- (void)_subviewWasUpdated;
- (id)_metricLabelToKeep;
- (id)_secondMetricLabel;
- (id)_firstMetricLabel;
- (void)_layoutSubviewsForStockDataWithTwoMetricsInBounds:(struct CGRect)arg1;
- (void)_layoutSubviewsForStockDataWithOneMetricInBounds:(struct CGRect)arg1 width:(float)arg2;
- (id)_metricLabelToDrop;
- (float)_imageViewForegroundAlpha;
- (float)_widthThatFits;
- (void)_applyForegroundAlpha;
- (void)setStockComplicationCompanionMetricText:(id)arg1;
- (void)setStockComplicationChangeDirection:(unsigned int)arg1;
- (void)setStockComplicationChangeInPointsText:(id)arg1;
- (void)setStockComplicationPriceText:(id)arg1;
- (void)setStockComplicationTickerSymbolText:(id)arg1;
- (void)setStateNoStocks;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(nonatomic) unsigned int complicationType;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) __weak id <NTKComplicationDisplayObserver> displayObserver;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

