//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CAEAGLLayer, EAGLContext, NSCalendar, NSDate;

@interface NTKMickeyRenderer : NSObject
{
    EAGLContext *_context;
    unsigned int _defaultFBOName;
    unsigned int _colorRenderbuffer;
    int _viewWidth;
    int _viewHeight;
    int _allocatedWidth;
    int _allocatedHeight;
    union _GLKVector2 _neckBone;
    int _prevState;
    int _dstState;
    int _curState;
    int _prevPose;
    int _dstPose;
    int _curPose;
    float _curTimeMod1Sec;
    float _curTimeMod15Sec;
    float _hourHandPos;
    float _minHandPos;
    int _progRGBASimpleSpriteID;
    int _progAlphaSimpleSpriteID;
    int _progRGBABoneSpriteID;
    int _modelMatrixLoc;
    unsigned int _curProg;
    unsigned int _curVAO;
    struct MickeyHead _mickeyHead;
    struct MickeyBody _mickeyBody;
    struct MickeyFoot _mickeyFoot;
    struct MickeyArms _mickeyArms;
    struct Background _background;
    NSCalendar *_cal;
    NSDate *_overrideDate;
    NSDate *_overrideDateFrom;
    NSDate *_overrideDateTo;
    float _overrideDateFraction;
    float _fromHourPercent;
    float _fromMinutePercent;
    float _toHourPercent;
    float _toMinutePercent;
    float _zoomScaleMickey;
    float _zoomFraction;
    float _animationFrameInterval;
    CAEAGLLayer *_cachedLayer;
    BOOL _animatingIntoOrb;
    BOOL _applyInstantTimeWarp;
    BOOL _sayCheese;
}

- (id)initWithContext:(id)arg1 andDrawable:(id)arg2;
- (void)setupShaders;
- (void)setupFBOs:(id)arg1;
- (BOOL)resizeFromLayer:(id)arg1;
- (void)_drawMinuteHand;
- (void)_drawHead;
- (void)_drawHourHand;
- (void)_drawTappingFoot;
- (void)_drawBody;
- (void)_drawBackground;
- (void)_updateStateAndPose;
- (void)_updateTimeVariables;
- (void)_drawArmFromShoulder:(union _GLKVector3)arg1 toWrist:(union _GLKVector3)arg2 withBend:(float)arg3;
- (float)_getElbowScaleForPosition:(float)arg1;
- (void)_doneWaitingForFootRaise;
- (BOOL)_footIsRaisedEnoughToStartAnimation;
- (void)_idleBodyAfterAnimation;
- (void)_updateWaitingForFootRaise;
- (void)_bindGLVAO:(unsigned int)arg1;
- (void)_bindGLProgram:(unsigned int)arg1;
- (int)linkProgramWithVShad:(int)arg1 FShad:(int)arg2;
- (int)loadOneShaderOfType:(unsigned int)arg1 string:(const char *)arg2 bytes:(int)arg3;
- (BOOL)resizeFromCachedLayer;
- (void)setupTextures;
- (void)setupVAOs;
- (void)_lowerFootAfterBodyAnimation;
- (void)_raiseFootForBodyAnimation;
- (void)cleanupToOverrideDate:(id)arg1;
- (void)setOverrideDateFraction:(float)arg1;
- (void)prepareToOverrideDateFrom:(id)arg1 to:(id)arg2 curDate:(id)arg3;
- (void)significantTimeChanged:(id)arg1;
- (void)setZoomFraction:(float)arg1 diameter:(float)arg2;
- (void)cleanupAfterZoom;
- (void)prepareToZoom;
- (void).cxx_destruct;
- (void)setTimeOffset:(double)arg1;
- (void)setAnimationFrameInterval:(float)arg1;
- (void)dealloc;
- (void)render;

@end

