//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoTimeKit/NTKColoringView.h>

@class NSMutableArray;

@interface NTKRingsView : NTKColoringView
{
    struct CGPoint _ringsViewCenter;
    BOOL _showsRingsBackground;
    int _ringCount;
    float _ringWidth;
    float _ringGapWidth;
    NSMutableArray *_ringsFillFractions;
    float _appearanceAnimationProgress;
}

@property(nonatomic) int ringCount; // @synthesize ringCount=_ringCount;
- (void)_drawRingWithRadius:(float)arg1 fillFraction:(float)arg2 alpha:(float)arg3;
- (void)_drawFillFractionRings;
- (void)_drawBackgroundRings;
@property(nonatomic) float appearanceAnimationProgress; // @synthesize appearanceAnimationProgress=_appearanceAnimationProgress;
@property(nonatomic) BOOL showsRingsBackground; // @synthesize showsRingsBackground=_showsRingsBackground;
@property(nonatomic) float ringGapWidth; // @synthesize ringGapWidth=_ringGapWidth;
@property(nonatomic) float ringWidth; // @synthesize ringWidth=_ringWidth;
@property(retain, nonatomic) NSMutableArray *ringsFillFractions; // @synthesize ringsFillFractions=_ringsFillFractions;
- (float)radiusForRingAtIndex:(int)arg1;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

