//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoTimeKit/NTKUtilityLabelComplicationView.h>

#import "NTKDateComplicationDisplay.h"

@class NSString;

@interface NTKShortDateUtilityComplicationView : NTKUtilityLabelComplicationView <NTKDateComplicationDisplay>
{
}

- (void)setDateComplicationText:(id)arg1 forDateStyle:(unsigned int)arg2;
- (unsigned int)supportedDateComplicationDateStyles;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(nonatomic) unsigned int complicationType;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) __weak id <NTKComplicationDisplayObserver> displayObserver;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

