//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NTKSolarTimeModel, UIBezierPath;

@interface NTKSolarPath : NSObject
{
    UIBezierPath *_bezierPath;
    struct CGRect _bounds;
    NTKSolarTimeModel *_solarTimeModel;
    float _minimumPercentageOfDayDone;
    float _maximumPercentageOfDayDone;
    BOOL _verticallyFitsPathToBounds;
    BOOL _usePlaceholderData;
}

@property(readonly, nonatomic) BOOL verticallyFitsPathToBounds; // @synthesize verticallyFitsPathToBounds=_verticallyFitsPathToBounds;
@property(readonly, nonatomic) NTKSolarTimeModel *solarTimeModel; // @synthesize solarTimeModel=_solarTimeModel;
- (id)_computeSolarPath;
- (id)initWithBounds:(struct CGRect)arg1 solarTimeModel:(id)arg2 verticallyFitsPathToBounds:(BOOL)arg3 usePlaceholderData:(BOOL)arg4;
- (void).cxx_destruct;
@property(readonly, nonatomic) UIBezierPath *bezierPath; // @synthesize bezierPath=_bezierPath;
@property(readonly, nonatomic) struct CGRect bounds; // @synthesize bounds=_bounds;

@end

