//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoTimeKit/NTKComplicationModuleView.h>

#import "NTKStockComplicationDisplay.h"

@class NSString, NTKColoringImageView, NTKColoringLabel, PUICDynamicTextSizingParams;

@interface NTKStockSmallModuleView : NTKComplicationModuleView <NTKStockComplicationDisplay>
{
    NTKColoringImageView *_iconView;
    NTKColoringLabel *_tickerSymbolLabel;
    NTKColoringLabel *_stockMetricLabel;
    PUICDynamicTextSizingParams *_tickerLabelSizingParams;
    PUICDynamicTextSizingParams *_stockMetricLabelSizingParams;
    BOOL _tickerLabelNeedsDynamicSizing;
    BOOL _stockMetricLabelNeedsDynamicSizing;
}

- (void)setStockComplicationCompanionMetricText:(id)arg1;
- (void)setStockComplicationTickerSymbolText:(id)arg1;
- (void)setStateNoStocks;
- (void)setAnimatesForegroundColors:(BOOL)arg1;
- (void)setSecondaryForegroundColor:(id)arg1;
- (void)layoutContentView;
- (void).cxx_destruct;
- (void)setForegroundColor:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(nonatomic) unsigned int complicationType;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) __weak id <NTKComplicationDisplayObserver> displayObserver;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

