//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoTimeKit/NTKComplicationController.h>

@class NSNumber;

@interface NTKStopwatchComplicationController : NTKComplicationController
{
    struct NSNumber *_stopwatchToken;
}

@property(nonatomic) __weak id <NTKStopwatchComplicationDisplay> display;
- (void)_startStopwatchTimerUpdates;
- (void)_stopStopwatchTimerUpdates;
@property(retain, nonatomic) NSNumber *stopwatchToken; // @synthesize stopwatchToken=_stopwatchToken;
- (void)_handleTimeFormatChange;
- (void)_handleReloadNotification;
- (void)_handleLocaleChange;
- (void)setDataMode:(int)arg1;
- (id)complicationApplicationIdentifier;
- (void)performTapAction;
- (BOOL)hasTapAction;
- (id)initWithComplication:(id)arg1;
- (void).cxx_destruct;
- (void)invalidate;
- (void)_updateDisplay;

@end

