//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CLLocation, NSDate;

@interface NTKSolarTimeModel : NSObject
{
    BOOL _usePlaceholderData;
    BOOL _dependentValuesNeedUpdate;
    CLLocation *_referenceLocation;
    NSDate *_startDateForReferenceDate;
    NSDate *_endDateForReferenceDate;
    NSDate *_localSolarMidnightDate;
    NSDate *_referenceDate;
    double _midnightOffset;
    double _effectiveSolarDayLength;
}

@property(nonatomic) BOOL dependentValuesNeedUpdate; // @synthesize dependentValuesNeedUpdate=_dependentValuesNeedUpdate;
@property(nonatomic) BOOL usePlaceholderData; // @synthesize usePlaceholderData=_usePlaceholderData;
@property(nonatomic) double effectiveSolarDayLength; // @synthesize effectiveSolarDayLength=_effectiveSolarDayLength;
@property(retain, nonatomic) NSDate *localSolarMidnightDate; // @synthesize localSolarMidnightDate=_localSolarMidnightDate;
@property(nonatomic) double midnightOffset; // @synthesize midnightOffset=_midnightOffset;
- (void)updateForTimeZoneChange;
- (void)updateModelWithDate:(id)arg1;
- (id)dateForPercentageThroughPeriod:(float)arg1;
- (float)percentageThroughPeriodForIdealizedTimeInCurrentSolarDay;
- (BOOL)includesDate:(id)arg1;
@property(retain, nonatomic) NSDate *endDateForReferenceDate; // @synthesize endDateForReferenceDate=_endDateForReferenceDate;
@property(retain, nonatomic) NSDate *startDateForReferenceDate; // @synthesize startDateForReferenceDate=_startDateForReferenceDate;
- (float)percentageThroughPeriodForDate:(id)arg1;
- (float)percentageThroughPeriodInCurrentSolarDayForDate:(id)arg1;
- (void)_updateDependentValues;
- (id)initWithReferenceDate:(id)arg1 referenceLocation:(id)arg2;
@property(retain, nonatomic) CLLocation *referenceLocation; // @synthesize referenceLocation=_referenceLocation;
- (void).cxx_destruct;
- (id)init;
@property(retain, nonatomic) NSDate *referenceDate; // @synthesize referenceDate=_referenceDate;

@end

