//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoTimeKit/NTKColorComplicationView.h>

#import "NTKSunriseComplicationDisplay.h"

@class NSDate, NSString, NTKColoringImageView, NTKColoringLabel, NTKDigitalTimeLabel;

@interface NTKSunriseColorComplicationView : NTKColorComplicationView <NTKSunriseComplicationDisplay>
{
    NTKDigitalTimeLabel *_timeLabel;
    NTKColoringImageView *_imageView;
    NTKColoringLabel *_noInfoLabel;
    BOOL _noInfo;
    BOOL _showingSunrise;
    NSDate *_sunriseDate;
    NSDate *_sunsetDate;
    int _constantSun;
}

- (void)setShowingSunrise:(BOOL)arg1;
- (BOOL)transitionsAtAstronomicalTwilight;
- (void)setSunriseDate:(id)arg1 sunsetDate:(id)arg2 constantSun:(int)arg3;
- (void)_updateContent;
- (void)setAnimatesForegroundColors:(BOOL)arg1;
- (void).cxx_destruct;
- (void)setForegroundColor:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(nonatomic) unsigned int complicationType;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) __weak id <NTKComplicationDisplayObserver> displayObserver;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

