//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoTimeKit/NTKDigitalFaceView.h>

#import "NTKTimeView.h"
#import "PUICCrownInputSequencerDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class NSDateComponentsFormatter, NSDictionary, NSMutableSet, NSString, NSTimer, NTKBezierPathView, NTKColorCurve, NTKComplicationController, NTKDateComplicationLabel, NTKDelayedBlock, NTKDigitalTimeLabel, NTKDigitalTimeLabelStyle, NTKLayoutRule, NTKSolarDiskView, NTKSolarSupplementalView, NTKSolarTimeModel, PUICClientSideAnimation, PUICCrownInputSequencer, UIImageView, UILabel, UITapGestureRecognizer, UIView;

@interface NTKSolarFaceView : NTKDigitalFaceView <NTKTimeView, PUICCrownInputSequencerDelegate, UIGestureRecognizerDelegate>
{
    NTKDigitalTimeLabel *_timeLabel;
    NTKDigitalTimeLabelStyle *_timeLabelDefaultStyle;
    NTKDigitalTimeLabelStyle *_timeLabelSmallInUpperRightCornerStyle;
    UIView *_solarPathObjectContainerView;
    NTKBezierPathView *_solarBezierPathView;
    NTKSolarDiskView *_solarDiskView;
    UIView *_solarDiskHaloParentView;
    UIImageView *_solarDiskHaloView;
    UIView *_solarDiskHaloMaskView;
    NTKColorCurve *_solarDiskColorCurve;
    PUICClientSideAnimation *_solarDiskAnimation;
    float _solarDiskOverridePercentage;
    UILabel *_waypointLabel;
    NSDictionary *_waypoints;
    NSDictionary *_waypointViews;
    UIView *_horizonView;
    UIImageView *_horizonGradientView;
    UIView *_horizonGradientContainerView;
    NTKColorCurve *_horizonGradientColorCurve;
    UIView *_belowHorizonView;
    NTKSolarTimeModel *_solarTimeModel;
    BOOL _solarPathNeedsUpdate;
    float _currentSolarDiskPercentage;
    UITapGestureRecognizer *_viewModeTapGesture;
    int _previousViewMode;
    struct NSNumber *_clockTimerToken;
    struct NSNumber *_locationManagerToken;
    NTKComplicationController *_dateComplicationController;
    NTKDateComplicationLabel *_dateComplicationLabel;
    NTKLayoutRule *_dateComplicationLayoutRule;
    BOOL _canHandleHardwareEvents;
    PUICCrownInputSequencer *_crownSequencer;
    NTKDigitalTimeLabel *_timeScrubLabel;
    NTKDigitalTimeLabelStyle *_timeScrubLabelStyle;
    UILabel *_timeScrubNowLabel;
    UILabel *_timeDifferenceScrubLabel;
    NTKLayoutRule *_timeDifferenceScrubLabelLayoutRule;
    NTKDelayedBlock *_timeDifferenceScrubLabelFadeInBlock;
    NSDateComponentsFormatter *_fullStyleIntervalDateFormatter;
    NSDateComponentsFormatter *_shortStyleIntervalDateFormatter;
    BOOL _useLocationAwareInteractiveMode;
    CDUnknownBlockType _waypointSettleAnimationBlock;
    NTKSolarSupplementalView *_supplementalSunriseView;
    NTKSolarSupplementalView *_supplementalSunsetView;
    NTKLayoutRule *_supplementalSunsetViewLayoutRule;
    NTKLayoutRule *_supplementalSunriseViewLayoutRule;
    UIView *_wristRaiseBackgroundView;
    UIView *_wristRaiseSunView;
    UIView *_wristRaiseSunMaskView;
    UIView *_zoomMaskView;
    struct CGPoint _timeLabelZoomEndingCenter;
    struct CGPoint _dateLabelZoomEndingCenter;
    struct CGPoint _solarDiskViewZoomEndingCenter;
    UIView *_borrowedTimeViewFromClockIcon;
    UIView *_borrowedCircleViewFromClockIcon;
    NSMutableSet *_animatingReasons;
    BOOL _contentViewsLoaded;
    NSTimer *_wheelDelayTimer;
    NSTimer *_buttonPressTimer;
}

- (void)crownInputSequencerIdleDidChange:(id)arg1;
- (void)crownInputSequencerOffsetDidChange:(id)arg1;
- (BOOL)_isAnimatingForReason:(id)arg1;
- (void)_adjustUIForBoundsChange;
- (void)_cleanupAfterSettingViewMode:(int)arg1;
- (id)_timeLabelStyleForViewMode:(int)arg1;
- (void)_prepareForSettingViewMode:(int)arg1;
- (id)_createWaypointView;
- (void)_animateSolarDiskToRestPercentageIfNeeded;
- (void)_endAnimatingForReason:(id)arg1;
- (void)_beginAnimatingForReason:(id)arg1;
- (void)_updateSolarDiskHaloViewPosition;
- (void)_updateSolarHorizonGradientAlphaWithSolarDiskCenter:(struct CGPoint)arg1;
- (struct CGPoint)_pointOnSolarPathForPercentage:(float)arg1;
- (id)_waypointLabelTextForPercentage:(float)arg1;
- (void)_updateColorCurves;
- (void)_makeLocationAwareInteractiveModeUIVisible:(BOOL)arg1 animated:(BOOL)arg2;
- (void)_updateSolarPathForChangedLocation:(id)arg1;
- (BOOL)_solarPathRequiresUpdateForChangedLocation:(id)arg1;
- (id)_createDateComponentsFormatterWithUnitsStyle:(int)arg1;
- (void)_enableCrown;
- (void)_disableCrown;
- (void)_animateSolarDiskFromPercentage:(float)arg1 toPercentage:(float)arg2 reason:(id)arg3;
- (void)_startClockUpdates;
- (void)_updateSolarPathForChangedDate:(id)arg1;
- (id)_formatDateStringForIntervalBetweenReferenceDate:(id)arg1 andOverrideDate:(id)arg2;
- (void)setOverrideDate:(id)arg1 duration:(double)arg2;
- (void)_fadeOutTimeDifferenceScrubLabelIfNeeded;
- (float)_percentageForWaypoint:(int)arg1;
- (int)_waypointForPercentage:(float)arg1 withSmallThreshold:(float)arg2 largeThreshold:(float)arg3;
- (void)_fadeInTimeDifferenceScrubLabelIfNeeded;
- (void)_buttonPressTimerFired;
- (void)_wheelDelayTimerFired;
- (BOOL)_canEnterInteractiveMode;
- (void)_solarDiskPercentageChanged:(float)arg1;
- (float)_solarDiskIdealizedDatePercentage;
- (void)_updateWaypointLabelForCrownMovement;
- (void)_layoutSupplementalViewsForViewMode:(int)arg1;
- (void)_layoutSolarDiskViewForViewMode:(int)arg1;
- (void)_layoutSolarPathAndContainerForViewMode:(int)arg1;
- (void)_layoutHorizonForViewMode:(int)arg1;
- (void)_layoutCrownLabelsForViewMode:(int)arg1;
- (void)_layoutDateComplicationForViewMode:(int)arg1;
- (void)_setSolarBezierPath:(id)arg1 animated:(BOOL)arg2;
- (id)_createSolarBezierPath;
- (void)_setViewMode:(int)arg1 animated:(BOOL)arg2;
- (void)_updateSolarHorizonGradientColorWithPercentage:(float)arg1;
- (void)_updateSolarHorizonGradientAlphaWithPercentage:(float)arg1;
- (void)_updateSolarHaloWithPercentage:(float)arg1;
- (float)_solarDiskRestPercentage;
- (id)_solarPathObjectFillColor;
- (void)_layoutTimeLabelForViewMode:(int)arg1;
- (void)_stopClockUpdates;
- (void)_sharedLocationManagerUpdatedLocation:(id)arg1 error:(id)arg2;
- (void)_updateWaypoints;
- (void)_handleViewModeTapGesture:(id)arg1;
- (void)setViewMode:(int)arg1;
- (BOOL)_handlePhysicalButton:(unsigned int)arg1 event:(unsigned int)arg2;
- (BOOL)_usesCustomZoom;
- (void)_performWristRaiseAnimation;
- (void)_prepareWristRaiseAnimation;
- (void)_applyDataMode;
- (void)_unloadSnapshotContentViews;
- (void)_loadSnapshotContentViews;
- (void)_loadLayoutRules;
- (void)_cleanupAfterZoom;
- (void)_setZoomFraction:(float)arg1 iconDiameter:(float)arg2;
- (void)_prepareToZoomWithIconView:(id)arg1 minDiameter:(float)arg2 maxDiameter:(float)arg3;
- (id)_labelFont;
- (void).cxx_destruct;
- (BOOL)_isAnimating;
- (void)setTimeOffset:(double)arg1;
- (BOOL)_wheelChangedWithEvent:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_timeZoneChanged:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

