//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLSBacklightObserver.h"

@class NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface NTKTaskScheduler : NSObject <CSLSBacklightObserver>
{
    NSMutableArray *_queuedTokens;
    NSMutableDictionary *_tasksByToken;
    unsigned int _nextToken;
    int _backlightStatus;
    NSObject<OS_dispatch_queue> *_backlightStatusQueue;
    BOOL _backlightIsOrWillBeOnAccordingToCSLPI;
    NSString *_taskSchedulerIdentifier;
}

- (void)_synchronouslyPerformImportantScheduledTasks;
- (void)cancelTaskForToken:(struct NSNumber *)arg1;
- (CDUnknownBlockType)_dequeueTask;
- (void)_takePowerAssertion;
- (void)_tryToPerformNextTask;
- (void)_synchronouslyPerformScheduledTasks:(BOOL)arg1;
- (struct NSNumber *)_scheduleImportant:(BOOL)arg1 task:(CDUnknownBlockType)arg2;
- (void)_releasePowerAssertion;
- (void)_handleCSLPIBacklightDidTurnOff;
- (void)_handleCSLPIBacklightWillTurnOn;
- (void)synchronouslyPerformAllScheduledTasks;
- (void)backlightDidChange:(id)arg1 from:(int)arg2 to:(int)arg3;
- (id)scheduleDataSensitiveTask:(CDUnknownBlockType)arg1;
- (struct NSNumber *)scheduleTask:(CDUnknownBlockType)arg1;
- (void)cancelAllTasks;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

