//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoTimeKit/NTKEnumeratedEditOption.h>

@interface NTKTimeScaleEditOption : NTKEnumeratedEditOption
{
}

+ (id)optionWithTimeScale:(unsigned int)arg1;
+ (id)_keylineLabelTextLocalizationKeyForValue:(unsigned int)arg1;
+ (id)_nameForValue:(unsigned int)arg1;
+ (id)_orderedValues;
@property(readonly, nonatomic) unsigned int timeScale;

@end

