//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoTimeKit/NTKAnalogFaceView.h>

#import "NTKUtilityComplicationFactoryDelegate.h"

@class NSString, NTKUtilitarianScene, NTKUtilityComplicationFactory, _UtilitarianTimeView;

@interface NTKUtilitarianFaceView : NTKAnalogFaceView <NTKUtilityComplicationFactoryDelegate>
{
    NTKUtilityComplicationFactory *_complicationFactory;
    NTKUtilitarianScene *_utilitarianScene;
}

- (unsigned int)_keylineLabelAlignmentForColorEditing;
- (BOOL)_fadesComplicationSlot:(id)arg1 inEditMode:(int)arg2;
- (unsigned int)_keylineLabelAlignmentForCustomEditMode:(int)arg1;
- (struct CGRect)_keylineFrameForCustomEditMode:(int)arg1;
- (id)_keylineViewForCustomEditMode:(int)arg1;
- (void)_applyTransitionFraction:(float)arg1 fromOption:(id)arg2 toOption:(id)arg3 forCustomEditMode:(int)arg4;
- (void)_applyOption:(id)arg1 forCustomEditMode:(int)arg2;
- (void)_unloadOpaqueComplicationDisplayForSlot:(id)arg1;
- (id)_loadOpaqueComplicationDisplayOfType:(unsigned int)arg1 forSlot:(id)arg2;
- (id)_opaqueComplicationSlots;
- (id)utilityComplicationFactoryDateComplicationFontForStyle:(unsigned int)arg1;
- (unsigned int)utilityComplicationFactoryDateStyleForComplicationType:(unsigned int)arg1;
- (struct CGRect)_keylineFrameForColorEditing;
- (id)_keylineViewForColorEditing;
- (id)_dateComplicationFontForStyle:(unsigned int)arg1;
- (float)_verticalPaddingForStatusBar;
- (void)_unloadSnapshotContentViews;
- (void)_loadSnapshotContentViews;
- (void)_configureForTransitionFraction:(float)arg1 fromEditMode:(int)arg2 toEditMode:(int)arg3;
- (void)_configureForEditMode:(int)arg1;
- (float)_keylineCornerRadiusForComplicationSlot:(id)arg1;
- (unsigned int)_keylineLabelAlignmentForComplicationSlot:(id)arg1;
- (id)_newComplicationViewOfType:(unsigned int)arg1 forSlot:(id)arg2;
- (void)_loadLayoutRules;
- (void)_applyForegroundAlphaForTransitionFraction:(float)arg1 fromEditMode:(int)arg2 toEditMode:(int)arg3;
- (unsigned int)_keylineLabelAlignmentForDensityEditing;
- (struct CGRect)_keylineFrameForDensityEditing;
- (id)_keylineViewForDensityEditing;
- (unsigned int)_dateComplicationStyleForType:(unsigned int)arg1;
- (id)_utilityComplicationSlots;
- (Class)_utilitarianSceneClass;
- (void)_configureComplicationFactory:(id)arg1;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) _UtilitarianTimeView *timeView;

@end

