//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NTKUniverseAnimatable.h"

@class NSArray, NSDate, NSMutableArray, NSString, NTKUniverseSpheroid;

@interface NTKUniverseScene : NSObject <NTKUniverseAnimatable>
{
    float _orbit;
    int _minFrameInterval;
    NSMutableArray *_spheroids;
    NTKUniverseSpheroid *_focus;
    // Error parsing type: , name: _position
    // Error parsing type: , name: _target
    // Error parsing type: , name: _up
    unsigned int _snap;
    unsigned int _backgroundType;
    unsigned int _projectionType;
    NSMutableArray *_animations;
    NSDate *_date;
    unsigned int _isUpdateNeeded:1;
    unsigned int _isUpdatable:1;
}

@property(nonatomic) int minFrameInterval; // @synthesize minFrameInterval=_minFrameInterval;
@property(nonatomic) BOOL updatable; // @synthesize updatable=_isUpdatable;
- (void)updateSunLocation;
@property(nonatomic) unsigned int snap; // @dynamic snap;
- (void)_removeAllAnimationsFor:(id)arg1 withKeys:(unsigned int)arg2;
- (void)setAnimatedFloat:(unsigned int)arg1 forKey: /* Error: Ran out of types for this method. */;
-     // Error parsing type: 12@0:4I8, name: animatedFloatForKey:
- (void)setCamera:target:up: /* Error: Ran out of types for this method. */;
- (BOOL)isAnimating:(id)arg1;
@property(nonatomic) float orbit; // @synthesize orbit=_orbit;
@property(nonatomic) unsigned int projectionType; // @synthesize projectionType=_projectionType;
@property(readonly, nonatomic) int acceptableFrameInterval;
- (void)updateFromDateIfNeeded;
@property(readonly, nonatomic) NSArray *spheroids; // @synthesize spheroids=_spheroids;
// Error parsing type for property up:
// Property attributes: T,R,N,V_up

- (void)updateSunLocationForDate:(id)arg1 animated:(BOOL)arg2;
- (id)spheroidOfType:(unsigned int)arg1;
- (id)initWithSphereoids:(unsigned int)arg1;
@property(retain, nonatomic) NTKUniverseSpheroid *focus; // @synthesize focus=_focus;
- (void)removeAnimation:(id)arg1;
- (void)addAnimation:(id)arg1;
- (void).cxx_destruct;
- (void)update:(float)arg1;
@property(retain, nonatomic) NSDate *date; // @dynamic date;
// Error parsing type for property position:
// Property attributes: T,R,N,V_position

// Error parsing type for property target:
// Property attributes: T,R,N,V_target

@property(nonatomic) unsigned int backgroundType; // @synthesize backgroundType=_backgroundType;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

