//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol NTKUniverseRotatable <NSObject>
@property(nonatomic) CDStruct_2c43369c centerCoordinate;
@property(nonatomic) CDStruct_2c43369c homeCoordinate;
- (void)setCenterCoordinate:(CDStruct_2c43369c)arg1 animated:(BOOL)arg2;
@end

