//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

#import "NTKComplicationDisplay.h"

@class NSString, UIView;

@interface NTKUtilityComplicationView : UIControl <NTKComplicationDisplay>
{
    BOOL _editing;
    unsigned int complicationType;
    id <NTKComplicationDisplayObserver> displayObserver;
    float _foregroundAlpha;
    unsigned int _placement;
    float _minimumWidth;
    UIView *_highlightView;
    struct CGSize _maxSize;
    struct UIEdgeInsets _touchEdgeInsets;
}

+ (id)largeComplicationViewForType:(unsigned int)arg1;
+ (id)smallComplicationViewForType:(unsigned int)arg1;
- (id)_newImageViewSubview;
- (id)_newStandardMonospacedLabelSubview;
- (id)_newStandardLabelSubview;
- (id)_newDigitalTimeLabelSubviewWithOptions:(unsigned int)arg1;
- (void)layoutLabelVertically:(id)arg1;
- (id)_newImageViewSubviewWithAlpha:(float)arg1;
- (id)_standardMonospacedFont;
- (id)_standardFont;
- (void)_updateContentForEditingChange;
- (void)_updateContentForMaxSizeChange;
- (float)_widthThatFits;
- (struct UIEdgeInsets)_touchEdgeInsetsForPlacement:(unsigned int)arg1;
- (void)_applyForegroundAlpha;
@property(nonatomic) struct UIEdgeInsets touchEdgeInsets; // @synthesize touchEdgeInsets=_touchEdgeInsets;
- (id)_smallCapsFont;
- (id)_newLabelSubviewWithFont:(id)arg1;
- (BOOL)shouldCancelTouchesInScrollview;
@property(nonatomic) __weak id <NTKComplicationDisplayObserver> displayObserver; // @synthesize displayObserver;
@property(nonatomic) unsigned int complicationType; // @synthesize complicationType;
- (void)updateForEditing:(BOOL)arg1;
- (void)updateForMaxSize:(struct CGSize)arg1;
@property(nonatomic) float foregroundAlpha; // @synthesize foregroundAlpha=_foregroundAlpha;
- (void).cxx_destruct;
@property(nonatomic) unsigned int placement; // @synthesize placement=_placement;
@property(retain, nonatomic) UIView *highlightView; // @synthesize highlightView=_highlightView;
@property(readonly, nonatomic) BOOL editing; // @synthesize editing=_editing;
@property(nonatomic) float minimumWidth; // @synthesize minimumWidth=_minimumWidth;
- (void)setHighlighted:(BOOL)arg1;
@property(readonly, nonatomic) struct CGSize maxSize; // @synthesize maxSize=_maxSize;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

