//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoTimeKit/NTKUtilityComplicationView.h>

@class NTKColoringLabel, UIFont;

@interface NTKUtilityDateComplicationView : NTKUtilityComplicationView
{
    NTKColoringLabel *_label;
    unsigned int _dateStyle;
}

- (id)initWithDateStyle:(unsigned int)arg1;
- (void)_invalidateLabelSize;
- (float)_widthThatFits;
- (void)setDateComplicationText:(id)arg1 forDateStyle:(unsigned int)arg2;
- (unsigned int)supportedDateComplicationDateStyles;
- (void).cxx_destruct;
@property(retain, nonatomic) UIFont *font;
- (void)layoutSubviews;

@end

