//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NTKComplicationDisplay.h"

@protocol NTKWellnessComplicationDisplay <NTKComplicationDisplay>
- (void)setWellnessComplicationPromptSetup;
- (void)setWellnessComplicationLoading;
- (void)setWellnessComplicationLocked;

@optional
- (void)setWellnessComplicationActiveHoursCurrent:(float)arg1 goal:(float)arg2;
- (void)setWellnessComplicationBriskMinutesCurrent:(float)arg1 goal:(float)arg2;
- (void)setWellnessComplicationCaloriesBurnedCurrent:(float)arg1 goal:(float)arg2;
- (void)setWellnessComplicationPredictedCaloriesPercentage:(float)arg1;
@end

