//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoTimeKit/NTKComplicationController.h>

#import "NTKWellnessDataSubscriber.h"

@class NSString;

@interface NTKWellnessComplicationController : NTKComplicationController <NTKWellnessDataSubscriber>
{
    struct {
        unsigned int wantsCaloriesBurnedCurrentAndGoal:1;
        unsigned int wantsPredictedCaloriesPercentage:1;
        unsigned int wantsBriskMinutesCurrentAndGoal:1;
        unsigned int wantsActiveHoursCurrentAndGoal:1;
    } _displayFlags;
    int _notifyToken;
    BOOL _deviceLocked;
    BOOL _showingMetaState;
    struct NSNumber *_dataBrokerSubscription;
}

@property(nonatomic) __weak id <NTKWellnessComplicationDisplay> display;
- (void)_updateActiveHoursViewsWithCurrent:(float)arg1 goal:(float)arg2;
- (void)_updateBriskMinutesViewsWithCurrent:(float)arg1 goal:(float)arg2;
- (void)_updateCaloriesViewsWithCurrent:(float)arg1 goal:(float)arg2;
- (void)_updateWellnessDatabaseLoading:(BOOL)arg1 userHasDoneActivitySetup:(BOOL)arg2;
- (void)_synchronousQueryWellnessData;
- (void)_startWellnessDataHandling;
- (void)_stopWellnessDataHandling;
- (void)_handleDeviceLockChange;
- (void)handleWellnessDataActiveHoursWithCurrent:(float)arg1 goal:(float)arg2;
- (void)handleWellnessDataBriskMinutesWithCurrent:(float)arg1 goal:(float)arg2;
- (void)handleWellnessDataCaloriesWithCurrent:(float)arg1 goal:(float)arg2;
- (void)handleWellnessDatabaseLoading:(BOOL)arg1 userHasDoneActivitySetup:(BOOL)arg2;
- (void)handleWellnessDataCache:(id)arg1;
- (void)setLockScreenBorrowed:(BOOL)arg1;
- (id)complicationApplicationIdentifier;
- (void)performTapAction;
- (BOOL)hasTapAction;
- (void).cxx_destruct;
- (void)invalidate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

