//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PUICPageScrollViewController, UIViewController;

@protocol PUICPageScrollViewControllerDataSource <NSObject>
- (UIViewController *)pageScrollViewController:(PUICPageScrollViewController *)arg1 viewControllerForPageAtIndex:(unsigned int)arg2;
- (unsigned int)pageScrollViewControllerNumberOfPages:(PUICPageScrollViewController *)arg1;

@optional
- (void)pageScrollViewController:(PUICPageScrollViewController *)arg1 didPurgePageViewController:(UIViewController *)arg2;
@end

