//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@interface CALayer (PUICSpring)
- (void)puic_animateKeyPath:(id)arg1 fromValue:(id)arg2 toValue:(id)arg3 usingSpringWithStiffness:(double)arg4 initialVelocity:(double)arg5 completion:(CDUnknownBlockType)arg6;
- (void)puic_animateScaleUsingSpringWithStiffness:(double)arg1 initialVelocity:(double)arg2 completion:(CDUnknownBlockType)arg3;
- (void)puic_animateXPositionUsingSpringWithStiffness:(double)arg1 initialVelocity:(double)arg2 completion:(CDUnknownBlockType)arg3;
@end

