//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class UIColor;

@interface PUICTableViewCellBackgroundView : UIImageView
{
    unsigned long long _roundedCorners;
    UIColor *_color;
}

+ (id)_imageCache;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
@property(nonatomic) unsigned long long roundedCorners; // @synthesize roundedCorners=_roundedCorners;
- (void).cxx_destruct;
- (id)_contentMaskLayer;
- (void)setOpaqueWithUpdate:(_Bool)arg1;
- (void)setPillOpaque:(_Bool)arg1;
- (void)viewWillMoveToSuperview:(id)arg1;
- (void)_updateColor;
- (void)_updateImage;
- (id)initWithFrame:(struct CGRect)arg1;

@end

