//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PUICApplication.h"

@class NSDictionary, NSString;

@interface SPApplication : PUICApplication
{
    NSString *_pptTestName;
    NSString *_pptSubTestName;
    NSDictionary *_pptTestOptions;
    _Bool _isDistributionTest;
    int _distributionTestIndex;
}

+ (id)sharedSPApplication;
+ (void)initialize;
- (void).cxx_destruct;
- (_Bool)runTest:(id)arg1 options:(id)arg2;
- (void)pptFinishSubTest;
- (void)pptStartSubTest;
- (void)pptFinishTestWithExtraResults:(id)arg1;
- (void)pptStartTestWithOptions:(id)arg1;
- (void)pptFinishDistributionTest;
- (void)pptStartDistributionTest;
- (int)pptGetNextSize;
- (id)_statusBarControllingWindow;
- (_Bool)_fakingRequiresHighResolution;
- (void)_createStatusBarWithRequestedStyle:(long long)arg1 orientation:(long long)arg2 hidden:(_Bool)arg3;
- (void)applicationWillSuspend;
- (void)finishedExtendedLaunchTest;
- (id)_extendLaunchTest;

@end

