//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol SPInterfaceDelegate <NSObject>
- (void)notifyDetentsChanged;
- (void)setValue:(id)arg1 forKey:(NSString *)arg2;
- (void)performAction:(NSString *)arg1 withValue:(id)arg2;
@end

