//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SPUtils : NSObject
{
}

+ (unsigned long long)folderSizeAtPath:(id)arg1 volumeBlockSize:(unsigned long long)arg2;
+ (unsigned long long)userVolumeBlockSize;
+ (id)deserializeObject:(id)arg1;
+ (id)serializeObject:(id)arg1;
+ (id)uniqueNumber;

@end

