//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HKAchievement, NSArray, NSDate;

@protocol HKExtendedServerInterface <NSObject>
- (void)resetNanoSyncWithCompletion:(void (^)(BOOL, NSError *))arg1;
- (void)forceNanoSyncWithPullRequest:(BOOL)arg1 completion:(void (^)(BOOL, NSError *))arg2;
- (void)addAchievement:(HKAchievement *)arg1 completion:(void (^)(BOOL, NSError *))arg2;
- (void)markAchievementAsViewed:(HKAchievement *)arg1 completion:(void (^)(HKAchievement *, NSError *))arg2;
- (void)fetchNumberOfUnviewedAchievementsWithCompletion:(void (^)(int, NSError *))arg1;
- (void)markAchievementsAlerted:(NSArray *)arg1 completion:(void (^)(BOOL, NSError *))arg2;
- (void)fetchUnalertedAchievementsWithCompletion:(void (^)(NSArray *, NSError *))arg1;
- (void)fetchAchievementsWithCompletedDateBetweenStart:(NSDate *)arg1 end:(NSDate *)arg2 completion:(void (^)(NSArray *, NSError *))arg3;
- (void)registerForAchievementNotificationsAndFetchUnalertedCountWithCompletion:(void (^)(int, NSError *))arg1;
@end

