//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NLActivityBulletinContentLocalizer : NSObject
{
}

+ (id)localizedDescriptionForGoalsCompleted:(id)arg1 singleGoalExceeded:(BOOL)arg2 date:(id)arg3 firstName:(id)arg4;
+ (id)localizedDescriptionForIncompleteGoalType:(unsigned int)arg1 percentComplete:(double)arg2 value:(double)arg3 date:(id)arg4 firstName:(id)arg5;
+ (id)localizedTitleForGoalsCompleted:(id)arg1;
+ (id)localizedTitleForIncompleteGoalType:(unsigned int)arg1 percentComplete:(double)arg2 date:(id)arg3;
+ (id)_keyForGoalTypes:(id)arg1;
+ (id)_localizePercent:(double)arg1;
+ (id)_localizeCount:(double)arg1;
+ (id)_keyForPercentComplete:(double)arg1;
+ (id)_keyForTimeOfDayAtDate:(id)arg1;
+ (id)_keyForGoalType:(unsigned int)arg1;

@end

