//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NLDailyGoalProgressGoalRecommender : NSObject
{
}

+ (unsigned int)recommendGoalFromActivityCache:(id)arg1 firstWristOnDateToday:(id)arg2 currentTime:(id)arg3;
+ (double)_calculateSuccessPercentageFromCurrentPercentage:(double)arg1 firstWristOnDateToday:(id)arg2 currentTime:(id)arg3;

@end

