//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PUICTableViewCell.h"

@class UIColor, UIFont;

@interface NCABContactListViewCell : PUICTableViewCell
{
    UIColor *_textColor;
    UIColor *_textColorDisabled;
    UIFont *_emphasisFont;
    UIColor *_emphasisColor;
    UIColor *_emphasisColorDisabled;
}

- (void)_updateFonts;
@property(retain, nonatomic) UIColor *emphasisColorDisabled; // @synthesize emphasisColorDisabled=_emphasisColorDisabled;
@property(retain, nonatomic) UIColor *textColorDisabled; // @synthesize textColorDisabled=_textColorDisabled;
- (void)_contentSizeChanged:(id)arg1;
@property(retain, nonatomic) UIColor *emphasisColor; // @synthesize emphasisColor=_emphasisColor;
@property(retain, nonatomic) UIFont *emphasisFont; // @synthesize emphasisFont=_emphasisFont;
- (void).cxx_destruct;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
- (void)prepareForReuse;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

@end

