//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PUICTableViewCell.h"

@class NSMutableArray, UIButton, UILabel;

@interface NCABContactQuickCell : PUICTableViewCell
{
    UILabel *_titleLabel;
    UIButton *_callButton;
    UIButton *_messageButton;
    void *_record;
    void *_phoneNumbers;
    void *_emailAddresses;
    NSMutableArray *_constraints;
    id <NCABContactQuickCellDelegate> _delegate;
}

- (id)initWithCellIdentifier:(id)arg1;
- (void)_updateControlStates;
- (void)releaseData;
- (void)quickMessage:(id)arg1;
- (void)quickCall:(id)arg1;
- (void)contentSizeChanged;
- (void)updateFonts;
- (void).cxx_destruct;
- (void)setDestination:(id)arg1;
- (void)updateConstraints;
- (void)prepareForReuse;
@property(nonatomic) __weak id <NCABContactQuickCellDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;
- (void)setRecord:(void *)arg1;

@end

