//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface NCABPerson : NSObject <NSCopying>
{
    void *_abRecord;
    NSString *_fullName;
}

@property(retain, nonatomic) NSString *fullName; // @synthesize fullName=_fullName;
@property(nonatomic) void *abRecord; // @synthesize abRecord=_abRecord;
- (BOOL)isEqualToPerson:(id)arg1;
- (id)initWithABRecord:(void *)arg1 fullName:(id)arg2;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;

@end

