//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PUICTableViewCell.h"

@class NSMutableArray, UILabel;

@interface NCABContactNotesCell : PUICTableViewCell
{
    UILabel *_titleLabel;
    UILabel *_notesLabel;
    float _titleLeading;
    NSMutableArray *_constraints;
}

- (id)initWithCellIdentifier:(id)arg1;
- (void)setNotes:(id)arg1 compactOffset:(BOOL)arg2;
- (void)contentSizeChanged;
- (void)updateFonts;
- (void).cxx_destruct;
- (void)updateConstraints;
- (void)prepareForReuse;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

@end

