//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PUICTableViewController.h"

@class NCABModel, NSArray, NSDictionary, NSMutableDictionary, NSString, PUICContentUnavailableView;

@interface NCABContactListViewController : PUICTableViewController
{
    void *_addressBook;
    PUICContentUnavailableView *_contentUnavailableView;
    NSString *_cellIdentifier;
    NCABModel *_model;
    NSArray *_collectionSheetGlyphs;
    id _prefsChangedObserver;
    NSArray *_sectionIndexTitles;
    NSMutableDictionary *_sectionHeaderToSortingIndex;
    NSDictionary *_displayableSectionHeaderToSectionHeader;
    NSDictionary *_sectionHeaderToDisplayableSectionHeader;
    NSDictionary *_displayableSectionIndexToSectionIndex;
    NSDictionary *_sectionIndexToDisplayableSectionIndex;
    id <NCABContactListViewControllerDelegate> _delegate;
    id <NCABContactDetailViewControllerDelegate> _detailDelegate;
}

- (void)loadData;
@property(nonatomic) __weak id <NCABContactDetailViewControllerDelegate> detailDelegate; // @synthesize detailDelegate=_detailDelegate;
- (id)_displayableSectionIndexFromSectionIndex:(id)arg1;
- (id)_titleForHeaderInSection:(int)arg1;
- (id)_sectionHeaderSortingIndices;
- (id)_sectionIndexFromDisplayableSectionIndex:(id)arg1;
- (id)_displayableSectionHeaderFromSectionHeader:(id)arg1;
- (void)_createAllDisplayableSectionIndexAndHeaderCaches;
- (void)loadDataForTestName:(id)arg1;
- (void)_updateNoContentViewIfNecessary;
- (void)_contentSizeChanged:(id)arg1;
- (void)_prefsChanged;
- (void).cxx_destruct;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic) __weak id <NCABContactListViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (int)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(int)arg3;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)dealloc;
- (void)modelDatabaseChange:(id)arg1;

@end

