//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ACAccountStore, NSSet, NSString;

@interface NCABGroupWrapper : NSObject
{
    void *_addressBook;
    NSString *_accountIdentifier;
    void *_source;
    void *_group;
    NSString *_cachedName;
    ACAccountStore *_accountStore;
    id _delegate;
    BOOL _shouldBeSelectedWhenAllChildrenAreSelected;
    BOOL _selected;
    NSSet *_childGroupWrappers;
    NCABGroupWrapper *_parentGroupWrapper;
}

+ (id)newGroupWrapperFromDictionaryRepresentation:(id)arg1 withAddressBook:(void *)arg2;
+ (id)newGroupWrappersWithAccountIdentifier:(id)arg1 addressBook:(void *)arg2 excludingSearchableStores:(BOOL)arg3;
+ (id)newGroupWrappersWithAccountIdentifier:(id)arg1 addressBook:(void *)arg2;
+ (id)newGroupWrappersWithAccountIdentifier:(id)arg1 addressBook:(void *)arg2 accountStore:(id)arg3;
+ (id)newGroupWrappersWithAccountIdentifier:(id)arg1 addressBook:(void *)arg2 accountStore:(id)arg3 excludingSearchableStores:(BOOL)arg4 isSoleAccount:(BOOL)arg5;
- (int)score;
@property(readonly, nonatomic) void *addressBook; // @synthesize addressBook=_addressBook;
@property(readonly, nonatomic) NSString *accountIdentifier; // @synthesize accountIdentifier=_accountIdentifier;
@property(readonly, nonatomic) void *group; // @synthesize group=_group;
@property(readonly, nonatomic) void *source; // @synthesize source=_source;
@property(readonly, nonatomic) int sourceType;
@property(nonatomic, getter=isSelected) BOOL selected; // @synthesize selected=_selected;
@property(readonly, nonatomic) NSString *name;
@property(nonatomic) id <NCABGroupWrapperDelegate> delegate; // @synthesize delegate=_delegate;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;
@property(retain, nonatomic) ACAccountStore *accountStore; // @synthesize accountStore=_accountStore;
@property(nonatomic) BOOL shouldBeSelectedWhenAllChildrenAreSelected; // @synthesize shouldBeSelectedWhenAllChildrenAreSelected=_shouldBeSelectedWhenAllChildrenAreSelected;
@property(retain, nonatomic) NSSet *childGroupWrappers; // @synthesize childGroupWrappers=_childGroupWrappers;
- (BOOL)isContainerWrapper;
- (BOOL)showLinkedPeople;
- (id)_rootGroupWrapper;
- (void)setSelected:(BOOL)arg1 propagateSelectionToChildren:(BOOL)arg2;
- (void)childGroupWrapper:(id)arg1 didBecomeSelected:(BOOL)arg2;
@property(readonly, nonatomic) NSString *_accountDescriptionBasedOnIdentifier;
- (id)initWithAddressBook:(void *)arg1 accountIdentifier:(id)arg2 source:(void *)arg3 group:(void *)arg4;
- (id)copyDictionaryRepresentation;
- (BOOL)isGlobalWrapper;
- (BOOL)toggleSelection;
- (int)compareToGroupWrapper:(id)arg1;
@property(nonatomic) NCABGroupWrapper *parentGroupWrapper; // @synthesize parentGroupWrapper=_parentGroupWrapper;
- (BOOL)isDirectoryWrapper;

@end

