//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIImage;

@interface EJAnimatedGIFFrame : NSObject
{
    UIImage *_image;
    float _durationInSeconds;
}

@property(nonatomic) float durationInSeconds; // @synthesize durationInSeconds=_durationInSeconds;
- (void).cxx_destruct;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;

@end

