//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Emoji/EJEmoji.h>

@class EJEmojiImage, NSMutableArray;

@interface EJAnimatedEmoji : EJEmoji
{
    NSMutableArray *_emojiImages;
    EJEmojiImage *_animatedEmojiImage;
    float _preferredScale;
    double _durationInSeconds;
}

+ (id)animatedEmojiWithContentsOfFile:(id)arg1;
+ (id)animatedEmojiWithCollection:(id)arg1;
+ (id)animatedEmojiWithAnimatedGIF:(id)arg1;
- (id)emojiImage;
- (BOOL)writeAnimatedEmojiToGIF;
- (void)writeImageToCache;
- (id)attributedStringFromEmoji;
- (id)animatedImageWithEmojiImagesAtPreferredScale;
- (id)animatedImageWithEmojiImages;
- (id)arrayOfImagesBeingAnimated;
@property(nonatomic) double durationInSeconds; // @synthesize durationInSeconds=_durationInSeconds;
- (void)addEmojiImage:(id)arg1;
@property(nonatomic) float preferredScale; // @synthesize preferredScale=_preferredScale;
- (void).cxx_destruct;
- (id)init;

@end

