//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Emoji/EJEmojiView.h>

@class EJEmojiGridView, EJMutableEmojiCollection;

@interface EJEmojiZoomedInView : EJEmojiView
{
    EJEmojiGridView *_emojiGridView;
    EJMutableEmojiCollection *_singleEmojiCollection;
}

- (id)initWithFrame:(struct CGRect)arg1 forEmoji:(id)arg2;
- (void).cxx_destruct;
- (void)setEmoji:(id)arg1;
- (id)emoji;

@end

