//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface EmojiGesture : NSObject
{
    BOOL _bidirectional;
    int _emoji;
    int _state;
    NSArray *_unitPoints;
    float _likelihood;
}

@property(nonatomic) float likelihood; // @synthesize likelihood=_likelihood;
@property(nonatomic) BOOL bidirectional; // @synthesize bidirectional=_bidirectional;
@property(retain, nonatomic) NSArray *unitPoints; // @synthesize unitPoints=_unitPoints;
- (void).cxx_destruct;
@property(nonatomic) int emoji; // @synthesize emoji=_emoji;
- (void)reset;
@property(nonatomic) int state; // @synthesize state=_state;
- (id)init;

@end

