//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface NNMKSyncEndpoint : NSObject
{
    NSObject<OS_dispatch_queue> *_endpointQueue;
    NSObject<OS_dispatch_queue> *_resendingQueue;
    NSMutableDictionary *_datesForIDSIdentifiersScheduledToBeResent;
    NSMutableDictionary *_lastResendIntervalKeyedByIDSIdentifier;
}

@property(retain, nonatomic) NSMutableDictionary *lastResendIntervalKeyedByIDSIdentifier; // @synthesize lastResendIntervalKeyedByIDSIdentifier=_lastResendIntervalKeyedByIDSIdentifier;
@property(retain, nonatomic) NSMutableDictionary *datesForIDSIdentifiersScheduledToBeResent; // @synthesize datesForIDSIdentifiersScheduledToBeResent=_datesForIDSIdentifiersScheduledToBeResent;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *resendingQueue; // @synthesize resendingQueue=_resendingQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *endpointQueue; // @synthesize endpointQueue=_endpointQueue;
- (void)dequeueIDSIdentifierForResend:(id)arg1;
- (unsigned int)newResendIntervalForPreviousResendInterval:(unsigned int)arg1 errorCode:(int)arg2;
- (void)resendReadyIDSIdentifiers;
- (void)enqueueIDSIdentifiersForResend:(id)arg1;
- (void)resendIDSIdentifier:(id)arg1;
- (void)enqueueIDSIdentifierForResend:(id)arg1 atDate:(id)arg2 silent:(BOOL)arg3;
- (void).cxx_destruct;
- (id)initWithQueue:(id)arg1;

@end

