//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NNMKMessageContentAssetsManager : NSObject
{
}

+ (BOOL)imageHasBeenDownloadedForMessageWithId:(id)arg1 contentId:(id)arg2;
+ (BOOL)messageContentHasBeenDownloadedForMessageWithId:(id)arg1;
+ (id)messageContentWithId:(id)arg1;
+ (id)_assetsBaseDirectory;
+ (id)urlForImageAttachmentsFolderForMessageWithId:(id)arg1;
+ (id)_urlForAssetForMessageId:(id)arg1 inSubdirectory:(id)arg2;
+ (id)urlForMessageContentWithId:(id)arg1;
+ (id)urlForImageAttachmentOfMessageWithId:(id)arg1 contentId:(id)arg2;

@end

