//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NNMKSyncReceiverDelegate.h"

@class NNMKSyncReceiver, NSMutableSet, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_semaphore>, NSString;

@interface NNMKMessageSender : NSObject <NNMKSyncReceiverDelegate>
{
    NSObject<OS_dispatch_queue> *_senderQueue;
    NNMKSyncReceiver *_syncReceiver;
    NSObject<OS_dispatch_semaphore> *_retrievingInitialAccountsSemaphore;
    NSMutableSet *_accountIds;
}

@property(retain, nonatomic) NSMutableSet *accountIds; // @synthesize accountIds=_accountIds;
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *retrievingInitialAccountsSemaphore; // @synthesize retrievingInitialAccountsSemaphore=_retrievingInitialAccountsSemaphore;
@property(retain, nonatomic) NNMKSyncReceiver *syncReceiver; // @synthesize syncReceiver=_syncReceiver;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *senderQueue; // @synthesize senderQueue=_senderQueue;
- (BOOL)canSendMessages;
- (void)syncReceiverDidResetXPCConnection:(id)arg1;
- (void)syncReceiverDidRequestReloadCache:(id)arg1;
- (void)syncReceiver:(id)arg1 didDeleteAccountWithId:(id)arg2;
- (void)syncReceiver:(id)arg1 didAddNewAccount:(id)arg2;
- (void)syncReceiver:(id)arg1 didReplyWithAccounts:(id)arg2;
- (void)sendMessageTo:(id)arg1 cc:(id)arg2 subject:(id)arg3 body:(id)arg4;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

