//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NNMKSyncReceiverXPCBasicClientInterface.h"

@class NNMKMessage, NSString;

@protocol NNMKSyncReceiverXPCMessageUpdatesBasedClientInterface <NNMKSyncReceiverXPCBasicClientInterface>
- (oneway void)receiverXPCServerDidDeleteMessageWithId:(NSString *)arg1;
- (oneway void)receiverXPCServerDidUpdateMessage:(NNMKMessage *)arg1;
- (oneway void)receiverXPCServerDidAddNewMessage:(NNMKMessage *)arg1;
@end

