//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NNMKAccount, NNMKMessage, NSArray, NSError, NSString, NSURL;

@protocol NNMKSyncReceiverXPCBasicClientInterface <NSObject>
- (oneway void)receiverXPCServerConnectivityDidChange:(BOOL)arg1;
- (oneway void)receiverXPCServerDidRequestReloadCache;
- (oneway void)receiverXPCServerDidDeleteAllMessages;
- (oneway void)receiverXPCServerDidDeleteAccountWithId:(NSString *)arg1;
- (oneway void)receiverXPCServerDidUpdateAccount:(NNMKAccount *)arg1;
- (oneway void)receiverXPCServerDidAddNewAccount:(NNMKAccount *)arg1;
- (oneway void)receiverXPCServerDidReceiveImageAttachmentForMessageWithId:(NSString *)arg1 contentId:(NSString *)arg2;
- (oneway void)receiverXPCServerDidReceiveContentForMessageWithId:(NSString *)arg1;
- (oneway void)receiverXPCServerDidReplyWithFirstUnreadMessages:(NSArray *)arg1;
- (oneway void)receiverXPCServerDidReplyWithIsConnected:(BOOL)arg1;
- (oneway void)receiverXPCServerDidReplyWithSyncedMailboxType:(unsigned int)arg1 accountId:(NSString *)arg2 url:(NSURL *)arg3 customName:(NSString *)arg4;
- (oneway void)receiverXPCServerDidReplyWithAccounts:(NSArray *)arg1;
- (oneway void)receiverXPCServerDidReplyWithMessageContentLoadFailedForMessageWithId:(NSString *)arg1;
- (oneway void)receiverXPCServerDidReplyWithMessage:(NNMKMessage *)arg1;
- (oneway void)receiverXPCServerDidReplyWithConversationOperations:(NSArray *)arg1 totalConversationsCount:(unsigned int)arg2 willFetch:(BOOL)arg3 error:(NSError *)arg4;
@end

