//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "RMSDAAPControlSessionDelegate.h"

@class BKSProcessAssertion, NMUNowPlayingArtworkView, NRUBacklightAssertion, NRUCachedService, NSObject<OS_dispatch_source>, NSString, RMSControlInterface;

@interface NRUDAAPControlSessionViewController : UIViewController <RMSDAAPControlSessionDelegate>
{
    NRUBacklightAssertion *_backlightAssertion;
    int _pendingConnectionResponseCode;
    BKSProcessAssertion *_processAssertion;
    NSObject<OS_dispatch_source> *_connectionTimeoutTimer;
    NSString *_wakeIdentifier;
    NSString *_artworkIdentifier;
    BOOL _shouldWaitForNowPlayingInfo;
    BOOL _isActive;
    BOOL _needsReconnect;
    BOOL _hasPendingConnectionResponse;
    CDUnknownBlockType _connectionHandler;
    NMUNowPlayingArtworkView *_artworkView;
    id <RMSDAAPControlSession> _controlSession;
    RMSControlInterface *_controlInterface;
    NRUCachedService *_cachedService;
    id <NRUDAAPControlSessionViewControllerDelegate> _delegate;
}

- (void)controlSessionDidEnd:(id)arg1;
- (void)controlSession:(id)arg1 didUpdateVolume:(float)arg2;
- (void)controlSession:(id)arg1 didUpdateNowPlayingInfo:(id)arg2;
- (void)controlSession:(id)arg1 didUpdateAudioRoutes:(id)arg2;
- (void)controlSession:(id)arg1 artworkDataDidBecomeAvailable:(id)arg2 identifier:(id)arg3;
@property(readonly, nonatomic) RMSControlInterface *controlInterface; // @synthesize controlInterface=_controlInterface;
- (void)_applicationWillResignActiveNotification:(id)arg1;
@property(readonly, nonatomic) NRUCachedService *cachedService; // @synthesize cachedService=_cachedService;
@property(readonly, nonatomic) NMUNowPlayingArtworkView *artworkView; // @synthesize artworkView=_artworkView;
- (void)_cancelTimeoutTimer;
- (void)connectToService:(id)arg1 shouldWaitForNowPlayingInfo:(BOOL)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)setProcessedArtworkImage:(id)arg1 identifier:(id)arg2;
- (void)_invokeConnectionHandlerWithResponseCode:(int)arg1;
- (void)_takeProcessAssertion;
- (void)_takeWakeAssertion;
- (void)_releaseWakeAssertion;
- (void)_releaseProcessAssertion;
- (void)_applicationResumedNotification:(id)arg1;
- (void)_applicationSuspendedNotification:(id)arg1;
@property(readonly, nonatomic) id <RMSDAAPControlSession> controlSession; // @synthesize controlSession=_controlSession;
- (void)_reconnect;
- (void).cxx_destruct;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak id <NRUDAAPControlSessionViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)init;
- (void)dealloc;
- (void)_applicationDidBecomeActiveNotification:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

