//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoRemoteMediaServicesUI/NRUDAAPControlSessionViewController.h>

#import "NMUNowPlayingFeedbackViewControllerDelegate.h"
#import "NMUTransportControlsViewDelegate.h"
#import "PUICActionControllerDelegate.h"
#import "RMSDAAPControlSessionDelegate.h"

@class NMUNowPlayingFeedbackViewController, NMUNowPlayingView, NSArray, NSObject<OS_dispatch_source>, NSString, NSTimer, PUICActionController, PUICActionSheetController, PUICEventThrottler, RMSAudioRoute, RMSNowPlayingInfo;

@interface NRUNowPlayingViewController : NRUDAAPControlSessionViewController <RMSDAAPControlSessionDelegate, NMUTransportControlsViewDelegate, NMUNowPlayingFeedbackViewControllerDelegate, PUICActionControllerDelegate>
{
    RMSNowPlayingInfo *_lastNowPlayingInfo;
    PUICActionController *_actionController;
    NSObject<OS_dispatch_source> *_optimisticPlayPauseTimer;
    NSObject<OS_dispatch_source> *_delayedNowPlayingUpdateTimer;
    BOOL _finishedAppearanceTransition;
    PUICActionSheetController *_airPlayActionSheet;
    RMSAudioRoute *_currentlySelectingAirPlayRoute;
    NSArray *_airPlayRoutes;
    NSArray *_airPlayActionSheetItems;
    NMUNowPlayingFeedbackViewController *_feedbackController;
    RMSNowPlayingInfo *_feedbackNowPlayingInfo;
    double _currentTrackElapsedTime;
    double _elapsedTime;
    NSTimer *_elapsedTimeUpdateTimer;
    PUICEventThrottler *_volumeThrottler;
    NSObject<OS_dispatch_source> *_delayedVolumeUpdatedTimer;
    NSTimer *_volumeLongPressUpdateTimer;
    float _lastReceivedVolumeValue;
    BOOL _receivedFirstVolumeUpdate;
    NMUNowPlayingView *_nowPlayingView;
}

- (void)controlSession:(id)arg1 didUpdateVolume:(float)arg2;
- (void)controlSession:(id)arg1 didUpdateNowPlayingInfo:(id)arg2;
- (void)controlSession:(id)arg1 didUpdateAudioRoutes:(id)arg2;
- (BOOL)canProvideActionController;
- (id)actionController;
- (void)_selectAirPlayRoute:(id)arg1 actionSheetItem:(id)arg2;
- (id)_audioRouteActionSheetItems;
- (void)_cancelDelayedVolumeUpdateTimer;
- (id)_scheduleTimerWithDelay:(double)arg1 block:(CDUnknownBlockType)arg2;
- (void)_cancelOptimisticPlayPauseTimer;
- (void)_scheduleDelayedVolumeUpdate;
- (void)_updateElapsedTime;
- (void)_cancelDelayedNowPlayingUpdateTimer;
- (void)_addToWishlist;
- (void)_setLikedState:(int)arg1;
- (void)_airPlayActionItemTapped:(id)arg1;
- (void)_optimisticallySetPlaying:(BOOL)arg1;
- (void)_skipByInterval:(double)arg1;
- (void)_resetElapsedTime;
- (void)_handleVolumeUpdate;
- (void)_updateAirPlayRoutes;
- (void)_handleNowPlayingUpdate:(id)arg1;
- (void)_scheduleDelayedNowPlayingUpdate:(id)arg1;
- (BOOL)_isNowPlayingUpdateBogus:(id)arg1;
- (void)_handleElapsedTimeUpdateTimer:(id)arg1;
- (void)_updateAvailableControls;
- (void)_volumeDidChange;
- (void)feedbackActionSheetController:(id)arg1 willDismissForTappedAction:(int)arg2;
- (void)feedbackActionSheetControllerDidCancel:(id)arg1;
- (void)transportControlsView:(id)arg1 tapOnControlType:(int)arg2;
@property(readonly, nonatomic) NMUNowPlayingView *nowPlayingView; // @synthesize nowPlayingView=_nowPlayingView;
- (void).cxx_destruct;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

