//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NRUPairingViewController, NSString;

@protocol NRUPairingViewControllerDelegate <NSObject>
- (void)pairingViewControllerDidCancel:(NRUPairingViewController *)arg1;
- (void)pairingViewController:(NRUPairingViewController *)arg1 didPairWithNetService:(NSString *)arg2;
@end

