//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIGestureRecognizer.h"

@class NSArray, NSMutableArray;

@interface NRUTouchRemoteSwipeGestureRecognizer : UIGestureRecognizer
{
    NSMutableArray *_recentTouches;
    struct CGPoint _swipeStartLocation;
    BOOL _moving;
    NSArray *_occludingViews;
    int _direction;
    id <NRUTouchRemoteSwipeGestureRecognizerDelegate> _swipeDelegate;
}

@property(retain, nonatomic) NSArray *occludingViews; // @synthesize occludingViews=_occludingViews;
- (void).cxx_destruct;
- (BOOL)cancelsTouchesInView;
- (BOOL)canBePreventedByGestureRecognizer:(id)arg1;
@property(nonatomic) int direction; // @synthesize direction=_direction;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
@property(nonatomic) __weak id <NRUTouchRemoteSwipeGestureRecognizerDelegate> swipeDelegate; // @synthesize swipeDelegate=_swipeDelegate;

@end

