//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NRUTouchRemoteAnimationController : NSObject
{
}

+ (void)animateFadeTouchRemoteInstructions:(id)arg1 delegate:(id)arg2;
+ (void)pausePulseArrows:(id)arg1;
+ (void)_pausePulseForArrow:(id)arg1 atPosition:(struct CGPoint)arg2;
+ (void)_animatePulseTouchArrow:(id)arg1 position:(struct CGPoint)arg2;
+ (void)_animateSwipeLabel:(id)arg1 hidden:(BOOL)arg2;
+ (void)animateTouchRemoteButton:(id)arg1 hidden:(BOOL)arg2 delegate:(id)arg3;
+ (void)animatePulseArrows:(id)arg1;
+ (void)_animateUnfoldTouchArrow:(id)arg1 position:(struct CGPoint)arg2;
+ (struct CGPoint)_unfoldPositionForRightArrowInRect:(struct CGRect)arg1;
+ (struct CGPoint)_unfoldPositionForLeftArrowInRect:(struct CGRect)arg1;
+ (struct CGPoint)_unfoldPositionForDownArrowInRect:(struct CGRect)arg1;
+ (struct CGPoint)_unfoldPositionForUpArrowInRect:(struct CGRect)arg1;
+ (void)_animateFoldTouchArrow:(id)arg1;
+ (void)prepareTouchRemoteControllerShowAnimation:(id)arg1;
+ (void)animateTouchRemoteController:(id)arg1 hidden:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;

@end

