//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NRUTouchRemoteView;

@protocol NRUTouchRemoteViewDelegate <NSObject>
- (void)touchRemoteViewPlayPauseButtonTapped:(NRUTouchRemoteView *)arg1;
- (void)touchRemoteViewMenuButtonLongPressed:(NRUTouchRemoteView *)arg1;
- (void)touchRemoteViewMenuButtonTapped:(NRUTouchRemoteView *)arg1;
@end

