//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface NGSGlance : NSObject <NSCopying>
{
    _Bool _cannotBeDisabled;
    _Bool _active;
    _Bool _defaultGlance;
    _Bool _prelaunch;
    NSString *_name;
    NSString *_appBundleIdentifier;
    NSString *_glanceBundleIdentifier;
    NSString *_sockPuppetIdentifier;
}

@property(nonatomic) _Bool prelaunch; // @synthesize prelaunch=_prelaunch;
@property(nonatomic, getter=isDefaultGlance) _Bool defaultGlance; // @synthesize defaultGlance=_defaultGlance;
@property(nonatomic, getter=isActive) _Bool active; // @synthesize active=_active;
@property(nonatomic) _Bool cannotBeDisabled; // @synthesize cannotBeDisabled=_cannotBeDisabled;
@property(copy, nonatomic) NSString *sockPuppetIdentifier; // @synthesize sockPuppetIdentifier=_sockPuppetIdentifier;
@property(copy, nonatomic) NSString *glanceBundleIdentifier; // @synthesize glanceBundleIdentifier=_glanceBundleIdentifier;
@property(copy, nonatomic) NSString *appBundleIdentifier; // @synthesize appBundleIdentifier=_appBundleIdentifier;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
@property(readonly, nonatomic) NSString *glanceIdentifier;
- (id)initWithDictionary:(id)arg1;

@end

