//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BBBulletin, BBObserver, BBSectionInfo, BBSectionParameters, BBThumbnailSizeConstraints, NSArray, NSData, NSDictionary, NSSet, NSString, UIImage;

@protocol BBObserverDelegate <NSObject>

@optional
- (struct CGSize)observer:(BBObserver *)arg1 composedAttachmentSizeForType:(int)arg2 thumbnailWidth:(float)arg3 height:(float)arg4 key:(NSString *)arg5;
- (UIImage *)observer:(BBObserver *)arg1 composedAttachmentImageForType:(int)arg2 thumbnailData:(NSData *)arg3 key:(NSString *)arg4;
- (NSDictionary *)observer:(BBObserver *)arg1 multipleThumbnailSizeConstraintsForAttachmentType:(int)arg2;
- (BBThumbnailSizeConstraints *)observer:(BBObserver *)arg1 thumbnailSizeConstraintsForAttachmentType:(int)arg2;
- (BOOL)observerShouldFetchAttachmentSizeBeforeBulletinDelivery:(BBObserver *)arg1;
- (BOOL)observerShouldFetchAttachmentImageBeforeBulletinDelivery:(BBObserver *)arg1;
- (void)observer:(BBObserver *)arg1 noteServerReceivedResponseForBulletin:(BBBulletin *)arg2;
- (void)observer:(BBObserver *)arg1 noteServerConnectionStateChanged:(BOOL)arg2;
- (void)observer:(BBObserver *)arg1 noteInvalidatedBulletinIDs:(NSSet *)arg2;
- (void)observer:(BBObserver *)arg1 noteAlertBehaviorOverrideStateChanged:(unsigned int)arg2;
- (void)observer:(BBObserver *)arg1 noteAlertBehaviorOverridesChanged:(unsigned int)arg2;
- (void)observer:(BBObserver *)arg1 purgeReferencesToBulletinID:(NSString *)arg2;
- (void)observer:(BBObserver *)arg1 noteSectionParametersChanged:(BBSectionParameters *)arg2 forSectionID:(NSString *)arg3;
- (void)observer:(BBObserver *)arg1 updateSectionInfo:(BBSectionInfo *)arg2;
- (void)observer:(BBObserver *)arg1 updateSectionInfo:(BBSectionInfo *)arg2 inCategory:(int)arg3;
- (void)observer:(BBObserver *)arg1 updateSectionOrder:(NSArray *)arg2;
- (void)observer:(BBObserver *)arg1 updateSectionOrder:(NSArray *)arg2 forCategory:(int)arg3;
- (void)observer:(BBObserver *)arg1 updateSectionOrderRule:(int)arg2;
- (void)observer:(BBObserver *)arg1 removeBulletin:(BBBulletin *)arg2;
- (void)observer:(BBObserver *)arg1 removeBulletin:(BBBulletin *)arg2 forFeed:(unsigned int)arg3;
- (void)observer:(BBObserver *)arg1 modifyBulletin:(BBBulletin *)arg2;
- (void)observer:(BBObserver *)arg1 modifyBulletin:(BBBulletin *)arg2 forFeed:(unsigned int)arg3;
- (void)observer:(BBObserver *)arg1 addBulletin:(BBBulletin *)arg2 forFeed:(unsigned int)arg3;
- (void)observer:(BBObserver *)arg1 addBulletin:(BBBulletin *)arg2 forFeed:(unsigned int)arg3 playLightsAndSirens:(BOOL)arg4 withReply:(void (^)(BOOL))arg5;
@end

