//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface BLTBulletinReplyInfo : NSObject
{
    BOOL _replySent;
    CDUnknownBlockType _reply;
    unsigned int _shouldPlayLightsAndSirens;
    NSDate *_transmissionDate;
    NSDate *_receptionDate;
    NSDate *_expiration;
    NSDate *_companionPublicationDate;
    NSDate *_gizmoPublicationDate;
    NSString *_matchID;
    NSString *_sectionID;
}

@property(retain, nonatomic) NSDate *expiration; // @synthesize expiration=_expiration;
@property(copy, nonatomic) CDUnknownBlockType reply; // @synthesize reply=_reply;
@property(readonly, nonatomic) BOOL replySent; // @synthesize replySent=_replySent;
@property(retain, nonatomic) NSDate *receptionDate; // @synthesize receptionDate=_receptionDate;
- (BOOL)hasBeenMatched;
@property(retain, nonatomic) NSDate *gizmoPublicationDate; // @synthesize gizmoPublicationDate=_gizmoPublicationDate;
@property(retain, nonatomic) NSDate *companionPublicationDate; // @synthesize companionPublicationDate=_companionPublicationDate;
- (BOOL)sendReplyWithIsConnected:(BOOL)arg1 isWristDetectDisabled:(BOOL)arg2;
@property(nonatomic) unsigned int shouldPlayLightsAndSirens; // @synthesize shouldPlayLightsAndSirens=_shouldPlayLightsAndSirens;
@property(copy, nonatomic) NSString *matchID; // @synthesize matchID=_matchID;
@property(retain, nonatomic) NSDate *transmissionDate; // @synthesize transmissionDate=_transmissionDate;
- (BOOL)hasExpired;
- (void).cxx_destruct;
- (id)description;
- (id)init;
@property(copy, nonatomic) NSString *sectionID; // @synthesize sectionID=_sectionID;

@end

