//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BLTBulletinStore, NSDate, NSMutableDictionary;

@interface BLTBulletinReplyInfoCache : NSObject
{
    NSMutableDictionary *_localReplyInfo;
    NSDate *_timeToCheck;
    BLTBulletinStore *_bulletinStore;
}

+ (void)expire;
+ (void)expireForTesting;
+ (id)sharedReplyCache;
+ (int)count;
- (void)expireForTesting;
@property(retain, nonatomic) BLTBulletinStore *bulletinStore; // @synthesize bulletinStore=_bulletinStore;
- (void)purgeReplyInfo:(id)arg1 withSectionID:(id)arg2 matchID:(id)arg3;
- (id)retrieveReplyInfoWithSectionID:(id)arg1 matchID:(id)arg2;
- (id)cacheShouldPlayLightsAndSirens:(unsigned int)arg1 withSectionID:(id)arg2 matchID:(id)arg3 transmissionDate:(id)arg4 receptionDate:(id)arg5 companionPublicationDate:(id)arg6;
- (id)cacheReply:(CDUnknownBlockType)arg1 withSectionID:(id)arg2 matchID:(id)arg3 gizmoPublicationDate:(id)arg4;
- (void)_removeReplyInfoFromStore:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *localReplyInfo; // @synthesize localReplyInfo=_localReplyInfo;
- (id)_keyForSectionID:(id)arg1 matchID:(id)arg2;
- (id)_firstReplyInfoWithNoStateWithSectionID:(id)arg1 matchID:(id)arg2;
- (void)_addReplyInfo:(id)arg1 forSectionID:(id)arg2 matchID:(id)arg3;
- (id)_firstReplyInfoWithNoReplyWithSectionID:(id)arg1 matchID:(id)arg2;
- (void)_checkCacheWithForce:(BOOL)arg1;
- (id)_cacheShouldPlayLightsAndSirens:(unsigned int)arg1 withSectionID:(id)arg2 matchID:(id)arg3;
- (void)_loadItemsFromStore;
- (void)_setNextTimeToCheck;
@property(retain, nonatomic) NSDate *timeToCheck; // @synthesize timeToCheck=_timeToCheck;
- (BOOL)_isTimeToCheck;
- (void)_checkCache;
- (void).cxx_destruct;
- (void)clear;
- (id)init;
- (int)count;
- (id)initWithStore:(id)arg1;

@end

