//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BLTObjectCacheItem : NSObject
{
    NSObject *_object;
    double _lastAccessedDate;
}

+ (id)cacheItemWithObject:(id)arg1;
@property(readonly, nonatomic) double lastAccessedDate; // @synthesize lastAccessedDate=_lastAccessedDate;
- (id)initWithObject:(id)arg1;
- (void).cxx_destruct;
- (void)touch;
@property(readonly, nonatomic) NSObject *object; // @synthesize object=_object;
- (id)description;

@end

