//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@class BLTPBAction, NSData, NSMutableArray, NSString;

@interface BLTPBBulletin : PBCodable <NSCopying>
{
    double _date;
    double _publicationDate;
    NSData *_alertSuppressionContexts;
    NSData *_attachment;
    unsigned int _attachmentType;
    NSString *_bulletinID;
    NSString *_category;
    NSData *_context;
    BLTPBAction *_dismissAction;
    unsigned int _feed;
    NSString *_messageTitle;
    NSString *_publisherBulletinID;
    NSString *_recordID;
    NSString *_sectionDisplayName;
    NSString *_sectionID;
    int _sectionSubtype;
    BLTPBAction *_snoozeAction;
    NSString *_sockPuppetAppBundleID;
    NSString *_soundAccountIdentifier;
    int _soundAlertType;
    NSString *_soundToneIdentifier;
    NSString *_subtitle;
    NSMutableArray *_supplementaryActions;
    NSString *_teamID;
    NSString *_title;
    NSString *_universalSectionID;
    BOOL _containsUpdatedAttachment;
    BOOL _includesSound;
    BOOL _loading;
    struct {
        unsigned int date:1;
        unsigned int publicationDate:1;
        unsigned int attachmentType:1;
        unsigned int sectionSubtype:1;
        unsigned int soundAlertType:1;
        unsigned int containsUpdatedAttachment:1;
        unsigned int loading:1;
    } _has;
}

+ (void)bulletinWithBBBulletin:(id)arg1 sockPuppetAppBundleID:(id)arg2 isSockPuppetAppInstalled:(BOOL)arg3 observer:(id)arg4 feed:(unsigned int)arg5 teamID:(id)arg6 universalSectionID:(id)arg7 completion:(CDUnknownBlockType)arg8;
+ (void)_addPrimaryAttachmentFromBBBulletin:(id)arg1 toBLTPBBulletin:(id)arg2 observer:(id)arg3 completion:(CDUnknownBlockType)arg4;
+ (id)_actionWithBBAction:(id)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)mergeFrom:(id)arg1;
@property(nonatomic) BOOL loading; // @synthesize loading=_loading;
@property(retain, nonatomic) NSString *recordID; // @synthesize recordID=_recordID;
@property(retain, nonatomic) NSString *teamID; // @synthesize teamID=_teamID;
@property(nonatomic) BOOL hasDate;
@property(readonly, nonatomic) BOOL hasCategory;
@property(readonly, nonatomic) BOOL hasRecordID;
@property(nonatomic) BOOL containsUpdatedAttachment; // @synthesize containsUpdatedAttachment=_containsUpdatedAttachment;
@property(nonatomic) unsigned int attachmentType; // @synthesize attachmentType=_attachmentType;
@property(retain, nonatomic) NSString *soundToneIdentifier; // @synthesize soundToneIdentifier=_soundToneIdentifier;
@property(retain, nonatomic) NSString *soundAccountIdentifier; // @synthesize soundAccountIdentifier=_soundAccountIdentifier;
@property(nonatomic) int soundAlertType; // @synthesize soundAlertType=_soundAlertType;
@property(nonatomic) BOOL includesSound; // @synthesize includesSound=_includesSound;
@property(retain, nonatomic) NSString *sockPuppetAppBundleID; // @synthesize sockPuppetAppBundleID=_sockPuppetAppBundleID;
@property(retain, nonatomic) NSString *messageTitle; // @synthesize messageTitle=_messageTitle;
@property(nonatomic) BOOL hasLoading;
@property(nonatomic) BOOL hasContainsUpdatedAttachment;
@property(nonatomic) BOOL hasAttachmentType;
@property(readonly, nonatomic) BOOL hasSoundToneIdentifier;
@property(readonly, nonatomic) BOOL hasSoundAccountIdentifier;
@property(nonatomic) BOOL hasSoundAlertType;
@property(readonly, nonatomic) BOOL hasAlertSuppressionContexts;
@property(readonly, nonatomic) BOOL hasContext;
@property(readonly, nonatomic) BOOL hasTeamID;
@property(nonatomic) BOOL hasPublicationDate;
@property(readonly, nonatomic) BOOL hasSockPuppetAppBundleID;
@property(nonatomic) BOOL hasSectionSubtype;
@property(readonly, nonatomic) BOOL hasDismissAction;
@property(readonly, nonatomic) BOOL hasSnoozeAction;
@property(readonly, nonatomic) BOOL hasAttachment;
@property(readonly, nonatomic) BOOL hasMessageTitle;
@property(readonly, nonatomic) BOOL hasSubtitle;
@property(readonly, nonatomic) BOOL hasSectionDisplayName;
@property(readonly, nonatomic) BOOL hasBulletinID;
- (id)supplementaryActionsAtIndex:(unsigned int)arg1;
- (void)clearSupplementaryActions;
- (unsigned int)supplementaryActionsCount;
- (void)addSupplementaryActions:(id)arg1;
@property(readonly, nonatomic) BOOL hasUniversalSectionID;
- (id)sectionMatchID;
@property(readonly, nonatomic) BOOL hasSectionID;
@property(readonly, nonatomic) BOOL hasPublisherBulletinID;
@property(retain, nonatomic) NSString *sectionDisplayName; // @synthesize sectionDisplayName=_sectionDisplayName;
@property(nonatomic) unsigned int feed; // @synthesize feed=_feed;
@property(retain, nonatomic) NSMutableArray *supplementaryActions; // @synthesize supplementaryActions=_supplementaryActions;
- (id)publisherMatchID;
@property(retain, nonatomic) BLTPBAction *snoozeAction; // @synthesize snoozeAction=_snoozeAction;
@property(retain, nonatomic) BLTPBAction *dismissAction; // @synthesize dismissAction=_dismissAction;
@property(nonatomic) double publicationDate; // @synthesize publicationDate=_publicationDate;
@property(retain, nonatomic) NSData *alertSuppressionContexts; // @synthesize alertSuppressionContexts=_alertSuppressionContexts;
@property(nonatomic) int sectionSubtype; // @synthesize sectionSubtype=_sectionSubtype;
@property(retain, nonatomic) NSString *publisherBulletinID; // @synthesize publisherBulletinID=_publisherBulletinID;
@property(retain, nonatomic) NSString *universalSectionID; // @synthesize universalSectionID=_universalSectionID;
@property(retain, nonatomic) NSString *bulletinID; // @synthesize bulletinID=_bulletinID;
@property(retain, nonatomic) NSData *attachment; // @synthesize attachment=_attachment;
@property(readonly, nonatomic) BOOL hasTitle;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *category; // @synthesize category=_category;
- (id)dictionaryRepresentation;
@property(retain, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(nonatomic) double date; // @synthesize date=_date;
@property(retain, nonatomic) NSData *context; // @synthesize context=_context;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (id)description;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
@property(retain, nonatomic) NSString *sectionID; // @synthesize sectionID=_sectionID;

@end

