//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBRequest.h"

#import "NSCopying.h"

@class NSString;

@interface BLTPBHandleDidPlayLightsAndSirensReplyRequest : PBRequest <NSCopying>
{
    double _date;
    NSString *_phoneSectionID;
    NSString *_publisherMatchID;
    BOOL _didPlayLightsAndSirens;
    struct {
        unsigned int date:1;
        unsigned int didPlayLightsAndSirens:1;
    } _has;
}

- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)mergeFrom:(id)arg1;
@property(nonatomic) BOOL hasDate;
@property(retain, nonatomic) NSString *phoneSectionID; // @synthesize phoneSectionID=_phoneSectionID;
@property(nonatomic) BOOL didPlayLightsAndSirens; // @synthesize didPlayLightsAndSirens=_didPlayLightsAndSirens;
@property(readonly, nonatomic) BOOL hasPhoneSectionID;
@property(readonly, nonatomic) BOOL hasPublisherMatchID;
@property(nonatomic) BOOL hasDidPlayLightsAndSirens;
@property(retain, nonatomic) NSString *publisherMatchID; // @synthesize publisherMatchID=_publisherMatchID;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
@property(nonatomic) double date; // @synthesize date=_date;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;

@end

