//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface BLTSectionIdentifierMapping : NSObject
{
    NSString *_localSectionID;
    NSString *_remoteSectionID;
    NSString *_universalSectionID;
    NSString *_mirroredSectionID;
}

@property(copy, nonatomic) NSString *mirroredSectionID; // @synthesize mirroredSectionID=_mirroredSectionID;
@property(copy, nonatomic) NSString *remoteSectionID; // @synthesize remoteSectionID=_remoteSectionID;
@property(copy, nonatomic) NSString *localSectionID; // @synthesize localSectionID=_localSectionID;
@property(copy, nonatomic) NSString *universalSectionID; // @synthesize universalSectionID=_universalSectionID;
- (void).cxx_destruct;
- (id)description;
- (id)copy;

@end

