//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NACIDSClientDelegate.h"
#import "NACXPCInterface.h"
#import "NSXPCListenerDelegate.h"

@class NACIDSClient, NSMutableDictionary, NSMutableSet, NSObject<OS_dispatch_queue>, NSString, NSXPCListener;

@interface NACXPCServer : NSObject <NSXPCListenerDelegate, NACXPCInterface, NACIDSClientDelegate>
{
    NSMutableDictionary *_volumeRecords;
    NSMutableDictionary *_audioRoutesRecords;
    NSXPCListener *_xpcListener;
    NSMutableSet *_volumeObservers;
    NACIDSClient *_idsClient;
    float _hapticIntensity;
    BOOL _systemMutedState;
    NSObject<OS_dispatch_queue> *_audioAndHapticPreviewQueue;
    BOOL _audioAndHapticPreviewIsPlaying;
}

+ (id)server;
- (void)_loadSystemMutedState;
- (void)_persistSystemMutedState;
- (void)audioAndHapticPreviewHasCompletedPlaying;
- (void)client:(id)arg1 systemMutedStateDidChange:(BOOL)arg2;
- (void)client:(id)arg1 routeObservationCancelledForCategory:(id)arg2;
- (void)clientVolumeObservationCancelled:(id)arg1;
- (void)client:(id)arg1 audioRoutes:(id)arg2 didChangeForCategory:(id)arg3;
- (void)client:(id)arg1 volumeWarningEnabled:(BOOL)arg2 didChangeForCategory:(id)arg3;
- (void)client:(id)arg1 EULimit:(float)arg2 didChangeForCategory:(id)arg3;
- (void)client:(id)arg1 hapticIntensityDidChange:(float)arg2;
- (void)client:(id)arg1 mutedState:(BOOL)arg2 didChangeForCategory:(id)arg3;
- (void)client:(id)arg1 volumeControlAvailable:(BOOL)arg2 didChangeForCategory:(id)arg3;
- (void)client:(id)arg1 volumeValue:(float)arg2 didChangeForCategory:(id)arg3;
- (id)_routeObservationCategoriesForConnection:(id)arg1;
- (void)_persistHapticIntensity;
- (void)_persistVolumeRecords;
- (void)_endObservingAudioRoutesForCategory:(id)arg1 connection:(id)arg2;
- (id)_audioRoutesRecordForCategory:(id)arg1;
- (id)_volumeRecordForCategory:(id)arg1;
- (void)_endObservingVolumeForConnection:(id)arg1;
- (void)_cleanupConnection:(id)arg1;
- (void)_loadHapticIntensity;
- (void)_loadVolumeRecords;
- (void)playAudioAndHapticPreview;
- (void)pickAudioRouteWithIdentifier:(id)arg1 category:(id)arg2;
- (void)endObservingAudioRoutesForCategory:(id)arg1;
- (void)audioRoutesForCategory:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)setSystemMuted:(BOOL)arg1;
- (void)setHapticIntensity:(float)arg1;
- (void)setMuted:(BOOL)arg1 category:(id)arg2;
- (void)setVolumeValue:(float)arg1 category:(id)arg2;
- (void)volumeWarningForCategory:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)EULimitForCategory:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)systemMutedState:(CDUnknownBlockType)arg1;
- (void)hapticIntensity:(CDUnknownBlockType)arg1;
- (void)mutedStateForCategory:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)volumeControlAvailabilityForCategory:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)volumeValueForCategory:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)beginObservingAudioRoutesForCategory:(id)arg1;
- (void)endObservingVolume;
- (void)beginObservingVolume;
- (BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void).cxx_destruct;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

