//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSAttributedString, PUICQuickboardViewController;

@protocol PUICQuickboardViewControllerDelegate <NSObject>
- (void)quickboardInputCancelled:(PUICQuickboardViewController *)arg1;
- (void)quickboard:(PUICQuickboardViewController *)arg1 textEntered:(NSAttributedString *)arg2;

@optional
- (void)quickboardDictationButtonTappedInCompanionSimulator:(PUICQuickboardViewController *)arg1;
- (void)quickboardEmojiButtonTappedInCompanionSimulator:(PUICQuickboardViewController *)arg1;
- (double)quickboard:(PUICQuickboardViewController *)arg1 selectionFrameOriginYInDestinationView:(id *)arg2;
@end

