//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PepperUICore/PUICQuickboardViewController.h>

#import "PUICTableViewDataSource.h"
#import "PUICTableViewDelegate.h"

@class NSMutableArray, NSString, PUICQuickboardListItemCell, PUICTableView, RadiosPreferences, UIButton, UIView;

@interface PUICQuickboardListViewController : PUICQuickboardViewController <PUICTableViewDelegate, PUICTableViewDataSource>
{
    PUICTableView *_tableView;
    UIView *_trayView;
    double _shadowImageHeight;
    UIButton *_dictationButton;
    RadiosPreferences *_radiosPreferences;
    NSMutableArray *_cachedHeights;
    NSMutableArray *_dismissedItemViews;
    PUICQuickboardListItemCell *_selectedCell;
}

@property(retain, nonatomic) PUICQuickboardListItemCell *selectedCell; // @synthesize selectedCell=_selectedCell;
- (void).cxx_destruct;
- (void)dismissView:(id)arg1 toPositionY:(double)arg2 delayFactor:(unsigned long long)arg3;
- (void)addDismissalAnimations;
- (void)finishDismissalWithOptions:(unsigned long long)arg1;
- (void)addPresentationAnimations;
- (void)addContentViewAnimations:(_Bool)arg1;
- (double)animationDuration;
- (void)dictationButtonTapped:(id)arg1;
- (double)trayViewHiddenFrameOriginY;
- (double)trayViewVisibleFrameOriginY;
- (id)dictationButton;
- (void)setupTrayView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)setDismissMode:(unsigned long long)arg1;
- (void)setConfirmSend:(_Bool)arg1;
- (double)cachedHeightForListItem:(long long)arg1 width:(double)arg2;
- (void)setupListView;
- (id)listView;
- (id)additionalTrayButtons;
- (void)didDeselectListItem:(long long)arg1;
- (void)didSelectListItem:(long long)arg1;
- (id)cellForListItem:(long long)arg1;
- (double)heightForListItem:(long long)arg1 width:(double)arg2;
- (long long)numberOfListItems;
- (void)contentSizeCategoryDidChange:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithDelegate:(id)arg1 dictationMode:(long long)arg2;
- (id)initWithDelegate:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

