//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIStatusBarServerClient.h"

@class PUICStatusView, UILabel, UIStatusBarServer;

@interface PUICStatusBarGlobalContextView : UIView <UIStatusBarServerClient>
{
    UILabel *_time;
    PUICStatusView *_statusView;
    _Bool _animatingTime;
    _Bool _tookAssertion;
    _Bool _inForeground;
    _Bool _currentDataIsStale;
    UIStatusBarServer *_statusBarServer;
}

@property(nonatomic) _Bool currentDataIsStale; // @synthesize currentDataIsStale=_currentDataIsStale;
@property(nonatomic) _Bool inForeground; // @synthesize inForeground=_inForeground;
@property(retain, nonatomic) UIStatusBarServer *statusBarServer; // @synthesize statusBarServer=_statusBarServer;
- (void).cxx_destruct;
- (void)setTimeHidden:(_Bool)arg1 duration:(double)arg2 animation:(unsigned long long)arg3 completion:(CDUnknownBlockType)arg4;
- (void)setTimeHidden:(_Bool)arg1 animation:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setTimeHidden:(_Bool)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_adjustActiveIconIfNeededForData:(const CDStruct_1f4d094c *)arg1 animated:(_Bool)arg2;
- (void)_updateTime:(id)arg1;
- (void)statusBarServer:(id)arg1 didReceiveDoubleHeightStatusString:(id)arg2 forStyle:(long long)arg3;
- (void)statusBarServer:(id)arg1 didReceiveGlowAnimationState:(_Bool)arg2 forStyle:(long long)arg3;
- (void)statusBarServer:(id)arg1 didReceiveStyleOverrides:(int)arg2;
- (void)statusBarServer:(id)arg1 didReceiveStatusBarData:(const CDStruct_1f4d094c *)arg2 withActions:(int)arg3;
- (void)_updateWithStatusBarData:(const CDStruct_1f4d094c *)arg1;
- (void)_updateStatusBarServerRegistration;
- (void)_didEnterBackground:(id)arg1;
- (void)_willEnterForeground:(id)arg1;
- (void)didMoveToSuperview;
- (void)_releaseVisibleAssertion;
- (void)_takeVisibleAssertion;
- (void)willMoveToSuperview:(id)arg1;
- (void)setHidden:(_Bool)arg1;
- (void)layoutSubviews;
- (void)setNeedsLayout;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

