//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, PUICButton, UIColor;

@interface PUICSideBySideButtonsView : UIView
{
    PUICButton *_leftButton;
    PUICButton *_rightButton;
    _Bool _shouldCalculateFontSize;
    _Bool _primaryButtonEnabled;
    _Bool _secondaryButtonEnabled;
    NSString *_primaryButtonTitle;
    NSString *_secondaryButtonTitle;
    CDUnknownBlockType _primaryActionBlock;
    CDUnknownBlockType _secondaryActionBlock;
    long long _style;
    unsigned long long _controlEvents;
    UIColor *_primaryColor;
    double _primaryButtonPlatterAlpha;
}

+ (void)_setupSideBySideButtonsSpec;
@property(nonatomic) double primaryButtonPlatterAlpha; // @synthesize primaryButtonPlatterAlpha=_primaryButtonPlatterAlpha;
@property(retain, nonatomic) UIColor *primaryColor; // @synthesize primaryColor=_primaryColor;
@property(nonatomic) unsigned long long controlEvents; // @synthesize controlEvents=_controlEvents;
@property(nonatomic) long long style; // @synthesize style=_style;
@property(nonatomic, getter=isSecondaryButtonEnabled) _Bool secondaryButtonEnabled; // @synthesize secondaryButtonEnabled=_secondaryButtonEnabled;
@property(nonatomic, getter=isPrimaryButtonEnabled) _Bool primaryButtonEnabled; // @synthesize primaryButtonEnabled=_primaryButtonEnabled;
@property(copy, nonatomic) CDUnknownBlockType secondaryActionBlock; // @synthesize secondaryActionBlock=_secondaryActionBlock;
@property(copy, nonatomic) CDUnknownBlockType primaryActionBlock; // @synthesize primaryActionBlock=_primaryActionBlock;
@property(copy, nonatomic) NSString *secondaryButtonTitle; // @synthesize secondaryButtonTitle=_secondaryButtonTitle;
@property(copy, nonatomic) NSString *primaryButtonTitle; // @synthesize primaryButtonTitle=_primaryButtonTitle;
- (void).cxx_destruct;
- (void)_adjustFontSizeFittingPrimaryLabel:(id)arg1 secondaryLabel:(id)arg2 inSize:(struct CGSize)arg3;
- (id)_primaryAppColor;
- (id)_defaultBackgroundColor;
- (id)_defaultTextColor;
- (void)_secondaryButtonAction:(id)arg1;
- (void)_primaryButtonAction:(id)arg1;
- (void)layoutSubviews;
- (struct CGSize)intrinsicContentSize;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

