//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PUICCrownInputSequencer, PUICCrownInputSequencerDetent;

@protocol PUICCrownInputSequencerDelegate <NSObject>

@optional
- (_Bool)crownInputSequencer:(PUICCrownInputSequencer *)arg1 shouldPlayHapticForDetent:(PUICCrownInputSequencerDetent *)arg2;
- (_Bool)crownInputSequencer:(PUICCrownInputSequencer *)arg1 shouldRubberBandAtBoundary:(long long)arg2;
- (void)crownInputSequencerOffsetDidChange:(PUICCrownInputSequencer *)arg1;
- (void)crownInputSequencerIdleDidChange:(PUICCrownInputSequencer *)arg1;
- (void)crownInputSequencerActiveDetentDidChange:(PUICCrownInputSequencer *)arg1;
- (void)crownInputSequencer:(PUICCrownInputSequencer *)arg1 offsetDidReachBoundary:(long long)arg2;
@end

