//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoPassKitUI/NPKPassFieldView.h>

@interface NPKBoardingPassFieldView : NPKPassFieldView
{
    float _innerValueMargin;
    float _innerLabelMargin;
    float _auxiliaryLabelHeight;
}

@property(nonatomic) float innerLabelMargin; // @synthesize innerLabelMargin=_innerLabelMargin;
@property(nonatomic) float innerValueMargin; // @synthesize innerValueMargin=_innerValueMargin;
- (BOOL)overrideValueParagraphStyle;
- (BOOL)overrideLabelParagraphStyle;
@property(readonly, nonatomic) struct CGPoint labelOrigin;
@property(nonatomic) float auxiliaryLabelHeight; // @synthesize auxiliaryLabelHeight=_auxiliaryLabelHeight;
- (float)_valueHeightForAvailableWidth:(float)arg1;
- (float)_labelHeightForAvailableWidth:(float)arg1;
- (void)_updateLabelLabel;
- (BOOL)hasLabel;
- (BOOL)fitsHalfWidth;
- (id)initWithField:(id)arg1 maxWidth:(float)arg2;
- (void)layoutSubviews;
- (BOOL)hasValue;

@end

