//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewLayoutAttributes.h"

@interface NPKCollectionViewLayoutAttributes : UICollectionViewLayoutAttributes
{
    BOOL _forceShowFullPass;
    BOOL _useRasterizedPass;
}

@property(nonatomic) BOOL forceShowFullPass; // @synthesize forceShowFullPass=_forceShowFullPass;
@property(nonatomic) BOOL useRasterizedPass; // @synthesize useRasterizedPass=_useRasterizedPass;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

