//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoPassKitUI/NPKPassView.h>

@class PUICActionController, PUICActionGroup, PUICActionItem, UIImageView, UILabel, UIView;

@interface NPKPaymentPassView : NPKPassView
{
    BOOL _shrink;
    BOOL _orbEnabled;
    UILabel *_cardNameLabel;
    UIView *_cardView;
    UIImageView *_backgroundCardArtView;
    UILabel *_fpanLabel;
    PUICActionController *_actionController;
    PUICActionGroup *_actionGroup;
    PUICActionItem *_deleteActionItem;
}

+ (struct CGSize)_sizePreservingAspectRatioForCardArt:(id)arg1 givenMaxConstraints:(struct CGSize)arg2;
+ (float)shrunkenCardHeight;
+ (float)cardHeight;
- (BOOL)canProvideActionController;
@property(retain, nonatomic) PUICActionController *actionController; // @synthesize actionController=_actionController;
@property(retain, nonatomic) PUICActionGroup *actionGroup; // @synthesize actionGroup=_actionGroup;
@property(retain, nonatomic) UILabel *cardNameLabel; // @synthesize cardNameLabel=_cardNameLabel;
@property(nonatomic) BOOL shrink; // @synthesize shrink=_shrink;
@property(retain, nonatomic) PUICActionItem *deleteActionItem; // @synthesize deleteActionItem=_deleteActionItem;
- (void)_deletePass;
@property(retain, nonatomic) UILabel *fpanLabel; // @synthesize fpanLabel=_fpanLabel;
@property(retain, nonatomic) UIImageView *backgroundCardArtView; // @synthesize backgroundCardArtView=_backgroundCardArtView;
@property(retain, nonatomic) UIView *cardView; // @synthesize cardView=_cardView;
- (BOOL)showFullPass;
- (void)updateUI;
@property(nonatomic, getter=isOrbEnabled) BOOL orbEnabled; // @synthesize orbEnabled=_orbEnabled;
- (void).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

