//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NPKPassView;

@protocol NPKPassViewDelegate <NSObject>
- (void)passViewNeedsResetState:(NPKPassView *)arg1;
- (void)passView:(NPKPassView *)arg1 hideStatusBar:(BOOL)arg2 animated:(BOOL)arg3;
- (void)passView:(NPKPassView *)arg1 didUpdateHeight:(float)arg2;
@end

