//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, PKDiff, PKPass;

@interface NPKPassDetailView : UIView
{
    float _width;
    NSArray *_primaryFieldViews;
    NSArray *_secondaryFieldViews;
    NSArray *_auxiliaryFieldViews;
    NSArray *_separatorViews;
    BOOL _shouldShowTopLine;
    PKPass *_pass;
    PKDiff *_diff;
}

+ (id)detailViewForPass:(id)arg1 diff:(id)arg2 width:(float)arg3;
- (id)labelColor;
@property(readonly, nonatomic) PKPass *pass; // @synthesize pass=_pass;
@property(nonatomic) BOOL shouldShowTopLine; // @synthesize shouldShowTopLine=_shouldShowTopLine;
- (id)auxiliaryFieldViews;
- (id)secondaryFieldViews;
- (id)primaryFieldViews;
- (BOOL)labelOnTopForPrimaryFields;
- (id)attributesForPrimaryValues;
- (id)attributesForPrimaryLabels;
- (id)_newVerticalSeparatorViewWithHeight:(float)arg1 startingY:(float)arg2;
- (float)_layoutFlexiblePassFieldViews:(id)arg1 startingY:(float)arg2 separators:(id)arg3;
- (BOOL)shouldArrangeSecondaryFieldsAfterAuxiliary;
- (id)_newHorizontalSeparatorViewAtY:(float)arg1;
- (void)setupPrimaryFieldViews;
- (id)_newSeparatorView;
- (Class)primaryFieldViewClass;
- (unsigned int)maxAuxiliaryFields;
- (unsigned int)maxSecondaryFields;
- (unsigned int)maxPrimaryFields;
- (void)_layoutFieldViews;
- (void)_createFieldViews;
- (id)initWithPass:(id)arg1 diff:(id)arg2 width:(float)arg3;
@property(readonly, nonatomic) PKDiff *diff; // @synthesize diff=_diff;
- (void).cxx_destruct;
- (id)foregroundColor;
- (id)highlightColor;
- (float)width;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

