//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NPKPaymentReadyDotsView, UILabel;

@interface NPKPaymentReadyView : UIView
{
    UILabel *_readyLabel;
    NPKPaymentReadyDotsView *_dotsView;
    UIView *_containerView;
}

@property(retain, nonatomic) NPKPaymentReadyDotsView *dotsView; // @synthesize dotsView=_dotsView;
@property(retain, nonatomic) UILabel *readyLabel; // @synthesize readyLabel=_readyLabel;
- (void).cxx_destruct;
@property(nonatomic, getter=isAnimating) BOOL animating;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

