//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "NPKQuickPaymentStatusViewAnimationCoordinatorDelegate.h"
#import "UIScrollViewDelegate.h"

@class NPKPaymentReadyView, NPKPaymentStatusView, NPKQuickPaymentStatusViewAnimationCoordinator, NSArray, NSString, PUICPageIndicatorView, UIImageView, UILabel, UIScrollView;

@interface NPKQuickPaymentView : UIView <UIScrollViewDelegate, NPKQuickPaymentStatusViewAnimationCoordinatorDelegate>
{
    BOOL _ready;
    id <NPKQuickPaymentViewDelegate> _delegate;
    id <NPKQuickPaymentViewDataSource> _dataSource;
    NSArray *_passUniqueIDs;
    UIView *_topContainerView;
    UIView *_bottomContainerView;
    UIView *_topClippingView;
    UIView *_bottomClippingView;
    NPKPaymentReadyView *_readyView;
    UILabel *_unavailableTopLabel;
    UILabel *_needsVerificationTopLabel;
    UILabel *_doneTopLabel;
    UILabel *_internalOnlyIssueTopLabel;
    UILabel *_activationFailureLabel;
    UILabel *_instructionLabel;
    NPKPaymentStatusView *_notPersonalizedStatusView;
    UIImageView *_checkmarkView;
    UILabel *_internalOnlyIssueBottomLabel;
    NSArray *_passViews;
    NSString *_selectedUniqueID;
    UIScrollView *_passScrollView;
    PUICPageIndicatorView *_pageIndicatorView;
    NPKQuickPaymentStatusViewAnimationCoordinator *_animationCoordinator;
    struct CGRect _topContainerViewFrame;
    struct CGRect _bottomContainerViewFrame;
}

@property(retain, nonatomic) NPKQuickPaymentStatusViewAnimationCoordinator *animationCoordinator; // @synthesize animationCoordinator=_animationCoordinator;
@property(nonatomic, getter=isReady) BOOL ready; // @synthesize ready=_ready;
@property(retain, nonatomic) UIView *bottomContainerView; // @synthesize bottomContainerView=_bottomContainerView;
@property(retain, nonatomic) UIView *topContainerView; // @synthesize topContainerView=_topContainerView;
- (void)setFailedForAuthRandomIssue;
- (void)setDone;
- (void)setNotPersonalizedForUniqueIdentifier:(id)arg1 animated:(BOOL)arg2;
- (void)setReadyForUniqueIdentifier:(id)arg1 animated:(BOOL)arg2;
- (void)setNotReadyForUniqueIdentifier:(id)arg1 animated:(BOOL)arg2;
@property(retain, nonatomic) NSArray *passUniqueIDs; // @synthesize passUniqueIDs=_passUniqueIDs;
- (void)animationCoordinator:(id)arg1 didStartHidingTopView:(id)arg2 bottomView:(id)arg3;
- (void)animationCoordinator:(id)arg1 didFinishPresentingTopView:(id)arg2 bottomView:(id)arg3;
- (struct CGRect)animationCoordinator:(id)arg1 frameForBottomViewWhenOnscreen:(BOOL)arg2;
- (struct CGRect)animationCoordinator:(id)arg1 frameForTopViewWhenOnscreen:(BOOL)arg2;
@property(nonatomic) struct CGRect bottomContainerViewFrame; // @synthesize bottomContainerViewFrame=_bottomContainerViewFrame;
@property(nonatomic) struct CGRect topContainerViewFrame; // @synthesize topContainerViewFrame=_topContainerViewFrame;
- (void)_updateViewsForScrolling;
- (BOOL)_isSelectingPass;
@property(retain, nonatomic) NSString *selectedUniqueID; // @synthesize selectedUniqueID=_selectedUniqueID;
- (unsigned int)_indexForUniqueID:(id)arg1;
- (void)_selectPassDidEnd;
- (void)_selectPassDidStart;
- (void)setFailed;
- (id)_topViewForPaymentApplication:(id)arg1;
- (void)_updateViewsForUserInteraction:(BOOL)arg1;
- (BOOL)_updateScrollViewOffsetForUniqueID:(id)arg1;
- (id)_passUniqueIDAtIndex:(unsigned int)arg1;
- (unsigned int)_currentIndex;
@property(retain, nonatomic) UILabel *internalOnlyIssueBottomLabel; // @synthesize internalOnlyIssueBottomLabel=_internalOnlyIssueBottomLabel;
@property(retain, nonatomic) NPKPaymentStatusView *notPersonalizedStatusView; // @synthesize notPersonalizedStatusView=_notPersonalizedStatusView;
@property(retain, nonatomic) UILabel *activationFailureLabel; // @synthesize activationFailureLabel=_activationFailureLabel;
@property(retain, nonatomic) UILabel *instructionLabel; // @synthesize instructionLabel=_instructionLabel;
@property(retain, nonatomic) UIView *bottomClippingView; // @synthesize bottomClippingView=_bottomClippingView;
@property(retain, nonatomic) PUICPageIndicatorView *pageIndicatorView; // @synthesize pageIndicatorView=_pageIndicatorView;
@property(retain, nonatomic) NSArray *passViews; // @synthesize passViews=_passViews;
- (void)_setContentOffsetForScrollView:(id)arg1 forPassWithUniqueID:(id)arg2;
@property(retain, nonatomic) UIScrollView *passScrollView; // @synthesize passScrollView=_passScrollView;
@property(retain, nonatomic) UILabel *internalOnlyIssueTopLabel; // @synthesize internalOnlyIssueTopLabel=_internalOnlyIssueTopLabel;
@property(retain, nonatomic) UILabel *needsVerificationTopLabel; // @synthesize needsVerificationTopLabel=_needsVerificationTopLabel;
@property(retain, nonatomic) UILabel *unavailableTopLabel; // @synthesize unavailableTopLabel=_unavailableTopLabel;
@property(retain, nonatomic) NPKPaymentReadyView *readyView; // @synthesize readyView=_readyView;
@property(retain, nonatomic) UILabel *doneTopLabel; // @synthesize doneTopLabel=_doneTopLabel;
@property(retain, nonatomic) UIView *topClippingView; // @synthesize topClippingView=_topClippingView;
@property(retain, nonatomic) UIImageView *checkmarkView; // @synthesize checkmarkView=_checkmarkView;
- (void).cxx_destruct;
@property(nonatomic) __weak id <NPKQuickPaymentViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <NPKQuickPaymentViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

