//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoPassKitUI/NPKPassView.h>

@class NPKPassDescription, NPKPassDetailView, NPKPassHeaderView, NPKUIAssertion, UIImageView, UILabel, UIView;

@interface NPKStandardPassView : NPKPassView
{
    BOOL _showNotificationNub;
    BOOL _addBufferAtBottomOfPass;
    BOOL _useBarcodeBackground;
    UIImageView *_backgroundView;
    UIImageView *_eventTicketBackgroundView;
    UIImageView *_logoImageView;
    UILabel *_logoTextLabel;
    NPKPassHeaderView *_headerView;
    NPKPassDetailView *_passDetailView;
    UIImageView *_footerImageView;
    UIImageView *_barcodeView;
    UIView *_barcodeBackground;
    UILabel *_expiredTextView;
    NPKUIAssertion *_barcodeAssertion;
}

+ (id)stretchableBackgroundImageWithColor:(id)arg1;
+ (id)stretchableBackgroundImageWithColor:(id)arg1 nubColor:(id)arg2;
- (void)setPass:(id)arg1;
- (BOOL)handleTapAtPoint:(struct CGPoint)arg1 andScrollWithBehavior:(int *)arg2 toOffset:(struct CGPoint *)arg3;
- (void)passContentScrollingBegan;
- (void)passContentScrollingAnimationEndedWithOffset:(struct CGPoint)arg1;
- (void)passContentScrolledToOffset:(struct CGPoint *)arg1 animated:(BOOL)arg2;
@property(nonatomic) BOOL addBufferAtBottomOfPass; // @synthesize addBufferAtBottomOfPass=_addBufferAtBottomOfPass;
@property(nonatomic) BOOL showNotificationNub; // @synthesize showNotificationNub=_showNotificationNub;
@property(nonatomic) BOOL useBarcodeBackground; // @synthesize useBarcodeBackground=_useBarcodeBackground;
@property(retain, nonatomic) UIImageView *eventTicketBackgroundView; // @synthesize eventTicketBackgroundView=_eventTicketBackgroundView;
- (void)setDiff:(id)arg1;
@property(readonly) float barcodeYOffset;
- (id)_resizedBarcode:(id)arg1 desiredSize:(struct CGSize)arg2;
@property(retain, nonatomic) UILabel *expiredTextView; // @synthesize expiredTextView=_expiredTextView;
@property(retain, nonatomic) NPKPassDetailView *passDetailView; // @synthesize passDetailView=_passDetailView;
- (void)_loadPassDetailView;
- (void)_removeEventTicketBackground;
- (void)_addEventTicketBackground;
- (void)_setBorderVisible:(BOOL)arg1 animated:(BOOL)arg2;
@property(retain, nonatomic) NPKUIAssertion *barcodeAssertion; // @synthesize barcodeAssertion=_barcodeAssertion;
- (void)setUseBarcodeBackground:(BOOL)arg1 animated:(BOOL)arg2;
- (void)updateUI;
@property(retain, nonatomic) UIView *barcodeBackground; // @synthesize barcodeBackground=_barcodeBackground;
@property(retain, nonatomic) UIImageView *barcodeView; // @synthesize barcodeView=_barcodeView;
@property(retain, nonatomic) UIImageView *footerImageView; // @synthesize footerImageView=_footerImageView;
@property(retain, nonatomic) UILabel *logoTextLabel; // @synthesize logoTextLabel=_logoTextLabel;
@property(retain, nonatomic) UIImageView *logoImageView; // @synthesize logoImageView=_logoImageView;
- (void).cxx_destruct;
@property(retain, nonatomic) NPKPassHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) UIImageView *backgroundView; // @synthesize backgroundView=_backgroundView;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(retain, nonatomic) NPKPassDescription *passDescription;

@end

