//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface CSLUIComplicationView : UIView
{
    UIView *_backgroundView;
    UIView *_foregroundView;
    BOOL _allJigglyLike;
    float _flippedPercentage;
    BOOL _trackingPosition;
    id <CSLUIComplicationViewDelegate> _delegate;
    int _state;
}

+ (struct CGRect)defaultFrame;
+ (id)complicationView;
+ (id)jitterTransformAnimation;
+ (id)jitterPositionAnimation;
+ (struct CGPoint)iconOffset;
- (struct CGPoint)_iconCenter;
- (void)setComplicationAlpha:(float)arg1;
- (void)setGettingJiggy:(BOOL)arg1;
- (void)beginTrackingPosition;
- (void)setState:(int)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void).cxx_destruct;
- (BOOL)isAccessibilityElement;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
@property(readonly, nonatomic) int state; // @synthesize state=_state;
@property(nonatomic) __weak id <CSLUIComplicationViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)layoutSubviews;

@end

