//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ComplicationUI/CSLUIComplicationView.h>

@interface CSLUIComplicationArcView : CSLUIComplicationView
{
}

+ (void)endRed:(float *)arg1 green:(float *)arg2 blue:(float *)arg3;
+ (void)startRed:(float *)arg1 green:(float *)arg2 blue:(float *)arg3;
+ (id)icon;
+ (float)startPosition;
- (void)setPercentageFull:(float)arg1 animated:(BOOL)arg2;
- (id)arcView;
- (id)iconView;
- (void)setIcon:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

