//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PUICActionSheetControllerDelegate.h"

@class NMUAirPlayActionController, NSString;

@interface NMUAudioRoutePickerController : NSObject <PUICActionSheetControllerDelegate>
{
    CDUnknownBlockType _completionHandler;
    NMUAirPlayActionController *_airPlayActionController;
}

+ (void)presentRoutePickerIfNecessaryFromViewController:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
+ (void)_deregisterRoutePickerController:(id)arg1;
+ (id)_registeredRoutePickerControllers;
+ (void)_registerRoutePickerController:(id)arg1;
- (void)actionSheetController:(id)arg1 didDismissWithActionAtIndexPath:(id)arg2;
- (id)_initWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

