//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "NMUMarqueeViewDelegate.h"

@class NMUMarqueeView, NSArray, NSString, UIColor, UIFont, UILabel;

@interface NMUNowPlayingTitlesView : UIView <NMUMarqueeViewDelegate>
{
    NMUMarqueeView *_titleMarqueeView;
    NMUMarqueeView *_detailMarqueeView;
    UILabel *_titleLabel;
    UILabel *_detailLabel;
    BOOL _needsLabelUpdate;
    float _secondLineLeading;
    BOOL _lendingContainerViews;
    BOOL _explicit;
    int _style;
    NSString *_titleText;
    NSString *_albumText;
    NSString *_artistText;
    NSString *_stationNameText;
    float _textMargin;
    int _textAlignment;
    NSArray *_firstLineFields;
    UIFont *_firstLineFont;
    UIColor *_firstLineColor;
    NSArray *_secondLineFields;
    UIFont *_secondLineFont;
    UIColor *_secondLineColor;
}

@property(copy, nonatomic) NSString *titleText; // @synthesize titleText=_titleText;
@property(copy, nonatomic) UIColor *secondLineColor; // @synthesize secondLineColor=_secondLineColor;
@property(copy, nonatomic) UIFont *secondLineFont; // @synthesize secondLineFont=_secondLineFont;
@property(copy, nonatomic) NSArray *secondLineFields; // @synthesize secondLineFields=_secondLineFields;
@property(copy, nonatomic) UIColor *firstLineColor; // @synthesize firstLineColor=_firstLineColor;
@property(copy, nonatomic) UIFont *firstLineFont; // @synthesize firstLineFont=_firstLineFont;
@property(copy, nonatomic) NSArray *firstLineFields; // @synthesize firstLineFields=_firstLineFields;
@property(nonatomic) float textMargin; // @synthesize textMargin=_textMargin;
@property(nonatomic, getter=isExplicit) BOOL explicit; // @synthesize explicit=_explicit;
@property(copy, nonatomic) NSString *stationNameText; // @synthesize stationNameText=_stationNameText;
@property(copy, nonatomic) NSString *artistText; // @synthesize artistText=_artistText;
@property(copy, nonatomic) NSString *albumText; // @synthesize albumText=_albumText;
- (id)lastLineContainerView;
- (id)firstLineContainerView;
- (void)setLendingContainerViews:(BOOL)arg1;
- (void)resetMarqueePositions;
@property(readonly, nonatomic, getter=hasMarqueeStartedAnimating) BOOL marqueeStartedAnimating;
- (void)pauseMarqueeAfterCompletingCurrentIteration;
@property(nonatomic, getter=isMarqueePaused) BOOL marqueePaused;
- (id)_defaultSecondLineFields;
- (id)_defaultFirstLineFields;
- (id)_nowPlayingTextForFields:(id)arg1;
@property(readonly, nonatomic) float firstLineBaselineOffsetFromBoundsTop;
@property(nonatomic) float secondLineLeading;
- (void)marqueeViewDidEndMarqueeIteration:(id)arg1 finished:(BOOL)arg2;
- (void).cxx_destruct;
- (id)initWithStyle:(int)arg1;
@property(nonatomic) int textAlignment; // @synthesize textAlignment=_textAlignment;
@property(nonatomic) int style; // @synthesize style=_style;
- (void)_updateStyle;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_setNeedsLabelUpdate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

