//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PUICActionSheetController.h"

#import "PUICActionSheetControllerDelegate.h"

@class NSString, PUICActionSheetItem, UIViewController, _NMUPlaybackSourceActionControllerHeaderView;

@interface NMUPlaybackSourceActionController : PUICActionSheetController <PUICActionSheetControllerDelegate>
{
    PUICActionSheetItem *_localPlaybackSourceItem;
    PUICActionSheetItem *_remotePlaybackSourceItem;
    _NMUPlaybackSourceActionControllerHeaderView *_headerView;
    UIViewController *_rememberedPresentingViewController;
}

- (id)initWithActionGroup:(id)arg1;
@property(retain, nonatomic) UIViewController *rememberedPresentingViewController; // @synthesize rememberedPresentingViewController=_rememberedPresentingViewController;
- (void)_updatePlaybackSourceItemsForCurrentSource;
- (void)_remotePlaybackSourceItemSelected;
- (void)_localPlaybackSourceItemSelected;
- (void).cxx_destruct;
@property(readonly, nonatomic) _NMUPlaybackSourceActionControllerHeaderView *headerView; // @synthesize headerView=_headerView;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

