//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NMUTheme : NSObject
{
}

+ (id)touchHighlightImageWithSourceImage:(id)arg1;
+ (id)processedArtworkImageWithSourceImage:(id)arg1 destinationSize:(struct CGSize)arg2 unprocessedImageScale:(float)arg3;
+ (id)artworkViewPlaceholderBackgroundColor;
+ (id)nowPlayingNoteImage;
+ (id)actionSheetBookmarkImageWithSelection:(BOOL)arg1;
+ (id)actionSheetDislikeImage;
+ (id)actionSheetLikeImage;
+ (id)orbPlayAllImage;
+ (id)orbRepeatModeImage;
+ (id)orbShuffleModeImage;
+ (id)orbAirPlayImage;
+ (id)volumeControlsDownImage;
+ (id)volumeControlsUpImage;
+ (id)transportControlsSkipImageWithTimeInterval:(double)arg1;
+ (id)transportControlsHamburgerImage;
+ (id)transportControlsLikeBanImageWithTintColor:(id)arg1 selection:(BOOL)arg2;
+ (id)transportControlsRewindImage;
+ (id)transportControlsForwardImage;
+ (id)transportControlsStopImage;
+ (id)transportControlsPauseImage;
+ (id)transportControlsPlayImage;
+ (id)progressStringForElapsedTime:(double)arg1;
+ (id)screenEdgeVignetteImage;
+ (id)_imageNamed:(id)arg1 inBundle:(id)arg2 useVariant:(BOOL)arg3 shouldCache:(BOOL)arg4;
+ (id)_cachedObjectForKey:(id)arg1 withCreationBlock:(CDUnknownBlockType)arg2;
+ (id)_transportControlsLikeBanImage;
+ (id)_cachedImageNamed:(id)arg1 useVariant:(BOOL)arg2;
+ (id)orbNowPlayingImage;
+ (id)orbPlaybackSourceRemoteImage;
+ (id)orbPlaybackSourceLocalImage;

@end

