//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NMUDefaultTouchHighlightProvider, NSArray, NSMutableDictionary, _NMUTransportControlButton;

@interface NMUTransportControlsView : UIView
{
    NSMutableDictionary *_availableControlByGroup;
    _NMUTransportControlButton *_leftButton;
    _NMUTransportControlButton *_middleButton;
    _NMUTransportControlButton *_rightButton;
    BOOL _showIsPlaying;
    BOOL _alwaysLive;
    BOOL _burgerModeEnabled;
    BOOL _enabled;
    id <NMUTransportControlsViewDelegate> _delegate;
    NSArray *_availableControls;
    NMUDefaultTouchHighlightProvider *_defaultTouchHighlightProvider;
    id <NMUTransportControlsTouchHighlightProvider> _customTouchHighlightProvider;
    double _displayedSkipForwardInterval;
    double _displayedSkipBackwardInterval;
}

+ (id)defaultTransportControls;
@property(nonatomic) __weak id <NMUTransportControlsTouchHighlightProvider> customTouchHighlightProvider; // @synthesize customTouchHighlightProvider=_customTouchHighlightProvider;
@property(nonatomic, getter=isBurgerModeEnabled) BOOL burgerModeEnabled; // @synthesize burgerModeEnabled=_burgerModeEnabled;
@property(nonatomic) BOOL showIsPlaying; // @synthesize showIsPlaying=_showIsPlaying;
@property(copy, nonatomic) NSArray *availableControls; // @synthesize availableControls=_availableControls;
- (void)_updateTransportControlHighlightedStates;
- (void)_updateMiddleButtonProperties;
- (id)_availableControlForGroup:(int)arg1;
- (void)_transportControlTap:(id)arg1;
- (void)_updateTransportControlButtons;
- (void)_updateButtonTouchHighlightProviders;
- (id)_createTransportButton;
@property(nonatomic) double displayedSkipForwardInterval; // @synthesize displayedSkipForwardInterval=_displayedSkipForwardInterval;
@property(nonatomic) double displayedSkipBackwardInterval; // @synthesize displayedSkipBackwardInterval=_displayedSkipBackwardInterval;
@property(readonly, nonatomic) NMUDefaultTouchHighlightProvider *defaultTouchHighlightProvider; // @synthesize defaultTouchHighlightProvider=_defaultTouchHighlightProvider;
@property(nonatomic, getter=isAlwaysLive) BOOL alwaysLive; // @synthesize alwaysLive=_alwaysLive;
- (void).cxx_destruct;
@property(nonatomic, getter=isEnabled) BOOL enabled; // @synthesize enabled=_enabled;
@property(nonatomic) __weak id <NMUTransportControlsViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

