//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PUICActionContentController.h"

@interface PUICActionContentController (NMUPlaybackSourceActionController_PrivateAccess)

// Remaining properties
@property(readonly, nonatomic) float cancelButtonHeight; // @dynamic cancelButtonHeight;
@property(readonly, nonatomic) float cancelButtonTopInset; // @dynamic cancelButtonTopInset;
@end

