//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL, PKPaymentWebServiceContext;

@protocol NPKCompanionServerProtocol <NSObject>
- (void)sharedPaymentWebServiceContextWithCompletion:(void (^)(PKPaymentWebServiceContext *))arg1;
- (void)setSharedPaymentWebServiceContext:(PKPaymentWebServiceContext *)arg1 completion:(void (^)(void))arg2;
- (void)handlePendingiCloudSignoutWithCompletion:(void (^)(void))arg1;
- (void)handlePendingUnpairingWithCompletion:(void (^)(void))arg1;
- (void)redownloadAllPaymentPassesWithCompletion:(void (^)(void))arg1;
- (void)initiateConsistencyCheckWithCompletion:(void (^)(void))arg1;
- (void)defaultCard:(void (^)(NSString *))arg1;
- (void)setDefaultCard:(NSString *)arg1 completion:(void (^)(BOOL))arg2;
- (void)removePaymentPassWithUniqueID:(NSString *)arg1 completion:(void (^)(BOOL))arg2;
- (void)savePaymentPassAtURL:(NSURL *)arg1 withUniqueID:(NSString *)arg2 completion:(void (^)(BOOL))arg3;
- (void)paymentPassWithUniqueID:(NSString *)arg1 reply:(void (^)(PKPaymentPass *))arg2;
- (void)paymentPassUniqueIDs:(void (^)(NSSet *))arg1;
@end

