//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSMutableSet, NSObject<OS_dispatch_queue>, NSXPCConnection;

@interface NPKCompanionAgentConnection : NSObject
{
    NSXPCConnection *_xpcConnection;
    NSObject<OS_dispatch_queue> *_xpcConnectionQueue;
    NSObject<OS_dispatch_queue> *_cacheQueue;
    NSMutableSet *_cachedUniqueIDs;
    NSMutableDictionary *_cachedPasses;
}

- (id)sharedPaymentWebServiceContext;
- (void)setSharedPaymentWebServiceContext:(id)arg1;
- (void)_sharedPaymentWebServiceContextWithCompletion:(CDUnknownBlockType)arg1;
- (CDUnknownBlockType)_errorHandlerWithCompletion:(CDUnknownBlockType)arg1;
- (void)consistencyCheckWithCompletion:(CDUnknownBlockType)arg1;
- (void)defaultCardUniqueID:(CDUnknownBlockType)arg1;
- (void)setDefaultCardUniqueID:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)savePaymentPass:(id)arg1 completion:(CDUnknownBlockType)arg2;
@property(retain) NSMutableDictionary *cachedPasses; // @synthesize cachedPasses=_cachedPasses;
- (void)_applyDataAccessorToPass:(id)arg1;
@property(retain) NSMutableSet *cachedUniqueIDs; // @synthesize cachedUniqueIDs=_cachedUniqueIDs;
- (void)_removePassWithUniqueIDFromCache:(id)arg1;
- (void)_addPassToCache:(id)arg1;
- (id)_cachedPassForUniqueID:(id)arg1;
- (void)_setCachedUniqueIDs:(id)arg1;
- (id)_cachedUniqueIDs;
- (void)_handleDefaultCardChanged:(id)arg1;
- (void)_handleServerPaymentPassesChanged:(id)arg1;
- (void)handlePendingiCloudSignoutWithCompletion:(CDUnknownBlockType)arg1;
- (void)handlePendingUnpairingWithCompletion:(CDUnknownBlockType)arg1;
- (void)redownloadAllPaymentPassesWithCompletion:(CDUnknownBlockType)arg1;
- (void)removePaymentPassWithUniqueID:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)paymentPassWithUniqueID:(id)arg1 reply:(CDUnknownBlockType)arg2;
- (void)paymentPassUniqueIDs:(CDUnknownBlockType)arg1;
- (id)_remoteObjectProxyWithFailureHandler:(CDUnknownBlockType)arg1;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;
- (void)_clearCaches;
@property(readonly) NSXPCConnection *xpcConnection;

@end

