//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@interface NPKProtoSecureElementSetNewAuthRandomResponse : PBCodable <NSCopying>
{
    BOOL _pending;
    BOOL _success;
    CDStruct_5ee4970e _has;
}

@property(nonatomic) BOOL hasSuccess;
@property(nonatomic) BOOL success; // @synthesize success=_success;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)mergeFrom:(id)arg1;
@property(nonatomic) BOOL pending; // @synthesize pending=_pending;
@property(nonatomic) BOOL hasPending;
- (id)dictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;

@end

