//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PKPass.h"

@class NSData;

@interface PKPass (NanoPassKit)
@property(readonly) BOOL hasLogoImageSet;
@property(readonly) NSData *npkCompleteHash;
@property(readonly) BOOL npkExpired;
@property(readonly) BOOL npkHasBarcode;
@end

