//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSLocking.h"

@class NSObject<OS_dispatch_semaphore>, NSString;

@interface NMSPersistentDictionary : NSObject <NSLocking>
{
    Class _objectClass;
    NSString *_path;
    struct __CFString *_loggingFacility;
    NSObject<OS_dispatch_semaphore> *_lock;
    struct sqlite3 *_db;
    struct sqlite3_stmt *_fetch;
    struct sqlite3_stmt *_insert;
    struct sqlite3_stmt *_reset;
    struct sqlite3_stmt *_remove;
    struct sqlite3_stmt *_removeAll;
    struct sqlite3_stmt *_byDate;
}

- (void)_openDBForceRecreate:(BOOL)arg1;
- (void)enumerateObjectsSortedByExpirationDate:(CDUnknownBlockType)arg1;
- (void)resetObject:(id)arg1 forKey:(id)arg2;
- (void)setObject:(id)arg1 forKey:(id)arg2 expires:(id)arg3;
- (id)_objectFromData:(id)arg1;
- (id)_dataFromObject:(id)arg1;
- (id)initWithPath:(id)arg1 objectClass:(Class)arg2 loggingFacility:(struct __CFString *)arg3;
- (void).cxx_destruct;
- (void)unlock;
- (void)lock;
- (void)removeObjectForKey:(id)arg1;
- (void)removeAllObjects;
- (id)init;
- (void)dealloc;
- (id)objectForKey:(id)arg1;

@end

