//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AWDServerConnection;

@interface SYMetricLogger : NSObject
{
    AWDServerConnection *_connection;
}

+ (id)sharedInstance;
- (void)postFullSyncDuration:(double)arg1 onMaster:(BOOL)arg2 forService:(id)arg3;
- (void)postSequenceErrorOfType:(int)arg1 sequenceNumber:(unsigned long long)arg2 forService:(id)arg3;
- (void)postReceiptOfMessage:(id)arg1 forService:(id)arg2;
- (void).cxx_destruct;
- (id)init;

@end

