//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SPLogs : NSObject
{
}

+ (void)setDebugLogLevel:(id)arg1;
+ (_Bool)debugLogLevel;
+ (int)fileLoggingLevel;
+ (_Bool)watchLogging;
+ (void)setupLoggingForDomain:(id)arg1;
+ (void)setupLoggingLevelForDomain:(id)arg1;

@end

