//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol CSLEcoModeDaemonXPCDelegate <NSObject>
- (void)xpcObliterateSettings:(void (^)(void))arg1;
- (void)xpcSetUtcOffset:(int)arg1;
- (void)xpcSetDeviceRotatedUp:(BOOL)arg1;
- (void)xpcSet24hMode:(BOOL)arg1;
- (void)xpcSetInfo24hMode:(BOOL)arg1 deviceRotatedUp:(BOOL)arg2 utcOffset:(int)arg3 completion:(void (^)(NSError *))arg4;
- (void)xpcSetEcoMode:(BOOL)arg1 thermalTrap:(BOOL)arg2 completion:(void (^)(NSError *))arg3;
@end

