//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLSBacklightXPCClient.h"

@class NSMutableDictionary, NSPointerArray, NSString, NSXPCConnection;

@interface CSLSBacklight : NSObject <CSLSBacklightXPCClient>
{
    NSPointerArray *_observers;
    NSPointerArray *_observersNeedingInitialState;
    NSXPCConnection *_connection;
    int _currentBacklightState;
    NSMutableDictionary *_assertionsDictionary;
    NSMutableDictionary *_brightnessAssertionsDictionary;
}

+ (id)sharedInstance;
- (void)backlightDidChange:(id)arg1 from:(int)arg2 to:(int)arg3;
- (void)_releaseAssertion:(id)arg1;
- (void)_takeAssertion:(id)arg1;
- (void)_tickleAssertionTimeout:(id)arg1;
- (void)_releaseMinimumBrightnessAssertion:(id)arg1;
- (void)_takeMinimumBrightnessAssertion:(id)arg1;
- (void)assertionTimedOut:(id)arg1;
- (void)setCurrentBacklightState:(int)arg1 forDisplayType:(id)arg2;
- (void)_dropConnection;
- (id)_createConnectionIfNecessary;
- (void)addObserver:(id)arg1;
- (void).cxx_destruct;
- (void)removeObserver:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)_attemptReconnect;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

