//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@class NSString;

@interface CSLSSiriLaunchOptions : NSObject <NSSecureCoding, NSCopying>
{
    BOOL _makeFrontmost;
    NSString *_bundleIdentifier;
    NSString *_defaultPNGName;
}

+ (BOOL)supportsSecureCoding;
@property(copy, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(nonatomic) BOOL makeFrontmost; // @synthesize makeFrontmost=_makeFrontmost;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *defaultPNGName; // @synthesize defaultPNGName=_defaultPNGName;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

