//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLSConnectionStatusObserver.h"

@class NSDate, NSString, NSXPCConnection, _CSLSConnectionStatusObservers;

@interface CSLSConnectionStatusService : NSObject <CSLSConnectionStatusObserver>
{
    unsigned int _status;
    NSDate *_lastConnectedDate;
    NSXPCConnection *_connection;
    _CSLSConnectionStatusObservers *_observers;
}

+ (id)sharedInstance;
- (void)connectionStatusDidChange:(unsigned int)arg1 lastConnection:(id)arg2;
@property(readonly, nonatomic) NSDate *lastConnectedDate; // @synthesize lastConnectedDate=_lastConnectedDate;
- (void)_informObserversOfChangeInStatus:(unsigned int)arg1 lastConnection:(id)arg2;
- (void)addObserver:(id)arg1;
@property(retain, nonatomic) _CSLSConnectionStatusObservers *observers; // @synthesize observers=_observers;
@property(nonatomic) unsigned int status; // @synthesize status=_status;
@property(retain, nonatomic) NSXPCConnection *connection; // @synthesize connection=_connection;
- (void).cxx_destruct;
- (void)removeObserver:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

