//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol CSLSBacklightXPCServer <NSObject>
- (void)releaseMinimumBrightnessAssertion:(NSString *)arg1;
- (void)takeMinimumBrightnessAssertion:(NSString *)arg1 withMinimumNits:(float)arg2 withDisplay:(NSString *)arg3;
- (void)releaseAssertionReason:(NSString *)arg1;
- (void)tickleAssertionTimeout:(NSString *)arg1;
- (void)takeAssertion:(NSString *)arg1 withReason:(NSString *)arg2 withDisplay:(NSString *)arg3 willPreventDim:(_Bool)arg4 willPreventScreenOff:(_Bool)arg5 willPreventGestures:(_Bool)arg6 timeoutSeconds:(double)arg7;
- (void)connect;
@end

