//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLOnWristClientExportedInterface.h"

@class NSString, NSXPCConnection;

@interface CSLSOnWristMonitor : NSObject <CSLOnWristClientExportedInterface>
{
    CDUnknownBlockType _changeHandler;
    NSXPCConnection *_connection;
}

@property(copy, nonatomic) CDUnknownBlockType changeHandler; // @synthesize changeHandler=_changeHandler;
- (void)onWristStateChanged:(int)arg1;
- (void)requestWristDetectionDisabledStatusWithCompletion:(CDUnknownBlockType)arg1;
- (void)forceOnWristUpdate;
@property(retain, nonatomic) NSXPCConnection *connection; // @synthesize connection=_connection;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;
- (void)getWristState:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

