//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol CSLSBacklightObserver <NSObject>
- (void)backlightDidChange:(NSString *)arg1 from:(int)arg2 to:(int)arg3;
@end

