//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CSLSDeviceOrientation : NSObject
{
    BOOL _isInverted;
    unsigned int _wristOrientation;
}

+ (id)sharedDeviceOrientation;
- (void)_synchronizePreferences;
- (unsigned int)wristOrientation;
- (void)setInverted:(BOOL)arg1 animated:(BOOL)arg2;
- (void)_updateWristOrientation;
- (void)_updateInvertedValue;
- (BOOL)isInverted;
- (id)_init;
- (void)dealloc;

@end

