//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@class NSData, NSString;

@interface _NMRCommandOptionsProtobuf : PBCodable <NSCopying>
{
    double _playbackPosition;
    long long _radioStationID;
    unsigned long long _trackID;
    NSString *_destinationAppDisplayID;
    NSString *_mediaType;
    float _playbackRate;
    NSString *_radioStationHash;
    float _rating;
    int _repeatMode;
    unsigned int _sendOptions;
    int _shuffleMode;
    float _skipInterval;
    NSString *_sourceID;
    NSData *_systemAppPlaybackQueueData;
    BOOL _externalPlayerCommand;
    BOOL _negative;
    BOOL _requestDefermentToPlaybackQueuePosition;
    struct {
        unsigned int playbackPosition:1;
        unsigned int radioStationID:1;
        unsigned int trackID:1;
        unsigned int playbackRate:1;
        unsigned int rating:1;
        unsigned int repeatMode:1;
        unsigned int sendOptions:1;
        unsigned int shuffleMode:1;
        unsigned int skipInterval:1;
        unsigned int externalPlayerCommand:1;
        unsigned int negative:1;
        unsigned int requestDefermentToPlaybackQueuePosition:1;
    } _has;
}

@property(nonatomic) unsigned long long trackID; // @synthesize trackID=_trackID;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)mergeFrom:(id)arg1;
@property(retain, nonatomic) NSString *mediaType; // @synthesize mediaType=_mediaType;
@property(retain, nonatomic) NSString *radioStationHash; // @synthesize radioStationHash=_radioStationHash;
@property(nonatomic) BOOL hasRequestDefermentToPlaybackQueuePosition;
@property(nonatomic) BOOL requestDefermentToPlaybackQueuePosition; // @synthesize requestDefermentToPlaybackQueuePosition=_requestDefermentToPlaybackQueuePosition;
@property(nonatomic) BOOL hasSendOptions;
@property(nonatomic) unsigned int sendOptions; // @synthesize sendOptions=_sendOptions;
@property(readonly, nonatomic) BOOL hasDestinationAppDisplayID;
@property(readonly, nonatomic) BOOL hasSystemAppPlaybackQueueData;
@property(readonly, nonatomic) BOOL hasRadioStationHash;
@property(nonatomic) BOOL hasRadioStationID;
@property(nonatomic) long long radioStationID; // @synthesize radioStationID=_radioStationID;
@property(nonatomic) BOOL hasTrackID;
@property(nonatomic) BOOL hasPlaybackPosition;
@property(nonatomic) double playbackPosition; // @synthesize playbackPosition=_playbackPosition;
@property(nonatomic) BOOL hasNegative;
@property(nonatomic) BOOL negative; // @synthesize negative=_negative;
@property(nonatomic) BOOL hasRating;
@property(nonatomic) BOOL hasPlaybackRate;
@property(nonatomic) BOOL hasSkipInterval;
@property(nonatomic) float skipInterval; // @synthesize skipInterval=_skipInterval;
@property(nonatomic) BOOL hasExternalPlayerCommand;
@property(nonatomic) BOOL externalPlayerCommand; // @synthesize externalPlayerCommand=_externalPlayerCommand;
@property(readonly, nonatomic) BOOL hasSourceID;
@property(retain, nonatomic) NSString *destinationAppDisplayID; // @synthesize destinationAppDisplayID=_destinationAppDisplayID;
@property(retain, nonatomic) NSData *systemAppPlaybackQueueData; // @synthesize systemAppPlaybackQueueData=_systemAppPlaybackQueueData;
@property(nonatomic) BOOL hasShuffleMode;
@property(nonatomic) BOOL hasRepeatMode;
@property(readonly, nonatomic) BOOL hasMediaType;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
@property(nonatomic) int shuffleMode; // @synthesize shuffleMode=_shuffleMode;
@property(nonatomic) float rating; // @synthesize rating=_rating;
@property(nonatomic) float playbackRate; // @synthesize playbackRate=_playbackRate;
@property(nonatomic) int repeatMode; // @synthesize repeatMode=_repeatMode;
@property(retain, nonatomic) NSString *sourceID; // @synthesize sourceID=_sourceID;

@end

