//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@class NSData;

@interface _NMRMediaRemoteSetArtworkMessage : PBCodable <NSCopying>
{
    double _timestamp;
    NSData *_jpegData;
    NSData *_originalDigest;
    CDStruct_b5306035 _has;
}

- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)mergeFrom:(id)arg1;
@property(retain, nonatomic) NSData *originalDigest; // @synthesize originalDigest=_originalDigest;
@property(retain, nonatomic) NSData *jpegData; // @synthesize jpegData=_jpegData;
@property(readonly, nonatomic) BOOL hasOriginalDigest;
@property(readonly, nonatomic) BOOL hasJpegData;
@property(nonatomic) BOOL hasTimestamp;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(nonatomic) double timestamp; // @synthesize timestamp=_timestamp;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;

@end

