//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IDSServiceDelegate.h"

@class IDSService, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface NMRIDSMessageCenter : NSObject <IDSServiceDelegate>
{
    NSObject<OS_dispatch_queue> *_idsQueue;
    IDSService *_idsService;
    NSMutableDictionary *_messageHandlers;
    id <NMRIDSMessageCenterDelegate> _delegate;
}

- (BOOL)sendMessageWithProtobufData:(id)arg1 messageType:(unsigned short)arg2 priority:(unsigned int)arg3 timeout:(double)arg4 bypassDuet:(BOOL)arg5 skipStorage:(BOOL)arg6 inReplyTo:(id)arg7 resultingMessageIdentifier:(id *)arg8 error:(id *)arg9;
- (BOOL)sendMessageWithProtobufData:(id)arg1 messageType:(unsigned short)arg2 priority:(unsigned int)arg3 timeout:(double)arg4 bypassDuet:(BOOL)arg5 skipStorage:(BOOL)arg6 expectReply:(BOOL)arg7 queueOneIdentifier:(id)arg8 resultingMessageIdentifier:(id *)arg9 error:(id *)arg10;
- (void)startHandlingMessages;
- (void)setMessageHandlerTarget:(id)arg1 action:(SEL)arg2 forIncomingMessagesOfType:(unsigned short)arg3;
- (BOOL)_sendMessageWithProtobufData:(id)arg1 messageType:(unsigned short)arg2 priority:(unsigned int)arg3 timeout:(double)arg4 bypassDuet:(BOOL)arg5 skipStorage:(BOOL)arg6 isResponse:(BOOL)arg7 additionalOptions:(id)arg8 resultingMessageIdentifier:(id *)arg9 error:(id *)arg10;
- (void)service:(id)arg1 account:(id)arg2 identifier:(id)arg3 didSendWithSuccess:(BOOL)arg4 error:(id)arg5;
- (void)service:(id)arg1 account:(id)arg2 incomingUnhandledProtobuf:(id)arg3 fromID:(id)arg4 context:(id)arg5;
- (void).cxx_destruct;
@property(nonatomic) __weak id <NMRIDSMessageCenterDelegate> delegate; // @synthesize delegate=_delegate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

