//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NMRMediaRemoteProtobufCodable.h"

@class NSDate, NSString, _NMRMediaRemoteGetArtworkMessage;

@interface NMRMediaRemoteGetArtworkMessage : NSObject <NMRMediaRemoteProtobufCodable>
{
    _NMRMediaRemoteGetArtworkMessage *_protobuf;
}

@property(readonly, nonatomic) NSDate *serializationDate;
- (id)protobufData;
- (id)initWithProtobufData:(id)arg1;
- (void).cxx_destruct;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

