//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MPAVRoutingControllerDelegate.h"

@class MPAVRoutingController, NMCVirtualAudioRoute, NSArray, NSMutableArray, NSMutableDictionary, NSString;

@interface NMCAudioRoutingManager : NSObject <MPAVRoutingControllerDelegate>
{
    NSMutableDictionary *_pairedBluetoothDevices;
    MPAVRoutingController *_routingController;
    NSArray *_systemAudioRoutes;
    NSMutableArray *_virtualAudioRoutes;
    BOOL _pendingVirtualRouteChangeNotification;
    BOOL _pendingPairedBluetoothAudioDeviceChangeNotification;
    BOOL _pendingSystemAudioRoutesChangedNotification;
    BOOL _speakerRouteEnabled;
    BOOL _bluetoothAvailableAndEnabled;
}

+ (id)sharedManager;
@property(nonatomic, getter=isBluetoothAvailableAndEnabled) BOOL bluetoothAvailableAndEnabled; // @synthesize bluetoothAvailableAndEnabled=_bluetoothAvailableAndEnabled;
@property(readonly, copy, nonatomic) NSArray *systemAudioRoutes;
@property(readonly, copy, nonatomic) NSArray *pairedBluetoothAudioDevices;
- (id)_createOrUpdateVirtualAudioRouteForBluetoothAudioDevice:(id)arg1;
- (void)_postPairedBluetoothAudioDevicesChangedNotification;
- (void)_removeBluetoothDevice:(id)arg1;
- (void)_addBluetoothDevice:(id)arg1;
- (void)_handleBluetoothAvailabilityChange;
- (void)_bluetoothConnectionStatusChangedNotification:(id)arg1;
- (void)_bluetoothDeviceDisconnectFailedNotification:(id)arg1;
- (void)_bluetoothDeviceDisconnectSuccessNotification:(id)arg1;
- (void)_bluetoothDeviceConnectFailedNotification:(id)arg1;
- (void)_bluetoothDeviceConnectSuccessNotification:(id)arg1;
- (void)_bluetoothDeviceUnpairedNotification:(id)arg1;
- (void)_bluetoothDeviceRemovedNotification:(id)arg1;
- (void)_bluetoothDeviceDiscoveredNotification:(id)arg1;
- (void)_bluetoothPowerChangedNotification:(id)arg1;
- (void)_bluetoothAvailabilityChangedNotification:(id)arg1;
- (void)_postSystemAudioRoutesChangedNotification;
- (void)_removeVirtualAudioRoute:(id)arg1;
- (id)_createOrUpdateVirtualAudioRouteForMPAVRoute:(id)arg1;
- (id)_existingVirtualAudioRouteForBluetoothAudioDevice:(id)arg1;
- (void)_addVirtualAudioRoute:(id)arg1;
- (id)_existingVirtualAudioRouteForMPAVRoute:(id)arg1;
- (void)_removeVirtualAudioRouteAtIndex:(unsigned int)arg1;
- (void)_postVirtualAudioRoutesChangedNotification;
- (unsigned int)_indexOfVirtualAudioRoute:(id)arg1 forInsertion:(BOOL)arg2;
- (void)_updateSystemAudioRoutesWithRoutes:(id)arg1;
- (void)_refreshBluetoothDevices;
- (void)_registerForBluetoothManagerNotifications;
- (void)_updateSpeakerRouteEnabled;
@property(readonly, copy, nonatomic) NSArray *virtualAudioRoutes;
- (void)pickVirtualAudioRoute:(id)arg1;
@property(readonly, nonatomic) NMCVirtualAudioRoute *pickedVirtualAudioRoute;
@property(readonly, nonatomic) BOOL hasPickedVirtualAudioRoute;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;
- (void)routingController:(id)arg1 didFailToPickRouteWithError:(id)arg2;
- (void)routingControllerAvailableRoutesDidChange:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

