//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NMCPlaybackController;

@interface NMCMediaRemoteCommandController : NSObject
{
    NMCPlaybackController *_playbackController;
}

+ (id)sharedController;
- (void)_appDefaultsDidChangeNotification;
- (void)beginRespondingToMediaRemoteCommands;
- (void)_nowPlayingItemDidChangeNotification:(id)arg1;
- (int)_handleChangePlaybackPositionCommand:(id)arg1;
- (void)_updateChangeShuffleModeCommand;
- (int)_handleChangeShuffleModeCommand:(id)arg1;
- (void)_updateChangeRepeatModeCommand;
- (int)_handleChangeRepeatModeCommand:(id)arg1;
- (int)_handleAdvanceRepeatModeCommand:(id)arg1;
- (int)_handleAdvanceShuffleModeCommand:(id)arg1;
- (int)_handleSpecialSeekBackwardCommand:(id)arg1;
- (int)_handleSpecialSeekForwardCommand:(id)arg1;
- (int)_handleChangePlaybackRateCommand:(id)arg1;
- (int)_handleSkipBackwardCommand:(id)arg1;
- (int)_handleSkipForwardCommand:(id)arg1;
- (int)_handleSeekBackwardCommand:(id)arg1;
- (int)_handleSeekForwardCommand:(id)arg1;
- (int)_handlePreviousTrackCommand:(id)arg1;
- (int)_handleNextTrackCommand:(id)arg1;
- (int)_handleTogglePlayPauseCommand:(id)arg1;
- (int)_handleStopCommand:(id)arg1;
- (int)_handlePlayCommand:(id)arg1;
- (int)_handlePauseCommand:(id)arg1;
- (void)_unregisterAllCommands;
- (void)_updateSupportedCommandsForItem:(id)arg1;
- (id)_playbackController;
- (void)_registerPrivateCommands;
- (void)_registerPublicCommands;
- (void)stopRespondingToMediaRemoteCommands;
- (void)_unregisterMediaRemoteCallbacks;
- (void)_unregisterPlayerNotifications;
- (void)_registerMediaRemoteCallbacks;
- (void)_registerPlayerNotifications;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end

