//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MPMediaQueryNowPlayingItem.h"

@interface NMCQueryNowPlayingItem : MPMediaQueryNowPlayingItem
{
}

+ (void)applyVolumeNormalizationForQueuedItems:(id)arg1;
- (id)_newTimeMarkersForChapterType:(int)arg1;
- (void)setupPlaybackInfo;
- (BOOL)supportsRewindAndFastForward15Seconds;
- (int)customAVEQPreset;
- (BOOL)hasDisplayableText;
- (float)defaultPlaybackRate;
- (id)initWithPlayerItem:(id)arg1;

@end

