//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <SockPuppetSiriSupport/SPSiriViewController.h>

#import "PUICTableViewDataSource.h"
#import "PUICTableViewDelegate.h"

@class NSArray, NSNumberFormatter, NSString, PUICTableView, STShowDailyWeatherForecastRequest;

@interface SPSiriDailyWeatherViewController : SPSiriViewController <PUICTableViewDataSource, PUICTableViewDelegate>
{
    STShowDailyWeatherForecastRequest *_siriData;
    PUICTableView *_tableView;
    NSArray *_weekdays;
    NSNumberFormatter *_numberFormatter;
}

@property(retain, nonatomic) NSArray *weekdays; // @synthesize weekdays=_weekdays;
- (id)_separatorForCell:(id)arg1;
- (id)_loTemperatureFromIndex:(int)arg1;
- (id)_hiTemperatureFromIndex:(int)arg1;
- (void)_alignView:(id)arg1 inCell:(id)arg2 withAlignment:(unsigned int)arg3 atXInset:(float)arg4;
- (id)_weekdayFromIndex:(int)arg1;
- (void)_tableView:(id)arg1 setCellSize:(id)arg2;
- (id)_temperatureFromValue:(id)arg1;
- (void)_setupNumberFormatter;
- (void)_setupWeekdays;
- (void)_dumpSiriObject;
- (id)_attributionImageAtY:(float)arg1;
- (id)_cityName;
@property(retain, nonatomic) STShowDailyWeatherForecastRequest *siriData; // @synthesize siriData=_siriData;
- (id)initWithSiriObject:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) PUICTableView *tableView; // @synthesize tableView=_tableView;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
@property(retain, nonatomic) NSNumberFormatter *numberFormatter; // @synthesize numberFormatter=_numberFormatter;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

