//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface WKInterfaceController : NSObject
{
    NSArray *_topLevelObjects;
    NSString *_viewControllerID;
    struct CGRect _contentFrame;
}

+ (struct CGRect)screenBounds;
+ (double)screenScale;
@property(retain, nonatomic) NSString *viewControllerID; // @synthesize viewControllerID=_viewControllerID;
@property(retain, nonatomic) NSArray *topLevelObjects; // @synthesize topLevelObjects=_topLevelObjects;
@property(nonatomic) struct CGRect contentFrame; // @synthesize contentFrame=_contentFrame;
- (void).cxx_destruct;
- (void)updateUserActivity:(id)arg1 userInfo:(id)arg2;
- (void)clearAllMenuItems;
- (void)addMenuItemWithItemIcon:(long long)arg1 title:(id)arg2 action:(SEL)arg3;
- (void)addMenuItemWithImageNamed:(id)arg1 title:(id)arg2 action:(SEL)arg3;
- (void)addMenuItemWithImage:(id)arg1 title:(id)arg2 action:(SEL)arg3;
- (id)contextsForSegueWithIdentifier:(id)arg1 inTable:(id)arg2 rowIndex:(long long)arg3;
- (id)contextsForSegueWithIdentifier:(id)arg1;
- (id)contextForSegueWithIdentifier:(id)arg1 inTable:(id)arg2 rowIndex:(long long)arg3;
- (id)contextForSegueWithIdentifier:(id)arg1;
- (void)dismissTextInputController;
- (void)presentTextInputControllerWithSuggestions:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dismissController;
- (void)presentControllerWithNames:(id)arg1 contexts:(id)arg2;
- (void)presentControllerWithName:(id)arg1 context:(id)arg2;
- (void)becomeCurrentPage;
- (void)popToRootController;
- (void)popController;
- (void)pushControllerWithName:(id)arg1 context:(id)arg2;
- (void)setTitle:(id)arg1;
- (id)actionForUserActivity:(id)arg1 context:(id *)arg2;
- (void)handleActionWithIdentifier:(id)arg1 forLocalNotification:(id)arg2;
- (void)handleActionWithIdentifier:(id)arg1 forRemoteNotification:(id)arg2;
- (void)table:(id)arg1 didSelectRowAtIndex:(long long)arg2;
- (void)didDeactivate;
- (void)willActivate;
- (id)initWithContext:(id)arg1;
- (void)_setContentFrame:(struct CGRect)arg1;

@end

