//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSString;

@protocol PUUnlockServer <NSObject>
- (void)getRemoteDeviceState;
- (void)setUnlockEnabled:(_Bool)arg1;
- (void)didCompletePasscodeAction:(_Bool)arg1 error:(NSError *)arg2;
- (void)requestRemoteDeviceUnlockNotification;
- (void)requestRemoteDevicePasscodeAction:(long long)arg1;
- (void)disableOnlyRemoteUnlock;
- (void)enableOnlyRemoteUnlockWithPasscode:(NSString *)arg1;
- (void)unpairForUnlock;
- (void)pairForUnlockWithPasscode:(NSString *)arg1;
- (void)checkIn;
@end

