//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>, NSObject<OS_xpc_object>;

@interface HLConnection : NSObject
{
    NSObject<OS_xpc_object> *_connection;
    NSObject<OS_dispatch_queue> *_eventQueue;
    NSMutableDictionary *_messageHandlers;
    CDUnknownBlockType _disconnectionHandler;
    CDUnknownBlockType _interruptionHandler;
    CDUnknownBlockType _destructionHandler;
}

- (void)setDestructionHandler:(CDUnknownBlockType)arg1;
- (_Bool)_sendMessage:(id)arg1 withReplyHandler:(CDUnknownBlockType)arg2;
- (void)handleInterruption;
- (void)deferredDelete;
- (void)initializeConnection;
- (const char *)getName;
- (id)initWithServiceName:(const char *)arg1 andQueue:(id)arg2;
- (int)getRemotePid;
- (id)getID;
- (void)setDisconnectionHandler:(CDUnknownBlockType)arg1;
- (id)initWithConnection:(id)arg1 andQueue:(id)arg2;
- (_Bool)sendMessage:(id)arg1;
- (_Bool)sendMessage:(id)arg1 withReplyHandler:(CDUnknownBlockType)arg2;
- (void)setHandlerForMessage:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)setInterruptionHandler:(CDUnknownBlockType)arg1;
- (void).cxx_destruct;
- (void)dealloc;
- (void)handleMessage:(id)arg1;
- (void)handleDisconnection;

@end

