//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HLConnection, NSLock, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>;

@interface HLHeartRateManager : NSObject
{
    HLConnection *_clientConnection;
    NSObject<OS_dispatch_queue> *_clientQueue;
    struct __IOHIDEventSystemClient *_hidSystemClient;
    BOOL _registerdForHIDEvents;
    NSObject<OS_dispatch_queue> *_heartRateEventsQueue;
    unsigned int _clientMode;
    BOOL _clientOpportunistic;
    NSLock *_hlClientLock;
    NSObject<OS_dispatch_source> *_spotCheckTimer;
    BOOL _opportunisticMode;
    NSObject<OS_dispatch_queue> *_heartRateDataHandlerQueue;
    CDUnknownBlockType _heartRateDataHandler;
    unsigned int _userActivitySession;
    CDUnknownBlockType _userActivitySessionChangedHandler;
    unsigned int _heartRateOptions;
    double _heartRateInterval;
}

@property(copy) CDUnknownBlockType userActivitySessionChangedHandler; // @synthesize userActivitySessionChangedHandler=_userActivitySessionChangedHandler;
@property(readonly) unsigned int userActivitySession; // @synthesize userActivitySession=_userActivitySession;
@property(nonatomic) BOOL opportunisticMode; // @synthesize opportunisticMode=_opportunisticMode;
@property(copy) CDUnknownBlockType heartRateDataHandler; // @synthesize heartRateDataHandler=_heartRateDataHandler;
@property(retain) NSObject<OS_dispatch_queue> *heartRateDataHandlerQueue; // @synthesize heartRateDataHandlerQueue=_heartRateDataHandlerQueue;
- (id)attachedClientInfo;
- (void)dispatchHeartRateData:(id)arg1;
- (void)setUserWorkoutActivitySession:(unsigned int)arg1;
- (BOOL)startPeriodicHeartRateUpdatesWithInterval:(double)arg1 withOptions:(unsigned int)arg2;
- (BOOL)startStreamingHeartRateUpdatesWithOptions:(unsigned int)arg1;
- (void)unregisterHeartRateHIDEvents;
@property double heartRateInterval; // @synthesize heartRateInterval=_heartRateInterval;
@property unsigned int heartRateOptions; // @synthesize heartRateOptions=_heartRateOptions;
- (void)registerHeartRateHIDEvents;
- (void)setUserActivitySession;
- (BOOL)startHeartRateUpdates;
- (void)getRemoteUserActivitySession;
- (BOOL)setupHIDClient;
- (void)handleIncomingDispatchedHeartRateData:(id)arg1;
- (void)notifyUserActivitySessionChanged:(id)arg1;
- (void)handleServerInterruption;
- (void)handleServerDisconnection;
- (void)heartRateEventOccurred:(struct __IOHIDEvent *)arg1;
- (BOOL)stopHeartRateUpdates;
- (BOOL)startSpotCheckHeartRateUpdateWithOptions:(unsigned int)arg1;
- (void).cxx_destruct;
- (id)init;

@end

