//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CDAttribute, CDSession, HLConnectionServer, HLHeartRateBucketer, NSDate, NSLock, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>, NSString;

@interface HLHeartRateServer : NSObject
{
    NSObject<OS_dispatch_queue> *_serverQueue;
    HLConnectionServer *_serverConnection;
    struct __IOHIDEventSystemClient *_primaryHidSystemClient;
    struct __IOHIDEventSystemClient *_lutetiumControlHidSystemClient;
    struct __IOHIDServiceClient *_platinumHIDServiceClient;
    struct __IOHIDServiceClient *_osmiumHIDServiceClient;
    struct __IOHIDServiceClient *_lutetiumHIDServiceClient;
    NSObject<OS_dispatch_queue> *_serverMgmtQueue;
    NSObject<OS_dispatch_queue> *_deviceControlQueue;
    NSObject<OS_dispatch_queue> *_hidEventsQueue;
    NSMutableDictionary *_clients;
    unsigned int _serverHRMode;
    NSLock *_hrControlLock;
    NSLock *_hidClientLock;
    BOOL _deviceStarted;
    NSObject<OS_dispatch_source> *_hrStreamingTimer;
    BOOL _hrStreamingWaitingForHighConfidence;
    double _hrStreamingStartTimestamp;
    NSObject<OS_dispatch_source> *_hrPeriodicTimer;
    NSObject<OS_dispatch_source> *_hrSpotCheckTimer;
    double _hrPeriodicInterval;
    NSDate *_hrPeriodicLastUpdateTime;
    unsigned int _userActivitySession;
    NSString *_userActivitySessionClient;
    BOOL _ppmNotify;
    CDSession *_cdSession;
    CDAttribute *_cdAttribute;
    unsigned char _scheduleID;
    BOOL _currentlyOnWrist;
    struct {
        unsigned long long lastAttach;
        unsigned long long lastDetach;
    } _wristEventTimestamps;
    HLHeartRateBucketer *_hrBucketer;
    float _minimumHR;
    float _nominalHR;
    float _maximumHR;
    BOOL _heartRateEnabled;
}

+ (id)HLHeartRateServerOnQueue:(id)arg1;
- (void)proximityEventOccurred:(struct __IOHIDEvent *)arg1 forService:(struct __IOHIDServiceClient *)arg2;
- (void)heartRateEventOccurred:(struct __IOHIDEvent *)arg1;
- (void)hidEventSystemReset:(struct __IOHIDEventSystemClient *)arg1;
- (void)hidServiceClientRemoved:(struct __IOHIDServiceClient *)arg1;
- (void)updateHeartRateEnabled;
- (void)devicePowerStatusChanged:(int)arg1;
- (BOOL)releasePowerResource;
- (void)setDeviceSchedule:(unsigned char)arg1;
- (BOOL)requestPowerResource;
- (void)updateWristStats:(BOOL)arg1;
- (BOOL)updateBucketerStats;
- (void)requestHRUpdateForMode:(unsigned int)arg1;
- (void)startDevice;
- (void)sendHeartRateDataToClients:(id)arg1;
- (void)handleHeartRateData:(id)arg1;
- (void)notifyUserActivitySessionChangedToClients;
- (void)handleGetAttachedClientInfo:(id)arg1 fromClient:(id)arg2;
- (void)handleDispatchHeartRateData:(id)arg1 fromClient:(id)arg2;
- (void)handleGetUserActivitySession:(id)arg1 fromClient:(id)arg2;
- (void)handleSetUserActivitySession:(id)arg1 fromClient:(id)arg2;
- (void)handleStopHRUpdateRequest:(id)arg1 fromClient:(id)arg2;
- (void)handleStartSpotCheckHRUpdateRequest:(id)arg1 fromClient:(id)arg2;
- (void)handleStartPeriodicHRUpdateRequest:(id)arg1 fromClient:(id)arg2;
- (void)handleStartStreamingHRUpdateRequest:(id)arg1 fromClient:(id)arg2;
- (void)setPlatinumEnable:(BOOL)arg1;
- (void)setPlatinumScheduleID;
- (void)setOnWrist:(BOOL)arg1;
- (void)setAlgorithmUserActivitySession:(unsigned int)arg1;
- (void)setAlgorithmInterval:(double)arg1;
- (void)pushStatsToPlugin;
- (void)hidServiceClientAdded:(struct __IOHIDServiceClient *)arg1 forHIDSystemClient:(struct __IOHIDEventSystemClient *)arg2;
- (void)setupHIDServicesForSystemClient:(struct __IOHIDEventSystemClient *)arg1;
- (void)updateLoFiReportInterval;
- (void)setAlgorithmMode:(unsigned int)arg1;
- (void)stopDevice;
- (void)handleClientStatusChange;
- (void)handleNewConnection:(id)arg1;
- (void)getPlatinumScheduleID:(char *)arg1;
- (BOOL)setupHIDSystemClients;
- (void)setupBucketer;
- (BOOL)registerPPM;
- (void)handleDisconnection:(id)arg1;
- (BOOL)isHeartRateEnabled;
- (void).cxx_destruct;
- (id)initWithQueue:(id)arg1;
- (void)dealloc;

@end

