//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface _ETHeartRateObserver : NSObject
{
    id <ETHeartRateObserver> _observer;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <ETHeartRateObserver> observer; // @synthesize observer=_observer;

@end

