//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CUISAlertToAlertAnimatedTransitioning.h"

@class CUISAlertViewController, ETPerson, NSString;

@interface ETAlertToAlertAnimator : NSObject <CUISAlertToAlertAnimatedTransitioning>
{
    unsigned int _style;
    CUISAlertViewController *_alert;
    ETPerson *_person;
}

@property(nonatomic) __weak CUISAlertViewController *alert; // @synthesize alert=_alert;
@property(retain, nonatomic) ETPerson *person; // @synthesize person=_person;
- (void).cxx_destruct;
- (id)initWithStyle:(unsigned int)arg1;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

