//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ElectricTouch/ETMessage.h>

@class SKScene;

@interface ETDoodleMessage : ETMessage
{
    SKScene *_targetScene;
    struct deque<ETDoodle *, std::__1::allocator<ETDoodle *>> _doodles;
    struct deque<std::__1::shared_ptr<ETDoodleData>, std::__1::allocator<std::__1::shared_ptr<ETDoodleData>>> _doodleData;
    int _totalPoints;
    double _baseTime;
}

+ (unsigned short)messageType;
- (void)coolOff;
- (void)addStrokeDot:(struct CGPoint)arg1 atTime:(double)arg2;
- (void)addStrokePoint:(struct CGPoint)arg1 atTime:(double)arg2;
- (double)timeDeltaAtIndex:(unsigned int)arg1 strokeIndex:(unsigned int)arg2;
- (struct CGPoint)pointAtIndex:(unsigned int)arg1 strokeIndex:(unsigned int)arg2;
- (unsigned int)pointCountForStrokeIndex:(unsigned int)arg1;
- (void)endCurrentStroke;
- (void)addNoise;
- (void)addDoodleWithColor:(union _GLKVector3)arg1 isPrevisMode:(BOOL)arg2 data:(shared_ptr_4afabb9d *)arg3;
- (void)addPointToLastDoodle:(id)arg1 point:(struct CGPoint)arg2 time:(float)arg3;
- (void)addDoodleWithColor:(union _GLKVector3)arg1 isPrevisMode:(BOOL)arg2;
@property(readonly, nonatomic) unsigned int strokeCount;
- (BOOL)_decodeWithDoodle:(id)arg1;
- (void)preVisualizeInScene:(id)arg1;
- (BOOL)isBelowSizeLimit;
- (id)messageTypeAsString;
- (void)displayInScene:(id)arg1;
- (id)initWithArchiveData:(id)arg1;
- (void).cxx_destruct;
- (id)archiveData;
- (id).cxx_construct;
- (void)cancel;

@end

