//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ETPerson, NSString, UIColor;

@interface ETMessage : NSObject
{
    BOOL _soundPlaybackStarted;
    BOOL _shouldCancelNotificationPlayback;
    BOOL _hapticIsPrewarmed;
    CDUnknownBlockType _soundCompletionHandler;
    BOOL _missedDuringPlayback;
    unsigned int _messageVersion;
    NSString *_identifier;
    ETPerson *_sender;
    UIColor *_color;
    id <ETMessageDelegate> _delegate;
    double _time;
    double _sendTime;
}

+ (double)sendTimeInArchive:(id)arg1;
+ (unsigned short)messageTypeInArchive:(id)arg1;
+ (id)unarchive:(id)arg1;
+ (unsigned short)messageType;
- (id)archive;
@property(nonatomic) BOOL missedDuringPlayback; // @synthesize missedDuringPlayback=_missedDuringPlayback;
@property(readonly, nonatomic) unsigned int messageVersion; // @synthesize messageVersion=_messageVersion;
- (void)_audioServicesDidComplete;
- (void)stopNotificationSoundPlayback;
- (void)startNotificationSoundPlaybackWithSoundCompletion:(CDUnknownBlockType)arg1;
- (BOOL)sendTimeIsValid;
- (void)preVisualizeInScene:(id)arg1;
- (BOOL)isBelowSizeLimit;
- (void)hapticDidUnwarm;
- (void)hapticDidPrewarm;
- (void)playNotificationSound;
- (id)messageTypeAsString;
- (void)displayInScene:(id)arg1;
- (void)soundPlaybackDidComplete:(BOOL)arg1;
- (void)unwarmHaptic;
- (BOOL)shouldCancelNotificationPlayback;
- (void)prewarmHaptic;
- (unsigned long)hapticSoundID;
- (id)initWithArchiveData:(id)arg1;
@property(nonatomic) double sendTime; // @synthesize sendTime=_sendTime;
@property(retain, nonatomic) ETPerson *sender; // @synthesize sender=_sender;
- (void).cxx_destruct;
- (id)archiveData;
@property(nonatomic) double time; // @synthesize time=_time;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(nonatomic) __weak id <ETMessageDelegate> delegate; // @synthesize delegate=_delegate;
- (id)description;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(readonly, nonatomic) unsigned short messageType;
- (void)stopPlaying;

@end

