//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "ETPersonControlsViewDelegate.h"
#import "ETPersonViewTransitioning.h"

@class ETDestinationStatusManager, ETFriendListManager, ETPerson, ETPersonControlsView, ETPersonView, ETPersonWispView, NCABContactAction;

@interface ETPersonViewController : UIViewController <ETPersonControlsViewDelegate, ETPersonViewTransitioning>
{
    ETPersonView *_personView;
    ETPersonWispView *_wispView;
    ETPersonControlsView *_controlsView;
    int _reachabilityStatus;
    ETFriendListManager *_friendList;
    NCABContactAction *_contactAction;
    BOOL _hasUnreadMessages;
    ETPerson *_person;
    ETDestinationStatusManager *_statusManager;
    id <ETPersonViewControllerDelegate> _delegate;
}

@property(retain, nonatomic) ETDestinationStatusManager *statusManager; // @synthesize statusManager=_statusManager;
- (id)initWithPerson:(id)arg1 friendListManager:(id)arg2;
- (float)maxAllowableStatusBarWidth;
- (void)completeAnimatedTransitionAppearing:(BOOL)arg1;
- (void)prepareToAnimateTransitionAppearing:(BOOL)arg1 withSiblingTransitionPersonView:(id)arg2 fromViewController:(id)arg3;
- (void)animateTransitionAppearing:(BOOL)arg1 withSiblingTransitionPersonView:(id)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (id)transitionPersonView;
- (void)etPersonControlsDidPressMessageButton:(id)arg1;
- (void)etPersonControlsDidPressDrawButton:(id)arg1;
- (void)etPersonControlsDidPressPlayButton:(id)arg1;
- (void)etPersonControlsDidPressPhoneButton:(id)arg1;
- (void)_setReachabilityStatus:(int)arg1;
- (void)_presentCanvas;
- (void)_adjustPersonViewToSibling:(id)arg1;
- (void)_updatePlayButton;
- (void)_personUnreadStatusChanged:(id)arg1;
- (void)_reachabilityStatusUpdated:(id)arg1;
- (void)_peopleSourceChanged:(id)arg1;
- (void)_popIfPersonDeleted;
- (void)_updateMessageButton;
- (void)_updatePhoneButton;
- (void)_updateReachability;
- (void)_personViewTapped:(id)arg1;
- (void)_personViewDoubleTapped:(id)arg1;
@property(nonatomic) BOOL hasUnreadMessages; // @synthesize hasUnreadMessages=_hasUnreadMessages;
@property(retain, nonatomic) ETPerson *person; // @synthesize person=_person;
- (void).cxx_destruct;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillLayoutSubviews;
@property(nonatomic) id <ETPersonViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dealloc;

@end

