//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "ETPersonViewTransitioning.h"
#import "PUICCrownInputSequencerDelegate.h"

@class CALayer, ETDestinationStatusManager, ETNoPeopleView, ETPeopleSource, ETPersonView, NSArray, NSMutableArray, NSString, NSTimer, PUICCrownInputSequencer, UIView;

@interface ETPeopleViewController : UIViewController <PUICCrownInputSequencerDelegate, ETPersonViewTransitioning>
{
    UIView *_dialView;
    NSArray *_dialPersonViews;
    NSMutableArray *_dialUnreadIndicatorViews;
    ETPersonView *_centerPersonView;
    ETNoPeopleView *_noPeopleView;
    unsigned int _selectedPersonIndex;
    NSTimer *_personDwellTimer;
    ETPeopleSource *_dataSource;
    PUICCrownInputSequencer *_crownInputSequencer;
    NSMutableArray *_crownOffsetToPersonIndex;
    CALayer *_selectionArrowLayer;
    UIView *_selectionOuterContainerView;
    UIView *_selectionInnerContainerView;
    CALayer *_selectionMaskLayer;
    CALayer *_selectionIndicatorMaskLayer;
    ETDestinationStatusManager *_statusManager;
    id <ETPeopleViewControllerDelegate> _delegate;
}

+ (CDStruct_818bb265)_specValues;
- (void)crownInputSequencerIdleDidChange:(id)arg1;
- (void)crownInputSequencerOffsetDidChange:(id)arg1;
- (void)selectPerson:(id)arg1;
- (void)_hideDialView;
- (void)_personDwellTimerFired:(id)arg1;
- (void)_startPersonDwellTimer;
- (void)_updatePeopleView;
- (void)_setupSelectionContent;
- (void)_updateUnreadIndicators;
- (void)_selectPersonAtIndex:(unsigned int)arg1 animated:(BOOL)arg2;
- (void)_updateSelectionIndicatorAnimated:(BOOL)arg1;
- (void)_updateCrownInputSequencerForSelectedPerson;
- (void)_selectPersonAtIndex:(unsigned int)arg1 includeSelectionIndicator:(BOOL)arg2 animated:(BOOL)arg3;
- (void)reloadPeople;
- (void)_centerPersonViewTapped:(id)arg1;
- (void)_setupDialViewsUsingSupplyBlock:(CDUnknownBlockType)arg1 inRingWithRadius:(float)arg2;
- (struct CGPoint)_positionOnDialAtIndex:(unsigned int)arg1 inRingWithRadius:(float)arg2;
- (void)_stopPersonDwellTimer;
@property(retain, nonatomic) ETDestinationStatusManager *statusManager; // @synthesize statusManager=_statusManager;
- (void)animateOutForButtonWithDuration:(double)arg1;
- (void)animateInForButtonWithDuration:(double)arg1;
- (void)completeAnimatedTransitionAppearing:(BOOL)arg1;
- (void)prepareToAnimateTransitionAppearing:(BOOL)arg1 withSiblingTransitionPersonView:(id)arg2 fromViewController:(id)arg3;
- (void)animateTransitionAppearing:(BOOL)arg1 withSiblingTransitionPersonView:(id)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (id)transitionPersonView;
- (void)_personUnreadStatusChanged:(id)arg1;
- (void)_peopleSourceChanged:(id)arg1;
- (void)_personViewTapped:(id)arg1;
- (void).cxx_destruct;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (BOOL)canBecomeFirstResponder;
- (void)_wheelChangedWithEvent:(id)arg1;
@property(nonatomic) id <ETPeopleViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

