//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface ETPersonWispView : UIView
{
    NSArray *_frames;
    int _style;
    CDStruct_38e0ea09 _sequenceAttributes;
}

+ (id)_frameImagesForSequence:(CDStruct_38e0ea09)arg1;
@property(readonly, nonatomic) CDStruct_38e0ea09 sequenceAttributes; // @synthesize sequenceAttributes=_sequenceAttributes;
- (void)startAnimationWithCompletion:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) NSArray *frames; // @synthesize frames=_frames;
- (void).cxx_destruct;
- (id)initWithStyle:(int)arg1;
@property(readonly, nonatomic) int style; // @synthesize style=_style;

@end

