//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class ETPersonControlsView;

@protocol ETPersonControlsViewDelegate
- (void)etPersonControlsDidPressMessageButton:(ETPersonControlsView *)arg1;
- (void)etPersonControlsDidPressDrawButton:(ETPersonControlsView *)arg1;
- (void)etPersonControlsDidPressPlayButton:(ETPersonControlsView *)arg1;
- (void)etPersonControlsDidPressPhoneButton:(ETPersonControlsView *)arg1;
@end

