//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@class NSData;

@interface ETPHeader : PBCodable <NSCopying>
{
    long long _sendDate;
    unsigned int _baseColor;
    NSData *_messageData;
    int _messageType;
    struct {
        unsigned int sendDate:1;
        unsigned int baseColor:1;
        unsigned int messageType:1;
    } _has;
}

- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)mergeFrom:(id)arg1;
@property(retain, nonatomic) NSData *messageData; // @synthesize messageData=_messageData;
@property(nonatomic) BOOL hasBaseColor;
@property(readonly, nonatomic) BOOL hasMessageData;
@property(nonatomic) BOOL hasSendDate;
@property(nonatomic) BOOL hasMessageType;
@property(nonatomic) long long sendDate; // @synthesize sendDate=_sendDate;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
@property(nonatomic) unsigned int baseColor; // @synthesize baseColor=_baseColor;
@property(nonatomic) int messageType; // @synthesize messageType=_messageType;

@end

