//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NRDeviceDiscoveryControllerXPCFrameworkDelegate.h"
#import "NSXPCConnectionDelegate.h"

@class NSArray, NSMutableArray, NSString, NSXPCConnection;

@interface NRDeviceDiscoveryController : NSObject <NRDeviceDiscoveryControllerXPCFrameworkDelegate, NSXPCConnectionDelegate>
{
    NSArray *_devices;
    NSMutableArray *_mutableDevices;
    unsigned int _counter;
    NSXPCConnection *_xpcConnection;
}

+ (id)sharedInstance;
@property(nonatomic) unsigned int counter; // @synthesize counter=_counter;
@property(retain, nonatomic) NSMutableArray *mutableDevices; // @synthesize mutableDevices=_mutableDevices;
- (void)xpcDidRestartDiscovery;
- (void)xpcDidDiscoverDevice:(id)arg1 deviceID:(id)arg2 advertisedName:(id)arg3;
- (BOOL)_xpcConnectToService;
- (void)xpcAssertInClient:(id)arg1;
- (void)xpcSetValue:(id)arg1 forProperty:(id)arg2 deviceID:(id)arg3;
@property(retain, nonatomic) NSXPCConnection *xpcConnection; // @synthesize xpcConnection=_xpcConnection;
@property(readonly, nonatomic) NSArray *devices; // @synthesize devices=_devices;
- (void).cxx_destruct;
- (void)end;
- (void)begin;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

