//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NPSManager, NSArray, NSMutableArray, NSObject<OS_dispatch_queue>, NSString;

@interface NGSInternalSettingsManager : NSObject
{
    NSMutableArray *_glanceDefinitions;
    NPSManager *_syncManager;
    NSArray *_storedSettings;
    NSString *_selectedGlanceIdentifier;
    NSObject<OS_dispatch_queue> *_queue;
}

- (BOOL)hasMaximumNumberOfActiveGlances;
- (id)glanceIdentifierForGlanceDefinitionAtIndex:(unsigned int)arg1;
- (id)glanceDefinitionForWatchKitIdentifier:(id)arg1;
- (id)glanceDefinitionForGlanceIdentifier:(id)arg1;
- (id)glanceDefinitionForAppBundleIdentifier:(id)arg1;
- (void)moveGlanceDefinitionFromIndex:(unsigned int)arg1 toIndex:(unsigned int)arg2;
- (void)removeGlanceDefinitionsInArray:(id)arg1;
- (void)addGlanceDefinition:(id)arg1;
@property(readonly, nonatomic) BOOL hasSettings;
@property(copy, nonatomic) NSString *selectedGlanceIdentifier;
- (unsigned int)_numberOfActiveGlances;
- (id)_localizedNameForGlance:(id)arg1;
- (void)enumerateGlanceDefinitionsUsingBlock:(CDUnknownBlockType)arg1;
- (void)_saveSettings;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (id)init;
- (void)saveSettings;
- (void)loadSettings;

@end

