//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface NGSSettingsGlancePath : NSObject
{
    BOOL _isEnabledByDefault;
    NSString *_bundleDirPath;
}

@property(nonatomic) BOOL isEnabledByDefault; // @synthesize isEnabledByDefault=_isEnabledByDefault;
@property(retain, nonatomic) NSString *bundleDirPath; // @synthesize bundleDirPath=_bundleDirPath;
- (void).cxx_destruct;

@end

