//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CAShapeLayer, UILabel;

@interface CUISAlertChevronView : UIView
{
    UILabel *_label;
    unsigned int _direction;
    CAShapeLayer *_chevronLayer;
    struct CGRect _chevronRect;
    BOOL _flat;
}

@property(nonatomic) BOOL flat; // @synthesize flat=_flat;
- (id)initWithLabel:(id)arg1 chevronDirection:(unsigned int)arg2;
- (void)_updatePathBent:(struct CGPath *)arg1;
- (void)_updatePathFlat:(struct CGPath *)arg1;
- (void)setFlat:(BOOL)arg1 animated:(BOOL)arg2;
- (void)_updateChevron;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setLabelText:(id)arg1;

@end

