//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImage, UIImageView;

@interface CUISAlertIconView : UIView
{
    UIImageView *_imageView;
    UIImageView *_shadowView;
    UIImage *_icon;
    UIImage *_shadow;
    unsigned int _iconType;
}

@property(retain, nonatomic) UIImage *icon; // @synthesize icon=_icon;
- (void)setIcon:(id)arg1 idealIconSize:(struct CGSize)arg2;
- (id)_nameForDeviceVariant:(int)arg1;
- (id)_nameForIconType:(unsigned int)arg1;
@property(nonatomic) unsigned int iconType; // @synthesize iconType=_iconType;
- (void)setIcon:(id)arg1 idealIconSize:(struct CGSize)arg2 iconType:(unsigned int)arg3;
@property(retain, nonatomic) UIImage *shadow; // @synthesize shadow=_shadow;
- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIImageView *shadowView; // @synthesize shadowView=_shadowView;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

