//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PUICTableViewDataSource.h"
#import "PUICTableViewDelegate.h"

@class NSArray, NSMapTable, NSString, PUICActionItem, PUICTableView, PUICTableViewCell;

@interface CUISBulletinActionMenu : NSObject <PUICTableViewDataSource, PUICTableViewDelegate>
{
    PUICTableView *_tableView;
    PUICTableViewCell *_selectedActionCell;
    id <CUISBulletinActionMenuDelegate> _delegate;
    NSArray *_actionItems;
    PUICActionItem *_dismissItem;
    NSMapTable *_cellToBackgroundMap;
}

+ (void)initialize;
- (id)initWithActionItems:(id)arg1;
@property(retain, nonatomic) NSArray *actionItems; // @synthesize actionItems=_actionItems;
@property(retain, nonatomic) NSMapTable *cellToBackgroundMap; // @synthesize cellToBackgroundMap=_cellToBackgroundMap;
@property(retain, nonatomic) PUICActionItem *dismissItem; // @synthesize dismissItem=_dismissItem;
@property(retain, nonatomic) PUICTableViewCell *selectedActionCell; // @synthesize selectedActionCell=_selectedActionCell;
- (id)initWithActionItems:(id)arg1 createDismissItem:(BOOL)arg2 customDismissText:(id)arg3;
- (void)_dismissAction:(id)arg1;
- (void)setSelectedActionCellTintColor:(id)arg1;
- (void)deselectActionCell;
- (void).cxx_destruct;
@property(retain, nonatomic) PUICTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <CUISBulletinActionMenuDelegate> delegate; // @synthesize delegate=_delegate;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

