//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CUISBulletinActionMenu, NSDictionary, NSSet;

@protocol CUISBulletinQuickLongLook <NSObject>
- (void)animateDismissLongLookWithCompletion:(void (^)(BOOL))arg1;
- (void)animateToLongLookIfReadyWithCompletion:(void (^)(BOOL))arg1;
- (void)animateInLongLookWithDuration:(double)arg1 completion:(void (^)(BOOL))arg2;
- (void)animateInQuickLookWithDuration:(double)arg1 completion:(void (^)(BOOL))arg2;
- (void)setQuickLongLookDelegate:(id <CUISBulletinQuickLongLookDelegate>)arg1;
- (unsigned int)presentationMode;
- (void)setPresentationMode:(unsigned int)arg1;

@optional
- (NSDictionary *)headerActionLaunchOptions;
- (NSSet *)alertSuppressionContexts;
- (void)alertBackgroundDidChange;
- (BOOL)hasSelectedAction;
- (void)setActionMenu:(CUISBulletinActionMenu *)arg1;
@end

