//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CUISAlertPlatterView;

@interface CUISBulletinActionMenuCellBackground : UIView
{
    CUISAlertPlatterView *_platterView;
}

- (void)setPlatterTintColor:(id)arg1;
- (void).cxx_destruct;
- (void)_removeAllAnimations:(BOOL)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

