//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface CUISBulletinClientFactory : NSObject
{
    NSArray *_bulletins;
    NSObject *_attachment;
    id <CUISBulletinClientFactoryDelegate> _delegate;
}

+ (void)prepareForBulletins;
- (id)actionItems;
- (unsigned int)allowedAudioFeedbackByOtherAlerts;
- (void)presentationActivelyDismissed;
- (id)alternateSubtitle;
- (id)customBulletinIcon;
- (id)shortDescriptionFormatForCoalescedBulletins;
- (id)clientViewController;
- (BOOL)playCustomBulletinSound;
- (BOOL)shouldClearBulletinsAfterDismissal;
- (BOOL)shouldPresentActionMenu;
- (id)actionMenuPresentation;
- (id)secondaryPagePresentation;
- (id)primaryPagePresentation;
- (BOOL)supportsCreatePrimaryPagePresentationAsychronously;
- (id)initWithBulletins:(id)arg1 attachment:(id)arg2;
- (id)initWithBulletins:(id)arg1;
- (void).cxx_destruct;
- (id)userActivity;
@property(nonatomic) __weak id <CUISBulletinClientFactoryDelegate> delegate; // @synthesize delegate=_delegate;

@end

