//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CUISBulletinTextAttributes, UIColor, UIFont;

@interface CUISBulletinLongLookLayoutAttributes : NSObject
{
}

+ (void)initialize;
+ (id)sharedInstance;
@property(readonly, nonatomic) float headerPlatterHeight;
@property(readonly, nonatomic) float actionMenuOffset;
@property(readonly, nonatomic) float platterLeftRightInset;
@property(readonly, nonatomic) UIFont *bodyFont;
@property(readonly, nonatomic) UIColor *contentPlatterColor;
@property(readonly, nonatomic) CUISBulletinTextAttributes *bodyTextAttributes;
@property(readonly, nonatomic) CUISBulletinTextAttributes *subtitleTextAttributes;
@property(readonly, nonatomic) UIColor *headerPlatterColor;
- (float)clientContentOffset;
@property(readonly, nonatomic) struct UIEdgeInsets contentInsets;
@property(readonly, nonatomic) UIFont *titleFont;
@property(readonly, nonatomic) CUISBulletinTextAttributes *titleTextAttributes;

@end

