//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface CUISGlanceView : UIView
{
    struct CGRect _cueViewRect;
    struct CGRect _contentViewRect;
    struct CGRect _backgroundViewRect;
    float _contentCorrnerRadius;
    UIView *_cueView;
    UIView *_backgroundView;
    UIView *_contentView;
}

@property(retain, nonatomic) UIView *cueView;
- (void).cxx_destruct;
@property(retain, nonatomic) UIView *backgroundView;
@property(retain, nonatomic) UIView *contentView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

