//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UILabel;

@interface CUISGlanceCardView : UIView
{
    UIView *_contentView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
}

+ (BOOL)_bigLayout;
+ (void)initLayouts;
- (void)_createContentView;
- (void)_createSubtitle;
- (void)_anchorLabelAtBaselineCenter:(id)arg1;
- (void)_createTitle;
- (float)_float:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(copy, nonatomic) NSString *subtitle;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(copy, nonatomic) NSString *title;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

