//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "PUICActivityIndicatorViewDelegate.h"

@class NSString, PUICActivityIndicatorView, PUICStatusView;

@interface _PUICStatusBarGlobalContextIndicatorsView : UIView <PUICActivityIndicatorViewDelegate>
{
    PUICActivityIndicatorView *_activityView;
    BOOL _activityViewSpinningUpOrDown;
    PUICStatusView *_statusView;
}

@property(readonly, nonatomic) PUICStatusView *statusView;
- (BOOL)_activityIsAnimating;
- (BOOL)_statusViewIsActive;
- (void)_layoutSubviews;
- (void)activityIndicatorViewDidAnimateOut:(id)arg1;
- (void)activityIndicatorViewWillAnimateOut:(id)arg1 duration:(double)arg2;
- (void)activityIndicatorViewDidAnimateIn:(id)arg1;
- (void)activityIndicatorViewWillAnimateIn:(id)arg1 duration:(double)arg2;
- (void).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)setNeedsLayout;
@property(readonly, nonatomic) PUICActivityIndicatorView *activityIndicatorView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

