//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextView.h"

@interface _PUICDictationTextView : UITextView
{
    BOOL _needsEnsureBottomRowVisible;
}

@property(nonatomic) BOOL needsEnsureBottomRowVisible; // @synthesize needsEnsureBottomRowVisible=_needsEnsureBottomRowVisible;
- (void)ensureBottomRowVisibleIfNeeded;
- (void)layoutSubviews;

@end

