//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PepperUICore/_PUICAdditiveValueAnimation.h>

@class CASpringAnimation;

@interface _PUICAdditiveValueSpringAnimation : _PUICAdditiveValueAnimation
{
    CASpringAnimation *_springAnimation;
}

@property(nonatomic) float stiffness;
- (void)_updateDuration;
- (void).cxx_destruct;
@property(nonatomic) float mass;
@property(nonatomic) float damping;
- (double)fractionForTime:(double)arg1;
- (double)duration;
- (id)init;

@end

