//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class _PUICPagePickerView;

@protocol _PUICPagePickerViewDelegate <NSObject>
- (void)pagePickerViewDidUpdateSelectedPageItemIndex:(_PUICPagePickerView *)arg1;

@optional
- (void)pagePickerView:(_PUICPagePickerView *)arg1 didMinimize:(BOOL)arg2;
- (void)pagePickerViewWillMinimize:(_PUICPagePickerView *)arg1;
- (void)pagePickerView:(_PUICPagePickerView *)arg1 didMaximize:(BOOL)arg2;
- (void)pagePickerViewWillMaximize:(_PUICPagePickerView *)arg1;
@end

