//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PUICCrownIndicatorWindow, PUICCrownView;

@interface _PUICCrownIndicator : NSObject
{
    id displayer;
    PUICCrownIndicatorWindow *_crownWindow;
    PUICCrownView *_crownView;
}

+ (float)trackMinY;
+ (float)trackMinX;
+ (float)trackCornerRadius;
+ (float)trackHeight;
+ (id)trackBackgroundColor;
+ (double)hideAnimationDuration;
+ (id)acquireCrownIndicatorFor:(id)arg1;
+ (id)sharedIndicatorForDisplayer:(id)arg1;
+ (id)_sharedIndicator;
+ (struct CGRect)windowFrame;
@property(retain, nonatomic) PUICCrownView *crownView; // @synthesize crownView=_crownView;
@property(retain, nonatomic) PUICCrownIndicatorWindow *crownWindow; // @synthesize crownWindow=_crownWindow;
- (void)_resetWindowLevel;
@property(nonatomic) __weak id displayer; // @synthesize displayer;
@property(nonatomic) BOOL usingCrown;
@property(nonatomic) float visibleLength;
- (void).cxx_destruct;
- (void)setVisible:(BOOL)arg1 animated:(BOOL)arg2;
@property(nonatomic, getter=isVisible) BOOL visible;
@property(nonatomic) float length;
@property(nonatomic) float offset;
- (id)init;

@end

