//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PepperUICore/PUICQuickboardViewController.h>

#import "NCABContactDetailViewControllerDelegate.h"
#import "NCABContactListViewControllerDelegate.h"

@class NSString;

@interface PUICQuickboardContactsListViewController : PUICQuickboardViewController <NCABContactListViewControllerDelegate, NCABContactDetailViewControllerDelegate>
{
}

- (id)initWithDelegate:(id)arg1;
- (void)contactDetailViewController:(id)arg1 didPickEntry:(id)arg2 ofType:(int)arg3 withLabel:(id)arg4 forContact:(void *)arg5;
- (void)contactListViewController:(id)arg1 didPickContact:(void *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

