//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "PUICStatusViewDataSource.h"
#import "UIStatusBarServerClient.h"

@class NSArray, NSDictionary, NSMutableArray, NSString, UILabel, UIStatusBarServer, _PUICStatusBarGlobalContextIndicatorsView;

@interface PUICStatusBarGlobalContextView : UIView <UIStatusBarServerClient, PUICStatusViewDataSource>
{
    UILabel *_time;
    _PUICStatusBarGlobalContextIndicatorsView *_indicatorsView;
    float _indicatorsOffset;
    _Bool _animatingTime;
    _Bool _tookAssertion;
    _Bool _networkActivity;
    NSArray *_statusViewStates;
    NSDictionary *_statusViewStatesMap;
    NSMutableArray *_animationsQueue;
    unsigned int _animationsInFight;
    unsigned int _layoutBehaviorOverride;
    unsigned int _currentLayoutBehavior;
    BOOL _inForeground;
    _Bool _currentDataIsStale;
    UIStatusBarServer *_statusBarServer;
}

@property(nonatomic) _Bool currentDataIsStale; // @synthesize currentDataIsStale=_currentDataIsStale;
@property(nonatomic) unsigned int layoutBehaviorOverride; // @synthesize layoutBehaviorOverride=_layoutBehaviorOverride;
- (id)initFromProperties:(id)arg1;
- (void)applyProperties:(id)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_kickOffIndicatorsAnimation:(id)arg1;
- (void)_kickOffTimeAnimation:(id)arg1;
- (void)_initializeStatusObjectsIfNecessary;
- (void)_adjustStatesForData:(const CDStruct_6ed4d2ba *)arg1 animated:(BOOL)arg2 forceCycle:(_Bool)arg3;
- (void)_updateTime:(id)arg1;
- (void)_updateWithStatusBarData:(const CDStruct_6ed4d2ba *)arg1 withActions:(int)arg2;
@property(nonatomic) BOOL inForeground; // @synthesize inForeground=_inForeground;
- (void)_stateUnsupressed:(id)arg1;
- (void)_stateSuppressed:(id)arg1;
- (void)_takeVisibleAssertion;
- (void)_releaseVisibleAssertion;
- (void)_dequeuAnimations;
- (void)_layoutGlobalContextViews;
- (unsigned int)layoutBehavior;
@property(retain, nonatomic) UIStatusBarServer *statusBarServer; // @synthesize statusBarServer=_statusBarServer;
- (void)_activityIndicatorChanged:(id)arg1;
- (void)_updateStatusBarServerRegistration;
- (id)_getInitialTimeString;
- (void)setTimeHidden:(BOOL)arg1 animation:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setTimeHidden:(BOOL)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setIndicatorsHidden:(BOOL)arg1 animation:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setIndicatorsHidden:(BOOL)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
@property(nonatomic, getter=isDisconnectedIndicatorSuppressed) _Bool suppressDisconnectedIndicator;
@property(nonatomic, getter=isDoNotDisturbIndicatorSuppressed) _Bool suppressDoNotDisturbIndicator;
@property(nonatomic, getter=isAirplaneModeIndicatorSuppressed) _Bool suppressAirplaneModeIndicator;
@property(nonatomic, getter=isChargingIndicatorSuppressed) _Bool suppressChargingIndicator;
- (BOOL)areIndicatorsHidden;
- (void)setIndicatorsHidden:(BOOL)arg1 duration:(double)arg2 animation:(unsigned long long)arg3 completion:(CDUnknownBlockType)arg4;
- (BOOL)isTimeHidden;
- (void)setTimeHidden:(BOOL)arg1 duration:(double)arg2 animation:(unsigned long long)arg3 completion:(CDUnknownBlockType)arg4;
- (id)stateByIndex:(unsigned int)arg1 forStatusView:(id)arg2;
- (unsigned int)numberOfStatesForStatusView:(id)arg1;
- (void).cxx_destruct;
- (void)_willEnterForeground:(id)arg1;
- (void)_didEnterBackground:(id)arg1;
- (void)statusBarServer:(id)arg1 didReceiveDoubleHeightStatusString:(id)arg2 forStyle:(int)arg3;
- (void)statusBarServer:(id)arg1 didReceiveGlowAnimationState:(BOOL)arg2 forStyle:(int)arg3;
- (void)statusBarServer:(id)arg1 didReceiveStyleOverrides:(int)arg2;
- (void)statusBarServer:(id)arg1 didReceiveStatusBarData:(const CDStruct_6ed4d2ba *)arg2 withActions:(int)arg3;
- (id)properties;
- (void)willMoveToSuperview:(id)arg1;
- (void)didMoveToSuperview;
- (void)layoutSubviews;
- (id)init;
- (void)setHidden:(BOOL)arg1;
- (void)setNeedsLayout;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

