//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PepperUICore/PUICQuickboardListViewController.h>

@class NSArray;

@interface PUICQuickboardMessageViewController : PUICQuickboardListViewController
{
    BOOL _allowsEmojiInput;
    NSArray *_messages;
    id <PUICQuickboardEmojiViewControllerDelegate> _emojiDelegate;
}

+ (id)emojiImage;
@property(nonatomic) __weak id <PUICQuickboardEmojiViewControllerDelegate> emojiDelegate; // @synthesize emojiDelegate=_emojiDelegate;
- (void)emojiButtonTapped:(id)arg1;
@property(nonatomic) BOOL allowsEmojiInput; // @synthesize allowsEmojiInput=_allowsEmojiInput;
@property(retain, nonatomic) NSArray *messages; // @synthesize messages=_messages;
- (id)additionalTrayButtons;
- (void)didSelectListItem:(int)arg1;
- (id)cellForListItem:(int)arg1;
- (float)heightForListItem:(int)arg1 width:(float)arg2;
- (int)numberOfListItems;
- (id)newCell;
- (id)initWithDelegate:(id)arg1 dictationMode:(int)arg2;
- (void).cxx_destruct;

@end

