//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class PUICEmojiSelectionView;

@protocol PUICEmojiSelectionViewDelegate
- (BOOL)emojiSelectionView:(PUICEmojiSelectionView *)arg1 supportsEmojiType:(int)arg2;
- (void)emojiSelectionView:(PUICEmojiSelectionView *)arg1 didSelectEmojiType:(int)arg2;
@end

