//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PepperUICore/PUICQuickboardViewController.h>

#import "PUICSiriFlamesViewDelegate.h"
#import "_PUICDictationStrategyDelegate.h"

@class CSLSAlertSuppressionAssertion, CSLSBacklightAssertion, NSString, PUICContentUnavailableView, PUICSiriFlamesView, UITapGestureRecognizer, UIView, _PUICDictationTextView;

@interface PUICDictationViewController : PUICQuickboardViewController <PUICSiriFlamesViewDelegate, _PUICDictationStrategyDelegate>
{
    _PUICDictationTextView *_textView;
    PUICSiriFlamesView *_flamesView;
    struct CGRect _flamesViewFrame;
    id <_PUICDictationStrategy> _strategy;
    CSLSBacklightAssertion *_backlightAssertion;
    CSLSAlertSuppressionAssertion *_alertSuppressionAssertion;
    UIView *_selectedViewForDismissalAnimation;
    PUICContentUnavailableView *_contentUnavailableView;
    UITapGestureRecognizer *_tapRecognizer;
    BOOL _shouldDisableDictation;
    BOOL _startDictationAutomatically;
    id <PUICDictationViewControllerDelegate> _dictationDelegate;
    int _dictationMode;
}

- (id)initWithDelegate:(id)arg1;
- (void)_showDisambiguationResultsControllerForQuery:(id)arg1 transcribedObjects:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)_dictationResultsView;
- (void)_disableDictation;
- (void)hideContentWithCompletion:(CDUnknownBlockType)arg1;
- (void)tickleBacklightAssertion;
- (void)strategyDidFailWithError:(id)arg1;
- (void)strategyDidCancel;
- (void)strategyIsProcessing;
- (void)strategyIsStillListening;
- (void)strategyDidBeginListening;
- (void)strategyDidFailWithError:(id)arg1 title:(id)arg2 message:(id)arg3;
- (void)setSelectedViewForDismissalAnimation:(id)arg1;
- (void)clearAssertions;
- (void)removeSiriFlames;
- (void)cleanupDictation;
- (void)blockLowPriorityAlerts;
- (void)keepScreenOn;
- (void)addSiriFlames;
@property(nonatomic) BOOL startDictationAutomatically; // @synthesize startDictationAutomatically=_startDictationAutomatically;
- (void)tapAcceptButton;
- (void)setTextViewFont:(id)arg1;
@property(nonatomic) int dictationMode; // @synthesize dictationMode=_dictationMode;
@property(nonatomic) __weak id <PUICDictationViewControllerDelegate> dictationDelegate; // @synthesize dictationDelegate=_dictationDelegate;
- (float)audioLevelForFlamesView:(id)arg1;
- (void)flamesViewTapped:(id)arg1;
@property(readonly, nonatomic) PUICDictationViewController *dictationViewController;
- (void)strategyDidFinish;
- (void)addContentViewAnimations:(BOOL)arg1;
- (void)acceptButtonTappedWithCompletion:(CDUnknownBlockType)arg1;
- (void)setShowsAcceptButton:(BOOL)arg1;
- (id)initWithDelegate:(id)arg1 dictationMode:(int)arg2;
- (void)addDismissalAnimationsWithOptions:(unsigned int)arg1;
- (void).cxx_destruct;
- (id)textView;
- (void)startDictation;
- (void)cancelDictation;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (BOOL)canBecomeFirstResponder;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

