//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableView.h"

#import "PUICCrownInputSequencerDataSource.h"
#import "PUICCrownInputSequencerDelegate.h"
#import "PUICTableViewCellActionBarDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class NSArray, NSDictionary, NSIndexPath, NSString, NSTimer, PUICCrownInputSequencer, PUICSectionIndexOverlayView, PUICTableViewCellActionBar, UIPanGestureRecognizer, UIView;

@interface PUICTableView : UITableView <PUICCrownInputSequencerDelegate, PUICCrownInputSequencerDataSource, UIGestureRecognizerDelegate, PUICTableViewCellActionBarDelegate>
{
    UIPanGestureRecognizer *_swipeActionPanRecognizer;
    float _initialTranslation;
    PUICTableViewCellActionBar *_actionBar;
    BOOL _swipingLeft;
    struct {
        unsigned int dataSourceSectionIndexTitlesForTableView:1;
        unsigned int dataSourceTableViewSectionForSectionIndexTitleAtIndex:1;
        unsigned int dataSourceCanEditRow:1;
        unsigned int delegateDeleteConfirmationButton:1;
        unsigned int delegateSwipeAccessoryButton:1;
        unsigned int delegateSwipeControlMask:1;
        unsigned int delegateTitleForDeleteButton:1;
        unsigned int delegateTitleForAccessoryButton:1;
        unsigned int delegateWillPerformAction:1;
        unsigned int delegateDidPerformAction:1;
        unsigned int delegateEditActionsForRow:1;
        unsigned int madeSwipedCellViewsTransparent:1;
    } _puicFlags;
    BOOL _sectionIndexOverlayHidden;
    PUICSectionIndexOverlayView *_sectionIndexOverlayView;
    UIView *_sectionIndexOverlayDimmingView;
    NSString *_sectionIndexOverlayTitle;
    NSTimer *_delayedSectionIndexOverlayHidingTimer;
    PUICCrownInputSequencer *_sectionIndexOverlaySequencer;
    PUICCrownInputSequencer *_crownVelocityTrackingSequencer;
    BOOL _hasLoadedSectionIndexTitles;
    NSArray *_sectionIndexTitles;
    NSDictionary *_sectionToSectionTitleMap;
    int _externalSectionIndexMinimumDisplayRowCount;
    BOOL _showsSectionIndexOverlayOnCrownScroll;
    NSIndexPath *_swipedIndexPath;
}

+ (void)_setFrame:(struct CGRect)arg1 onTransformedView:(id)arg2;
@property(nonatomic) BOOL showsSectionIndexOverlayOnCrownScroll; // @synthesize showsSectionIndexOverlayOnCrownScroll=_showsSectionIndexOverlayOnCrownScroll;
- (float)openThresholdForActionBar:(id)arg1;
- (void)setSwipedIndexPath:(id)arg1 animated:(BOOL)arg2;
- (void)deleteRowAtIndexPath:(id)arg1 animated:(BOOL)arg2;
- (void)swipeRecognizerDidRecognize:(id)arg1;
- (void)setCellSwipeEnabled:(BOOL)arg1;
- (BOOL)cellSwipeEnabled;
- (unsigned int)nextStateForActionBar:(id)arg1;
- (void)actionBar:(id)arg1 tappedButtonForAction:(id)arg2;
- (id)actionsForActionBar:(id)arg1;
- (void)_setSectionIndexOverlayTitle:(id)arg1;
- (void)_delayedSectionIndexOverlayHidingTimerFired:(id)arg1;
- (void)_puic_contentOffsetDidChange;
- (id)_crownVelocityTrackingSequencer;
- (unsigned int)_numberOfSectionIndexTitles;
- (void)_setSectionIndexOverlayHidden:(BOOL)arg1 animated:(BOOL)arg2;
- (BOOL)_canShowSectionIndexOverlay;
- (void)_scheduleDelayedSectionIndexOverlayHiding;
- (void)_cancelDelayedSectionIndexOverlayHiding;
- (int)_sectionIndexForSectionTitleAtIndex:(int)arg1;
- (void)_performNonDestructiveAction:(id)arg1 atIndexPath:(id)arg2;
- (void)_performDestructiveAction:(id)arg1 atIndexPath:(id)arg2;
- (void)_moveCell:(id)arg1 toSwipeOffset:(float)arg2 animated:(BOOL)arg3 actionButtonsHidden:(BOOL)arg4 completion:(CDUnknownBlockType)arg5;
- (float)_rubberBandOffsetForOffset:(float)arg1 usingActionBar:(id)arg2;
- (id)_swipedCell;
@property(retain, nonatomic) NSIndexPath *swipedIndexPath; // @synthesize swipedIndexPath=_swipedIndexPath;
- (void)_swipeRecognizerEnded:(id)arg1 wasCancelled:(BOOL)arg2;
- (void)_swipeRecognizerChanged:(id)arg1;
- (void)_swipeRecognizerBegan:(id)arg1;
- (BOOL)_canSwipeToEditRowAtIndexPath:(id)arg1;
- (id)_sectionIndexOverlaySequencer;
- (void)_updateSectionIndexOverlayViewText;
- (void)_updateSectionIndexOverlayContentsAndVisibility;
- (void)_updateSectionIndexOverlaySequencer;
- (int)_numberOfRows;
- (void)resetSwipedRowAnimated:(BOOL)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)_setSectionIndexOverlayRubberbandFactor:(float)arg1;
- (void)_layoutSectionIndexOverlayView;
- (void)_updateSectionTitlesIfNecessary;
- (void)_cleanupDelayedSectionIndexOverlayHidingTimer;
- (void)_disableDefaultUITableViewIndexBar;
- (BOOL)_crownInputSequencerShouldSuppressInput:(id)arg1;
- (void)crownInputSequencerAverageCrownVelocityDidChange:(id)arg1;
- (void)crownInputSequencerIdleDidChange:(id)arg1;
- (void)crownInputSequencerOffsetDidChange:(id)arg1;
- (void).cxx_destruct;
- (void)setSectionIndexMinimumDisplayRowCount:(int)arg1;
- (int)sectionIndexMinimumDisplayRowCount;
- (void)reloadSections:(id)arg1 withRowAnimation:(int)arg2;
- (void)reloadSectionIndexTitles;
- (id)initWithFrame:(struct CGRect)arg1 style:(int)arg2;
- (id)deleteConfirmationIndexPath;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (id)_titleForSwipeAccessoryButtonForRowAtIndexPath:(id)arg1;
- (id)_swipeAccessoryButtonForRowAtIndexPath:(id)arg1;
- (id)_titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg1;
- (id)_deleteConfirmationButtonForRowAtIndexPath:(id)arg1;
- (BOOL)_shouldDisplayExtraSeparatorsAtOffset:(float *)arg1;
- (void)setContentOffset:(struct CGPoint)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)_wheelChangedWithEvent:(id)arg1;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (void)layoutSubviews;
- (void)reloadData;
@property(nonatomic) id <PUICTableViewDelegate> delegate;
@property(nonatomic) id <PUICTableViewDataSource> dataSource;
- (id)initWithCoder:(id)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

