//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegateFlowLayout.h"
#import "UIGestureRecognizerDelegate.h"

@class NSArray, NSObject<PUICRecentEmojiViewDelegate>, NSString, PUICEmojiSelectionView, UICollectionView;

@interface PUICRecentEmojiView : UIView <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, UIGestureRecognizerDelegate>
{
    NSArray *_recentEmojiStrings;
    NSArray *_defaultEmojiStrings;
    UICollectionView *_collectionView;
    NSObject<PUICRecentEmojiViewDelegate> *_delegate;
    PUICEmojiSelectionView *_selectionView;
}

@property(nonatomic) __weak PUICEmojiSelectionView *selectionView; // @synthesize selectionView=_selectionView;
- (void)updateWithDefaultEmojiStrings;
- (void)updateWithRecentEmojiStrings:(id)arg1;
- (id)_emojiStringForIndexPath:(id)arg1;
- (void).cxx_destruct;
- (void)clear;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(int)arg3;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(int)arg3;
- (void)activate;
- (void)deactivate;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (int)numberOfSectionsInCollectionView:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
@property(readonly, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void)_handleSwipe:(id)arg1;
@property(nonatomic) __weak NSObject<PUICRecentEmojiViewDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

