//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, PUICActionGroup, UIImage, UIView;

@interface PUICActionItem : NSObject
{
    BOOL _needsItemUpdateNotification;
    BOOL _active;
    BOOL _enabled;
    BOOL _hidden;
    int _tag;
    int _actionItemType;
    UIImage *_image;
    NSString *_title;
    UIView *_leftAccessoryView;
    PUICActionGroup *_actionGroup;
    id _target;
    SEL _action;
}

+ (id)actionItemWithImage:(id)arg1 actionItems:(id)arg2;
+ (id)actionItemWithImage:(id)arg1 target:(id)arg2 action:(SEL)arg3;
+ (id)actionItemWithTitle:(id)arg1 actionGroup:(id)arg2;
+ (id)actionItemWithTitle:(id)arg1 actionItems:(id)arg2;
+ (id)actionItemWithImage:(id)arg1 title:(id)arg2 actionGroup:(id)arg3;
+ (id)actionItemWithImage:(id)arg1 title:(id)arg2 actionItems:(id)arg3;
+ (id)actionItemWithTitle:(id)arg1 target:(id)arg2 action:(SEL)arg3;
+ (id)actionItemWithImage:(id)arg1 title:(id)arg2 target:(id)arg3 action:(SEL)arg4;
- (void)_setNeedsItemUpdateNotification;
- (id)_initWithImage:(id)arg1 title:(id)arg2 target:(id)arg3 action:(SEL)arg4 actionItems:(id)arg5;
- (id)_initWithImage:(id)arg1 title:(id)arg2 target:(id)arg3 action:(SEL)arg4 actionGroup:(id)arg5;
@property(copy, nonatomic) NSArray *actionItems;
@property(retain, nonatomic) PUICActionGroup *actionGroup; // @synthesize actionGroup=_actionGroup;
@property(retain, nonatomic) UIView *leftAccessoryView; // @synthesize leftAccessoryView=_leftAccessoryView;
@property(nonatomic) int actionItemType; // @synthesize actionItemType=_actionItemType;
- (void).cxx_destruct;
@property(nonatomic, getter=isActive) BOOL active; // @synthesize active=_active;
@property(nonatomic) SEL action; // @synthesize action=_action;
@property(nonatomic) int tag; // @synthesize tag=_tag;
@property(nonatomic, getter=isEnabled) BOOL enabled; // @synthesize enabled=_enabled;
@property(nonatomic) __weak id target; // @synthesize target=_target;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (id)init;
@property(nonatomic, getter=isHidden) BOOL hidden; // @synthesize hidden=_hidden;

@end

