//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIPresentationController.h"

@interface PUICActionPresentationController : UIPresentationController
{
}

- (BOOL)_shouldChangeStatusBarViewController;
- (id)initWithPresentedViewController:(id)arg1 presentingViewController:(id)arg2;
- (int)presentationStyle;
- (BOOL)shouldPresentInFullscreen;
- (BOOL)shouldRemovePresentersView;

@end

