//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFSiriContext, NSArray, NSString, PUICDictationViewController;

@protocol PUICDictationViewControllerDelegate <NSObject>

@optional
- (AFSiriContext *)contextForDictationViewController:(PUICDictationViewController *)arg1;
- (NSString *)languageCodeForDictationViewController:(PUICDictationViewController *)arg1;
- (void)dictationViewController:(PUICDictationViewController *)arg1 didRecognizeTranscriptionObjects:(NSArray *)arg2 languageModel:(NSString *)arg3;
@end

