//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIView;

@interface PUICActionSheetItem : NSObject
{
    BOOL _enabled;
    BOOL _selected;
    BOOL _loading;
    BOOL _shouldRemainSelected;
    BOOL _shouldDismiss;
    NSString *_title;
    int _titleAlignment;
    int _style;
    CDUnknownBlockType _actionHandler;
    UIView *_accessoryView;
    UIView *_contentView;
}

+ (id)actionWithTitle:(id)arg1 style:(int)arg2 actionHandler:(CDUnknownBlockType)arg3;
@property(copy, nonatomic) CDUnknownBlockType actionHandler; // @synthesize actionHandler=_actionHandler;
@property(nonatomic) BOOL shouldRemainSelected; // @synthesize shouldRemainSelected=_shouldRemainSelected;
@property(nonatomic, getter=isLoading) BOOL loading; // @synthesize loading=_loading;
@property(nonatomic) BOOL shouldDismiss; // @synthesize shouldDismiss=_shouldDismiss;
@property(nonatomic) int titleAlignment; // @synthesize titleAlignment=_titleAlignment;
- (void).cxx_destruct;
@property(retain, nonatomic) UIView *accessoryView; // @synthesize accessoryView=_accessoryView;
@property(nonatomic, getter=isSelected) BOOL selected; // @synthesize selected=_selected;
@property(nonatomic) int style; // @synthesize style=_style;
@property(nonatomic, getter=isEnabled) BOOL enabled; // @synthesize enabled=_enabled;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (id)init;

@end

