//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PepperUICore/PUICBaseActionViewController.h>

#import "CSLPIButtonHandlerProtocol.h"
#import "UIGestureRecognizerDelegate.h"

@class NSArray, NSMapTable, NSMutableArray, NSString, PUICActionCancelGestureRecognizer, PUICActionGroup, PUICActionItem, PUICApplicationStatusBarItem, PUICHyphenatedLabel, UIView, UIViewController;

@interface PUICActionViewController : PUICBaseActionViewController <UIGestureRecognizerDelegate, CSLPIButtonHandlerProtocol>
{
    BOOL _actionGroupDirty;
    BOOL _appearing;
    BOOL _visible;
    PUICActionGroup *_actionGroup;
    UIViewController *_viewControllerForStatusBarForwarding;
    CDUnknownBlockType _completionHandler;
    CDUnknownBlockType _selectHandler;
    NSArray *_actionItems;
    NSMapTable *_buttonByActionItem;
    NSMutableArray *_dirtyActionItems;
    int _effectiveActionStyle;
    PUICActionItem *_selectedActionItem;
    UIView *_headerView;
    PUICHyphenatedLabel *_messageLabel;
    PUICApplicationStatusBarItem *_statusBarItem;
    NSMutableArray *_actionButtonCache;
    PUICActionCancelGestureRecognizer *_cancelGestureRecognizer;
}

@property(retain, nonatomic) PUICActionCancelGestureRecognizer *cancelGestureRecognizer; // @synthesize cancelGestureRecognizer=_cancelGestureRecognizer;
@property(retain, nonatomic) NSMutableArray *actionButtonCache; // @synthesize actionButtonCache=_actionButtonCache;
@property(nonatomic) __weak PUICApplicationStatusBarItem *statusBarItem; // @synthesize statusBarItem=_statusBarItem;
@property(nonatomic) BOOL appearing; // @synthesize appearing=_appearing;
@property(retain, nonatomic) PUICActionItem *selectedActionItem; // @synthesize selectedActionItem=_selectedActionItem;
@property(nonatomic) int effectiveActionStyle; // @synthesize effectiveActionStyle=_effectiveActionStyle;
@property(retain, nonatomic) NSMutableArray *dirtyActionItems; // @synthesize dirtyActionItems=_dirtyActionItems;
@property(retain, nonatomic) NSMapTable *buttonByActionItem; // @synthesize buttonByActionItem=_buttonByActionItem;
@property(copy, nonatomic) NSArray *actionItems; // @synthesize actionItems=_actionItems;
@property(nonatomic, getter=isActionGroupDirty) BOOL actionGroupDirty; // @synthesize actionGroupDirty=_actionGroupDirty;
@property(copy, nonatomic) CDUnknownBlockType selectHandler; // @synthesize selectHandler=_selectHandler;
@property(nonatomic) __weak UIViewController *viewControllerForStatusBarForwarding; // @synthesize viewControllerForStatusBarForwarding=_viewControllerForStatusBarForwarding;
@property(retain, nonatomic) PUICActionGroup *actionGroup; // @synthesize actionGroup=_actionGroup;
- (void)blurDidGenerate;
- (void)setupDidDisappear;
- (void)setupWillDisappear;
- (void)setupDidAppear;
- (void)setupWillAppear;
- (id)initWithActionGroup:(id)arg1 sourceView:(id)arg2 selectHandler:(CDUnknownBlockType)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (_Bool)handleButton:(unsigned int)arg1 eventType:(unsigned int)arg2;
- (void)dismissWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)_actionGroupDidUpdateNotification:(id)arg1;
- (void)_actionButtonClick:(id)arg1;
- (struct CGPoint)_initialOffsetForView:(id)arg1;
- (void)_setScale:(float)arg1 animated:(BOOL)arg2;
- (BOOL)_needsLongTitleLayoutForButtons:(id)arg1 withNumberOfRows:(int)arg2;
- (void)_applyActionItem:(id)arg1 toButton:(id)arg2 withActionStyle:(int)arg3;
- (void)_updateForChangedActionGroupAnimated:(BOOL)arg1;
- (void)_unregisterForNotificationsForActionGroup:(id)arg1;
- (void)_cleanUpActionButton:(id)arg1;
- (void)_invokeCompletionHandler;
- (id)_createButtonForActionItem:(id)arg1 withActionStyle:(int)arg2;
- (void)_cancelGesture:(id)arg1;
- (void)_actionItemDidUpdateNotification:(id)arg1;
- (void)_registerForNotificationsForActionGroup:(id)arg1;
- (id)puic_applicationStatusBarItem;
@property(retain, nonatomic) PUICHyphenatedLabel *messageLabel; // @synthesize messageLabel=_messageLabel;
- (id)_visibleViews;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
- (void).cxx_destruct;
@property(nonatomic) BOOL visible; // @synthesize visible=_visible;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
- (void)_layout;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (BOOL)canBecomeFirstResponder;
- (BOOL)prefersStatusBarHidden;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

