//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PUICStatusBarLayoutManager : NSObject
{
    unsigned int _numberOfVisibleGlobalContexts;
    _Bool _ignoreVisibleAssertionsForGlobalContextVisibleFrame;
    unsigned int _globalContextLayoutBehavior;
    struct CGRect _globalContextVisibleFrame;
}

+ (id)sharedInstance;
@property(nonatomic) unsigned int globalContextLayoutBehavior; // @synthesize globalContextLayoutBehavior=_globalContextLayoutBehavior;
@property(nonatomic) _Bool ignoreVisibleAssertionsForGlobalContextVisibleFrame; // @synthesize ignoreVisibleAssertionsForGlobalContextVisibleFrame=_ignoreVisibleAssertionsForGlobalContextVisibleFrame;
@property(nonatomic) struct CGRect globalContextVisibleFrame; // @synthesize globalContextVisibleFrame=_globalContextVisibleFrame;
- (void)releaseGlobalContextVisibleAssertion;
- (void)takeGlobalContextVisibleAssertion;
- (id)init;

@end

