//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PepperUICore/PUICClientSideAnimation.h>

@interface PUICRepeatingClientSideAnimation : PUICClientSideAnimation
{
    BOOL _stopScheduled;
    unsigned int _stopAfterIteration;
    double _elapsedTimeAtScheduledStop;
}

- (void)cancelScheduledStop;
- (void)stopAfterReachingEnd;
- (void)_stopAfterIteration:(unsigned int)arg1 withElapsedTime:(double)arg2;
- (unsigned int)_currentIteration;
- (void)_getEffectiveElapsedTime:(double *)arg1 finished:(char *)arg2;
- (void)_reset;

@end

