//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, PUICButton, UIColor;

@interface PUICSideBySideButtonsView : UIView
{
    PUICButton *_leftButton;
    PUICButton *_rightButton;
    BOOL _shouldCalculateFontSize;
    BOOL _primaryButtonEnabled;
    BOOL _secondaryButtonEnabled;
    NSString *_primaryButtonTitle;
    NSString *_secondaryButtonTitle;
    CDUnknownBlockType _primaryActionBlock;
    CDUnknownBlockType _secondaryActionBlock;
    int _style;
    unsigned int _controlEvents;
    UIColor *_primaryColor;
    float _primaryButtonPlatterAlpha;
}

+ (void)_setupSideBySideButtonsSpec;
@property(nonatomic) float primaryButtonPlatterAlpha; // @synthesize primaryButtonPlatterAlpha=_primaryButtonPlatterAlpha;
@property(nonatomic) unsigned int controlEvents; // @synthesize controlEvents=_controlEvents;
@property(nonatomic, getter=isSecondaryButtonEnabled) BOOL secondaryButtonEnabled; // @synthesize secondaryButtonEnabled=_secondaryButtonEnabled;
@property(copy, nonatomic) CDUnknownBlockType secondaryActionBlock; // @synthesize secondaryActionBlock=_secondaryActionBlock;
@property(copy, nonatomic) CDUnknownBlockType primaryActionBlock; // @synthesize primaryActionBlock=_primaryActionBlock;
- (void)_adjustFontSizeFittingPrimaryLabel:(id)arg1 secondaryLabel:(id)arg2 inSize:(struct CGSize)arg3;
- (void)_secondaryButtonAction:(id)arg1;
@property(copy, nonatomic) NSString *secondaryButtonTitle; // @synthesize secondaryButtonTitle=_secondaryButtonTitle;
- (void)_primaryButtonAction:(id)arg1;
@property(copy, nonatomic) NSString *primaryButtonTitle; // @synthesize primaryButtonTitle=_primaryButtonTitle;
@property(nonatomic, getter=isPrimaryButtonEnabled) BOOL primaryButtonEnabled; // @synthesize primaryButtonEnabled=_primaryButtonEnabled;
- (id)_primaryAppColor;
- (id)_defaultBackgroundColor;
- (id)_defaultTextColor;
@property(retain, nonatomic) UIColor *primaryColor; // @synthesize primaryColor=_primaryColor;
- (void).cxx_destruct;
@property(nonatomic) int style; // @synthesize style=_style;
- (struct CGSize)intrinsicContentSize;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

