//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CADisplayLink, NSMutableArray;

@interface PUICZoomModel : NSObject
{
    CADisplayLink *_displayLink;
    BOOL _nudgeSetZoomEnable;
    float _snapRange;
    float _nudgeRange;
    float _minMovementTimeout;
    float _maxMovementTimeout;
    float _velocityTimeoutFactor;
    float _lisaRatio;
    float _snapSpeed;
    float _animateSpeed;
    unsigned char _velocityAverageDepth;
    unsigned char _velocityUIAverageDepth;
    float _startVelocityThreshold;
    float _runVelocityThreshold;
    float _stopTimeout;
    float _nonWeightedRatio;
    float _zoomAnimationSpeed;
    float _lastZoom;
    BOOL _snapDirection;
    float _nudgedAtZoom;
    float _cumulativeLisaDistance;
    float _velocity;
    NSMutableArray *_oldVelocities;
    float _UIVelocity;
    NSMutableArray *_UIVelocities;
    float _movementTimer;
    float _movementTimeout;
    float _startZoomLevel;
    int _lisaState;
    int _previousLisaState;
    _Bool _didRedraw;
    BOOL _crownEnabled;
    BOOL _weightedAtIntegerLevels;
    _Bool _updating;
    BOOL _shouldNotNudge;
    id <PUICZoomModelDelegate> _delegate;
    float _zoomLevel;
    float _animatedZoomLevel;
    float _maxZoomLevel;
    float _minZoomLevel;
    float _clientZoom;
}

+ (_Bool)nudgeDefaultSet;
+ (_Bool)hwHasLinearActuator;
+ (float)appFullZoomLevel;
@property(readonly, nonatomic) float zoomLevel; // @synthesize zoomLevel=_zoomLevel;
- (void)setZoomLevel:(float)arg1;
@property(nonatomic) float clientZoom; // @synthesize clientZoom=_clientZoom;
@property(nonatomic) BOOL shouldNotNudge; // @synthesize shouldNotNudge=_shouldNotNudge;
@property(readonly, nonatomic) _Bool updating; // @synthesize updating=_updating;
@property(nonatomic) BOOL weightedAtIntegerLevels; // @synthesize weightedAtIntegerLevels=_weightedAtIntegerLevels;
@property(nonatomic) float maxZoomLevel; // @synthesize maxZoomLevel=_maxZoomLevel;
@property(nonatomic) BOOL crownEnabled; // @synthesize crownEnabled=_crownEnabled;
@property(readonly, nonatomic) float animatedZoomLevel; // @synthesize animatedZoomLevel=_animatedZoomLevel;
- (void)addCrownTicks:(int)arg1;
- (void)setZoomLevelSimulated:(float)arg1;
- (void)setZoomLevelFromListener:(float)arg1;
- (void)updateZoomLevelDisplayLink:(id)arg1;
- (void)nudgeIfNeeded;
- (void)setUpdating:(_Bool)arg1;
- (void)updateZoomWithDistance:(float)arg1;
- (float)closestNudgeZoom;
- (_Bool)atZoomLevel;
- (void)updateZoomLevel;
- (void)setZoomLevel:(float)arg1 animated:(BOOL)arg2;
- (void)setZoomLevel:(float)arg1 animated:(BOOL)arg2 nudge:(BOOL)arg3;
- (void)_setZoomLevel:(float)arg1;
- (void)_setAnimatedZoomLevel:(float)arg1;
@property(nonatomic) float minZoomLevel; // @synthesize minZoomLevel=_minZoomLevel;
- (void)_changeLisaState:(int)arg1;
- (float)closestZoom;
- (void).cxx_destruct;
- (_Bool)isZoomAnimating;
@property(nonatomic) __weak id <PUICZoomModelDelegate> delegate; // @synthesize delegate=_delegate;
- (id)init;

@end

