//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSRecursiveLock;

@interface CSLPIWeakNotificationCenter : NSObject
{
    NSMutableDictionary *_notifications;
    NSRecursiveLock *_lock;
}

+ (id)defaultCenter;
- (void)_removeObserver:(id)arg1 name:(id)arg2 object:(id)arg3 matchObject:(_Bool)arg4;
- (void)_handleNotification:(id)arg1;
- (void).cxx_destruct;
- (void)postNotification:(id)arg1;
- (void)removeObserver:(id)arg1;
- (void)postNotificationName:(id)arg1 object:(id)arg2 userInfo:(id)arg3;
- (void)postNotificationName:(id)arg1 object:(id)arg2;
- (void)removeObserver:(id)arg1 name:(id)arg2 object:(id)arg3;
- (id)description;
- (id)init;
- (void)addObserver:(id)arg1 selector:(SEL)arg2 name:(id)arg3 object:(id)arg4;

@end

