//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CSLPIBacklight : NSObject
{
}

+ (_Bool)willBeOn;
+ (_Bool)screenBlanked;
+ (_Bool)screenOn;
+ (void)setProvider:(id)arg1;
+ (id)provider;

@end

