//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSLPIDispatchTimer, NSString;

@interface CSLPIRecursiveSystemActivityAssertion : NSObject
{
    NSString *_identifier;
    CSLPIDispatchTimer *_timeoutTimer;
    unsigned int _assertionID;
    int _count;
}

- (id)initWithIdentifier:(id)arg1 timeout:(double)arg2;
- (void)_timeoutAssertion;
- (void)takeAssertion;
@property(readonly, nonatomic, getter=isAsserted) _Bool asserted;
- (void)releaseAssertion;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end

