//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSLPIDispatchTimer, NSObject<OS_dispatch_queue>, NSString;

@interface CSLPITimer : NSObject
{
    CSLPIDispatchTimer *_dispatchTimer;
    void *_dispatchQueueKey;
    _Bool _disableSystemWaking;
    _Bool _scheduled;
    NSString *_serviceIdentifier;
    NSObject<OS_dispatch_queue> *_queue;
    CDUnknownBlockType _handler;
    double _fireInterval;
    double _leewayInterval;
    double _wallClockFireTime;
}

+ (id)scheduledTimerWithFireInterval:(double)arg1 leewayInterval:(double)arg2 serviceIdentifier:(id)arg3 queue:(id)arg4 handler:(CDUnknownBlockType)arg5;
@property(nonatomic) _Bool disableSystemWaking; // @synthesize disableSystemWaking=_disableSystemWaking;
@property(nonatomic, getter=isScheduled) _Bool scheduled; // @synthesize scheduled=_scheduled;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) double leewayInterval; // @synthesize leewayInterval=_leewayInterval;
- (void)_fireTimer;
- (void)_scheduleDispatchTimerWithFireTime:(unsigned long long)arg1;
- (void)_dispatchTimerFired;
- (id)initWithFireInterval:(double)arg1 leewayInterval:(double)arg2 serviceIdentifier:(id)arg3 queue:(id)arg4 handler:(CDUnknownBlockType)arg5;
- (_Bool)isDispatchScheduled;
@property(nonatomic) double wallClockFireTime; // @synthesize wallClockFireTime=_wallClockFireTime;
- (void)fireTimer;
- (void)cancelDispatchTimer;
- (void)scheduleDispatchTimerInSeconds:(double)arg1;
- (void)schedule;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
- (id)description;
- (id)init;
- (void)dealloc;
- (void)cancel;
@property(nonatomic) double fireInterval; // @synthesize fireInterval=_fireInterval;
@property(copy, nonatomic) NSString *serviceIdentifier; // @synthesize serviceIdentifier=_serviceIdentifier;

@end

