//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface CSLPIScheduledSystemWake : NSObject
{
    NSDate *_wakeDate;
    NSString *_identifier;
}

- (void)cancelWake;
- (void)scheduleWake:(double)arg1;
- (void).cxx_destruct;
- (id)initWithIdentifier:(id)arg1;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)description;
- (id)init;

@end

